Check if a template exists when inheriting templates
contao/contao pull request #1016
Opened 2019-11-26 09:45 UTC by leofeyer

Fixes #798 

I am not sure about the performance implications here as the `file_exists()` check is done inside the `while` loop. We could also do

```php
if (!include $strParent)
{
    throw new \Exception('…');
}
```

@contao/developers WDYT?

2019-11-26 09:47 UTC, Toflar commented
What about a simple

```php

if (false === (@include $strParent)) {
    // handle error
}
```
?

2019-11-26 09:49 UTC, aschempp commented
I wonder if that's a behavior change? Didn't it currently simply use an empty output if the file was not found?

2019-11-26 09:58 UTC, leofeyer commented
Silencing the include is not a good idea: https://github.com/contao/core/pull/5440

2019-11-26 09:59 UTC, Toflar commented
But now that we are in PHP7 times? :)

2019-11-26 10:11 UTC, leofeyer commented
The silence operator will still silence errors in the included template: https://3v4l.org/FRT8Y

2019-11-26 10:20 UTC, aschempp requested changes
This does not make sense to me. The behavior will change, as the file include is now required. If this is desired, then we should use `require` instead of `include`, and a try-catch would then still be unnecessary.

2019-11-26 10:35 UTC, leofeyer commented
Based on your comment, I suggest you read the original issue to understand what this PR is aiming to fix. 🤷‍♂

2019-11-28 15:45 UTC, leofeyer commented
As discussed in Mumble on November 28th, we want to add the `file_exists()` check but only to prevent the include and log the missing template in `tl_log`. Throwing an exception would be a BC break.

2019-12-03 08:31 UTC, leofeyer commented
I have adjusted the PR accordingly.

2019-12-03 08:34 UTC, aschempp approved these changes

2019-12-03 08:37 UTC, Toflar approved these changes

2019-12-03 08:53 UTC, bytehead approved these changes

2019-12-03 09:29 UTC, merged