Add @internal to what is not covered by our BC promise
contao/contao pull request #1045
Opened 2019-12-03 15:45 UTC by leofeyer

Implements #1031 

**TODO**

* [ ] What about controllers? Do they need an `@internal` tag, too?
* [ ] What about `Contao\CoreBundle\Repository\RememberMeRepository`?
* [ ] What about `Contao\ManagerBundle\Api\*`?
* [ ] What about `Contao\ManagerBundle\ContaoManager\ApiCommand\*`?

2019-12-03 17:02 UTC, Toflar requested changes
LGTM, found one issue in the comments.
Regarding your questions:

* What about controllers? Do they need an @internal tag, too?

I don't see why they would need to be extended. So yes.

* What about Contao\CoreBundle\Repository\RememberMeRepository?

I don't see why repositories would need to be extended. So yes.

* What about Contao\ManagerBundle\Api\*?
* What about Contao\ManagerBundle\ContaoManager\ApiCommand\*?

Imho the whole manager bundle is internal. What do you need to use or extend there?

2019-12-03 17:02 UTC, Toflar commented on calendar-bundle/src/Picker/EventPickerProvider.php
> +     * @internal Do not inherit from this class; decorate the "contao.cache.clear_internal" service instead
I guess that's a mistake here?

2019-12-03 17:04 UTC, leofeyer commented on calendar-bundle/src/Picker/EventPickerProvider.php
> +     * @internal Do not inherit from this class; decorate the "contao.cache.clear_internal" service instead
Indeed. 🤦‍♂

2019-12-03 17:25 UTC, leofeyer commented on calendar-bundle/src/Picker/EventPickerProvider.php
> +     * @internal Do not inherit from this class; decorate the "contao.cache.clear_internal" service instead
Fixed in 3c7da70f61f2474ea81b445cadb56cff27fe7383.

2019-12-04 08:17 UTC, Toflar approved these changes
LGTM. I'd like to have other approvals though.

2019-12-05 11:35 UTC, merged

2019-12-05 11:35 UTC, leofeyer commented
It seems no-one else was interested in reviewing, therefore I have merged this one now. 🤷‍♂

2019-12-09 14:35 UTC, aschempp commented
> It seems no-one else was interested in reviewing, therefore I have merged this one now. 🤷‍♂

That's not really true, looks like two days was not enough time 😉