[POC] Rebuild login process
contao/contao pull request #1130
Opened 2019-12-23 09:34 UTC by bytehead

As discussed in Slack on 12th of December 2019, we want to rebuild the login process in Contao 4.9 so both the username/password login and the 2FA login use the delay scheme as described in the [RFC](https://tools.ietf.org/html/rfc4226#section-7.3):
> Another option would be to implement a delay scheme to avoid a brute
force attack. After each failed attempt A, the authentication server
would wait for an increased TA number of seconds, e.g., say T = 5,
then after 1 attempt, the server waits for 5 seconds, at the second
failed attempt, it waits for 5 * 2 = 10 seconds, etc.

This implies that `$user->loginCount` is set to `0` by default and is incremented with each failed login attempt. Then `$user->locked` is set to `$user->loginCount * 5` seconds, so the lock period increases with each failed login attempt.

There are several advantages compared to the current logic, e.g. we do not have to inform the administrator about locked accounts and we do not have to configure the lock time and number of login attempts anymore – which was one of the bigger issues with this PR.

2019-12-23 11:05 UTC, bytehead commented
This is just a first attempt, maybe there is more to cover or the refactor. What do you think?

2019-12-23 11:32 UTC, m-vo commented
I like!

2019-12-23 12:20 UTC, Toflar commented
Instead of a migration that turns all the `loginCount` values into `0` we could just drop that column and name it `loginAttempts` with a default value of `0`. It's more descriptive and migration is not needed :)

2019-12-29 12:28 UTC, DeDan69 commented
Since this is my first post, I apologize in advance if I am doing something wrong. So first, my greetings to all Contao developers out there. You are doing a great job! I am deeply impressed.

Let's come to my point for this RFC discussion:
Could you please also consider a point that I would sketch out as "Security by Design"?
Today, the Contao4 login is available via root-url/contao. Since knowledge about the target is an important key for any "brute force attack", I wonder if it would not be an advantage if the Contao admin could define the backend directory himself, via configuration file in /app/config/?
Merci

2019-12-29 15:09 UTC, xchs commented
So you're actually suggesting security through obscurity?

2019-12-29 17:03 UTC, DeDan69 commented
> So you're actually suggesting security through obscurity?

No, and I'm not here to argue. I wish to construtivly contribute.  Clarity or ambiguity is for me only a question of documentation. By default it certainly could remain as it is. But neglecting safety aspects to achieve an apparent clarity could be a disservice in the end. Why not leave the decision to the admin of the site? Autonomy is ultimately the big brother of open source. Or am I wrong? Cheers

2019-12-30 09:16 UTC, fritzmg commented
Obfuscation of the back end login URL is a common feature of other systems as well.

2019-12-30 18:12 UTC, ausi commented
> if the Contao admin could define the backend directory himself, via configuration file in /app/config/?

This should already be possible if you add the following lines to your *routing.yml* file I think:

```yml
contao_backend:
    path: /admin
contao_backend_login:
    path: /admin/login
```

2019-12-30 19:53 UTC, bytehead commented
> This should already be possible if you add the following lines to your routing.yml file I think:

```yml
contao_backend:
    path: /admin
contao_backend_login:
    path: /admin/login
```
Don't forget to adapt the firewall configuration (`access_control`) in `security.yml` to the new paths:
```yml
access_control:
    - { path: ^/contao/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/contao/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/contao(/|$), roles: ROLE_USER }
    - { path: ^/_contao/two-factor$, roles: [IS_AUTHENTICATED_2FA_IN_PROGRESS, ROLE_MEMBER] }
    - { path: ^/, roles: [IS_AUTHENTICATED_2FA_IN_PROGRESS, IS_AUTHENTICATED_ANONYMOUSLY] }
```

2019-12-31 12:15 UTC, Mynyx commented
For usability reasons the account should not be locked after the first failure. I would propose to accept three attempts before starting to lock the account.

This would not decrease the security level, because in opposite to the currenct implementation the login attempts counter ist not reset.

2020-01-01 09:32 UTC, DeDan69 commented
> > This should already be possible if you add the following lines to your routing.yml file I think:
> 
> ```yaml
> contao_backend:
>     path: /admin
> contao_backend_login:
>     path: /admin/login
> ```
> 
> Don't forget to adapt the firewall configuration (`access_control`) in `security.yml` to the new paths:
> 
> ```yaml
> access_control:
>     - { path: ^/contao/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
>     - { path: ^/contao/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
>     - { path: ^/contao(/|$), roles: ROLE_USER }
>     - { path: ^/_contao/two-factor$, roles: [IS_AUTHENTICATED_2FA_IN_PROGRESS, ROLE_MEMBER] }
>     - { path: ^/, roles: [IS_AUTHENTICATED_2FA_IN_PROGRESS, IS_AUTHENTICATED_ANONYMOUSLY] }
> ```

Happy new Year!
Thanks a lot for your efforts. All what Ausi and you replied seemed to me very logical and clear, but in the end I am not successful. It seems I am missing an important point that would allow contao to find its sources at the newly defined path. So far 404 is returned.  -Thanks.

2020-01-01 13:11 UTC, bytehead commented
I never tried by myself. Possibly there is a lot of resource paths hard wired (like css and javascript files).

2020-01-02 16:25 UTC, leofeyer requested changes
This PR is almost complete IMHO. 👍 

There are a few inconsistencies though:

1. When an account is locked for 5 seconds, I can submit more username/password combinations without increasing the lock period. However, when I do the same with the TOTP tokens, the lock period is increased upon every submit.

2. When a user enters a wrong username/password combination, we log an "Invalid password submitted" message. We never log an "Invalid verification code" message though. Why not?

2020-01-07 08:39 UTC, aschempp reviewed
Looks pretty good so far! I wonder why we do/have to split the logic across `AuthenticationProvider`, event listeners and success/failure handlers. Why not "just" have everything in success and failure handlers in the first place? But maybe we should merge this first and then (try to) optimize.

2020-01-07 08:39 UTC, aschempp commented on core-bundle/src/Resources/contao/dca/tl_member.php
> +		'loginAttempts' => array
I'm pretty sure the DBAL Schema Migration will try to rename this field… It's not really a problem though, as the delay seconds is only applied if the password is wrong, so it would be increased 15 secs instead of 5 secs on the first login. I'm really fine with that.

2020-01-07 08:39 UTC, aschempp commented on core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
>          $this->user->lastLogin = $this->user->currentLogin;
I wonder if we should change this too, only store the time a 2FA was successful (if enabled for the user)?

2020-01-07 08:39 UTC, aschempp commented on core-bundle/src/Security/Authentication/Provider/AuthenticationProvider.php
> +        if ($user->loginAttempts < 1) {
I'm not sure this process is correct. According to the docblock, the user should be locked for 5 secs after the first attempt. But this is not the case here. Maybe this block is more a leftover of a not-locked login attempt, which does not exist anymore?

On the other hand, it does not really make sense to lock after the first attempt and show a "your locked for 5secs" ?

2020-01-07 08:39 UTC, aschempp commented on core-bundle/tests/Security/User/UserCheckerTest.php
> +        $user->locked = time() + 5;
@ausi won't this result in time issues similar to the image tests?

2020-01-07 08:39 UTC, aschempp commented on core-bundle/tests/Security/Exception/LockedExceptionTest.php
> -        $this->assertSame(5, $exception->getLockedMinutes());
The `getLockedMinutes` method is deprecated, but it's still there. Still makes sense to test it works correctly.

2020-01-07 09:32 UTC, bytehead commented on core-bundle/tests/Security/Exception/LockedExceptionTest.php
> -        $this->assertSame(5, $exception->getLockedMinutes());
Should not. It uses the ClockMock from Symfony/phpunit-bridge.

2020-01-07 09:32 UTC, bytehead commented on core-bundle/tests/Security/User/UserCheckerTest.php
> +        $user->locked = time() + 5;
Should not. It uses the ClockMock from Symfony/phpunit-bridge.

2020-01-07 09:33 UTC, bytehead commented
> Why not "just" have everything in success and failure handlers in the first place? 

I've asked this myself. I'll check if it's somehow easy to refactor.

2020-01-07 09:34 UTC, bytehead commented on core-bundle/tests/Security/Exception/LockedExceptionTest.php
> -        $this->assertSame(5, $exception->getLockedMinutes());
Valid point :)

2020-01-08 09:00 UTC, bytehead commented
> 1. When an account is locked for 5 seconds, I can submit more username/password combinations without increasing the lock period. However, when I do the same with the TOTP tokens, the lock period is increased upon every submit.

I have to check.

> 2. When a user enters a wrong username/password combination, we log an "Invalid password submitted" message. We never log an "Invalid verification code" message though. Why not?

I don't know. Should it?

2020-01-09 16:30 UTC, leofeyer commented
> I don't know. Should it?

I don't know, either. 😄 But it should be consistent, I think, so either log both or none. WDYT?

2020-01-09 16:34 UTC, bytehead commented
> I think, so either log both or none. WDYT?

Definitely.
But I don't have a preference, as I don't care about this messages. 🤷‍♂
@contao/developers WDYT?

2020-01-09 16:36 UTC, Toflar commented
I wouldn't log it at all. Just floods the logs and what info does it provide? If someone cannot log in anymore they will get in touch with me, I'll try myself and notice myself that the password is wrong :D

2020-01-10 10:52 UTC, leofeyer commented on core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
>          $this->user->lastLogin = $this->user->currentLogin;
I think so, too.

2020-01-10 10:53 UTC, leofeyer commented
Ok, then we will drop the "user entered a wrong username and password" log messages entirely.

2020-01-10 12:50 UTC, Mynyx commented
I do not think it is a good practice to remove the log messages. They could be helpful to analyse unauthorised access or attacks. 

It is also an OWASP recommendation: https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#logging-and-monitoring

2020-01-10 17:24 UTC, leofeyer commented
You can still see the failed login requests in the server log, which is a better starting point to analyse attacks anyway IMHO.

2020-01-14 14:45 UTC, leofeyer commented
Closed in favor of #1178

2020-01-14 14:45 UTC, closed without merging