Get universal picker url parameters via own method
contao/contao pull request #1154
Opened 2020-01-03 12:20 UTC by rabauss

see: https://github.com/contao/contao/pull/579#issuecomment-570549619

2020-01-03 12:40 UTC, Toflar submitted a review, later dismissed
LGTM 👍 I asked @aschempp for another review though :)

2020-01-03 15:31 UTC, aschempp submitted a review, later dismissed
It would probably require a custom picker builder and/or a custom DC_Table, but there‘s no reason not to add the flexibility 👍🏻

2020-01-06 14:41 UTC, leofeyer requested changes

2020-01-06 14:41 UTC, leofeyer commented on core-bundle/src/Resources/contao/widgets/Picker.php
> +	 * Return the extra parameters for picker url
```suggestion
	 * Return the extra parameters for the picker URL
```

2020-01-07 10:31 UTC, leofeyer approved these changes

2020-01-07 10:34 UTC, merged

2020-01-07 10:34 UTC, leofeyer commented
Thank you @rabauss.