Remove all form actions
contao/contao pull request #1201
Opened 2020-01-16 15:54 UTC by aschempp

fixes #1170

2020-01-16 20:52 UTC, ausi submitted a review, later dismissed

2020-01-16 21:32 UTC, leofeyer requested changes
I think I have found two left-over occurrences:

https://github.com/contao/contao/blob/abae57ab22d93118a008e587df0ab5f979c95060/newsletter-bundle/src/Resources/contao/classes/Newsletter.php#L540

https://github.com/contao/contao/blob/abae57ab22d93118a008e587df0ab5f979c95060/core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig#L5

2020-01-17 07:22 UTC, aschempp commented
Newsletter.php is adjusted. The action in the preview toolbar twig needs to remain, it does not post to the current URL but the preview entpoint.

2020-01-17 07:23 UTC, leofeyer approved these changes

2020-01-17 07:49 UTC, merged

2020-01-17 07:49 UTC, leofeyer commented
Thank you @aschempp.