Correctly highlight phrases in the search results
contao/contao pull request #1270
Opened 2020-01-31 16:50 UTC by leofeyer

Fixes #1061 

The PR synchronizes the keywords with the matched words of each result so we can highlight phrases and wildcard matches correctly. However, I had to change the return type of the `Search::searchFor()` method to accomplish this, which is an API change (BC break).

@contao/developers Not sure what is more important in this case – remaining BC or fixing the issue?

2020-01-31 16:52 UTC, aschempp requested changes
why not modify the existing result set to keep BC?

2020-01-31 16:52 UTC, fritzmg commented
Hm, can't you process the database result in `ModuleSearch` after `$arrResult = \Search::searchFor` instead?

2020-01-31 16:55 UTC, leofeyer commented
> why not modify the existing result set to keep BC?

That only works for models. `Result::fetchAllAssoc()` will reset the result and thus the modified fields. 😢 

> Hm, can't you process the database result in `ModuleSearch` after `$arrResult = \Search::searchFor` instead?

No, because we do not have `$arrKeywords`, `$arrIncluded`, `$arrWildcards` and `$arrPhrases` there. Of course I could pass these via reference, however, the `Search::searchFor()` method has 6 arguments already and would have 10 then. 🙈

2020-01-31 16:59 UTC, fritzmg commented
Hm, what about simply changing the database result object on the fly within `searchFor` instead?

2020-01-31 17:01 UTC, leofeyer commented
> Hm, what about simply changing the database result object on the fly within `searchFor` instead?

See above:

> That only works for models. `Result::fetchAllAssoc()` will reset the result and thus the modified fields. 😢

2020-01-31 17:05 UTC, leofeyer commented
We could add a `getResultSet()` and `setResultSet()` method to the `Result` class, then I could modify the result set in the `Search::searchFor()` method. Not sure if this is better though…

2020-01-31 17:11 UTC, leofeyer commented
I was wrong about having to pass four additional arguments via reference (see above). We would only have to pass `$arrHighlight` as seventh argument to the `Search::searchFor()` method. That would be kind of ok as a trade-off I guess.

2020-01-31 17:33 UTC, aschempp commented
I don't understand. You can loop over the result set (instead of `fetchAllAssoc()`) and update each property – exactly like for models.

2020-01-31 17:33 UTC, leofeyer commented
It is pretty ugly now but it works and it does not break BC anymore. 🤷‍♂ 

<img width="702" alt="00" src="https://user-images.githubusercontent.com/1192057/73560898-2bbf7580-4458-11ea-8ee7-86c4e18d9760.png">

2020-01-31 17:34 UTC, leofeyer commented
> I don't understand. You can loop over the result set (instead of `fetchAllAssoc()`) and update each property – exactly like for models.

No, you cannot. The changes will be lost when the `ModuleSearch` class calls `fetchAllAssoc()`, which internally calls `reset()`.

2020-02-01 10:14 UTC, bytehead approved these changes

2020-02-01 10:47 UTC, ausi approved these changes

2020-02-01 13:20 UTC, Toflar approved these changes

2020-02-02 10:32 UTC, fritzmg approved these changes

2020-02-03 08:36 UTC, leofeyer commented
See #1274 for an alternative, cleaner approach.

2020-02-04 13:55 UTC, aschempp requested changes
Just because I get reminders to add a review… I'm for #1274

2020-02-14 12:02 UTC, leofeyer commented
Closed in favor of #1274.

2020-02-14 12:02 UTC, closed without merging