Correctly highlight phrases in the search results (alternative)
contao/contao pull request #1274
Opened 2020-02-03 08:35 UTC by leofeyer

This is an alternative approach to #1270 which does not require to pass a seventh argument via reference. It adds a public `overwrite()` method to the `Contao\Database\Result` class though.

@contao/developers Please let me know which variant you prefer.

2020-02-03 08:43 UTC, bytehead commented
👍 for this (#1274).

2020-02-03 10:25 UTC, fritzmg approved these changes

2020-02-03 10:33 UTC, bytehead approved these changes

2020-02-03 14:14 UTC, aschempp requested changes
I think it would be majorly more flexible to allow creating a `Database\Result` from array instead of a `DoctrineStatement`. The only necessary change would be to allow the first argument to be an array or a doctrine statement, and initialize the records accordingly.

2020-02-04 11:44 UTC, leofeyer commented
Not sure if that is a good idea. The `Result` class is actually supposed to work directly with the PHP resource object, so we do not have to load the entire result set into memory (you probably remember [how it used to work in Contao 3](https://github.com/contao/core/blob/3.5/system/modules/core/library/Contao/Database/Result.php)).

When we switched to Symfony and Doctrine in Contao 4, working with the PHP resource object was no longer possible, so we bit the bullet and now we import the entire result set into memory. However, there is also a `@todo` comment "Try to find a solution that works without fetchAll()".

So if we are sure that there will never be a solution that works without fetchAll(), we might as well allow to initialize the `Result` object from an array. But if we are not, we should keep the type hint.

@contao/developers Are we sure about it or are we not? 😉

2020-02-04 14:37 UTC, Toflar commented
If this one works reliably (which I cannot verify), I'm in favor of this variant as well.

2020-02-04 20:16 UTC, ausi commented
Created a pull request which removes `fetchAll()` from the `Result` class and allows creating a `Result` from an array: #1287

2020-02-05 08:29 UTC, fritzmg commented
> @contao/developers Are we sure about it or are we not? 😉

imho fixing the search highlighting is not important enough to remove to disregard that todo 😉

2020-02-14 17:16 UTC, leofeyer commented
Closed in favor of #1335.

2020-02-14 17:16 UTC, closed without merging