Generate catch all routes for 404 pages
contao/contao pull request #1321
Opened 2020-02-13 16:05 UTC by aschempp

fixes #999

2020-02-14 12:15 UTC, leofeyer requested changes
How about naming the services `route_404_provider`, `route_404_router` and `route_404_matcher`? Would be more consistent and it would also fix the sorting problem. 😄

2020-02-14 17:39 UTC, aschempp commented
There's no sorting problem, they are now sorted by type (like the regular services are as well) 🤷‍♂

2020-02-17 15:58 UTC, leofeyer approved these changes

2020-02-17 16:04 UTC, merged

2020-02-17 16:04 UTC, leofeyer commented
Thank you @aschempp