Only test if the page title matches partially
contao/contao pull request #133
Opened 2018-10-17 07:29 UTC by aschempp

This is forward compatible with Symfony Routing (#95) because the 404 message will not be identical.

2018-10-17 11:23 UTC, leofeyer requested changes

2018-10-17 11:23 UTC, leofeyer commented on core-bundle/tests/Functional/RoutingTest.php
> +                'Redirecting to http://root-with-index.local/en/',
This change is wrong and makes the tests fail. 

```suggestion
                'Redirecting to en/',
```

2018-10-17 11:23 UTC, leofeyer commented on core-bundle/tests/Functional/RoutingTest.php
> +                'Redirecting to http://root-with-index.local/en/',
This change is wrong and makes the tests fail. 

```suggestion
                'Redirecting to en/',
```

2018-10-17 11:32 UTC, aschempp commented on core-bundle/tests/Functional/RoutingTest.php
> +                'Redirecting to http://root-with-index.local/en/',
Sorry, that was only supposed to be in the in #95

2018-10-18 07:34 UTC, merged

2018-10-18 07:34 UTC, leofeyer commented
Thank you @aschempp.