Clear dev cache
contao/contao pull request #1369
Opened 2020-02-20 15:41 UTC by Toflar

Fixes https://github.com/contao/contao/issues/1361

2020-02-20 16:34 UTC, fritzmg commented
Aren't these command executed in the current environment anyway? Thus, if you do

```php
static::executeCommand('cache:clear --no-warmup', $event);
static::executeCommand('cache:clear --no-warmup --env=dev', $event);
```

and you configured the `APP_ENV` to be `dev` currently, the production cache will not actually get deleted, since it clears the `dev` cache both times.

2020-02-20 16:34 UTC, Toflar commented
Correct. That's your mistake then, isn't it?

2020-02-20 16:37 UTC, fritzmg commented
Not sure what you mean. This change is supposed to fix an issue that occurs, if you switch the environment, after a `composer update/install` for example. I am just showing, that this would only fix, if you go from `prod` to `dev`, but not from `dev` to `prod`.

2020-02-23 16:16 UTC, ausi commented
@fritzmg you mean we should use something like this?

```php
static::executeCommand('cache:clear --no-warmup --env=prod', $event);
static::executeCommand('cache:clear --no-warmup --env=dev', $event);
```

2020-02-23 16:42 UTC, fritzmg commented
Possibly. @Tastaturberuf mentioned in #1357, that apparently the Script Handler will always use `prod`. Haven't confirmed this myself yet.

2020-02-24 08:31 UTC, aschempp requested changes
*if* we wanna clear both environments, then adding `--env=prod` to the first call would certainly be correct.

2020-02-24 08:38 UTC, Toflar commented
I actually found the issue. We were using `getenv('APP_ENV')` which only works with real environment variables because at the time the script handler is executed, no `.env` file is handled.
We have to be explicit about our environments, I think it's correct now.

2020-02-24 09:12 UTC, ausi approved these changes

2020-02-24 09:18 UTC, aschempp approved these changes

2020-02-24 09:21 UTC, fritzmg approved these changes

2020-02-24 11:45 UTC, fritzmg commented
Shouldn't this be changed in Contao 4.4 as well?

2020-02-26 17:00 UTC, merged

2020-02-26 17:00 UTC, leofeyer commented
Thank you @Toflar.

2020-02-28 10:30 UTC, fritzmg commented
For some reason this is not working:

Contents of `var/cache/dev` after a request to the back end for example has been made, with `APP_ENV=dev`:

```
annotations.map
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php.meta
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.preload.php
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.xml
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.xml.meta
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainerCompiler.log
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainerDeprecations.log
ContainerDBMJOYw
ContainerYxAQez3
ContainerYxAQez3.legacy
doctrine
pools
profiler
twig
UrlGenerator.php
UrlGenerator.php.meta
UrlMatcher.php
UrlMatcher.php.meta
```

`composer install` output (excerpt):

```
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Added the web/app.php file.
Added the web/index.php file.
Added the web/preview.php file.

 // Clearing the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.



 // Clearing the cache for the dev environment with debug true


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.



 // Warming up the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.



 Trying to install assets as relative symbolic links.
```

Contents of `var/cache/dev` after `composer install`:

```
annotations.map
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php.meta
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.preload.php
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.xml
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.xml.meta
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainerCompiler.log
appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainerDeprecations.log
ContainerDBMJOYw
ContainerYxAQez3
ContainerYxAQez3.legacy
doctrine
pools
profiler
twig
UrlGenerator.php
UrlGenerator.php.meta
UrlMatcher.php
UrlMatcher.php.meta
```

Contents of `var/cache/dev` after `cache:clear --no-warmup --env=dev`:

```
ContainerDBMJOYw
ContainerDBMJOYw.legacy
```

I noticed this after installing an extension, while having `APP_ENV=dev` in my `.env`. Once installed, no services, routes or templates of that package where available. I had to manually clear the dev cache, even though it was supposed to be cleared during the `composer` process.