Make sure the subdirectory in the tmp folder exists
contao/contao pull request #1370
Opened 2020-02-20 16:16 UTC by Toflar

Seems like on some systems writing to the tmp dir is possible but if written to a sub directory, this requires to be present first.

2020-02-20 16:18 UTC, bytehead submitted a review, later dismissed

2020-02-21 09:07 UTC, leofeyer requested changes

2020-02-21 09:07 UTC, leofeyer commented on core-bundle/src/Resources/contao/classes/Crawl.php
> +			mkdir($crawLogsDir);
We should use `Filesystem::mkdir()` here. More robust implementation and better error handling.

2020-02-21 14:32 UTC, m-vo reviewed
Why not inject it as a dependency? This would allow mocking the call.

2020-02-21 15:03 UTC, Toflar commented
Because that whole class is not a service. There's no way to register properly as maintenance module yet.

2020-02-21 15:05 UTC, leofeyer approved these changes

2020-02-21 15:05 UTC, merged

2020-02-21 15:05 UTC, leofeyer commented
Thank you @Toflar.