Separate Fehlermeldung bei fehlendem JSON-LD
contao/contao pull request #1378
Opened 2020-02-21 15:50 UTC by chopsol

Wenn de JSON-LD Daten in der Ausgabe fehlen, z.B. wenn man Änderungen an der fe_page vorgenommen hatte, bricht der Indexer bisher mit der Fehlermeldung ab, das ausdrücklich die Indexierung unterbunden wurde. Das ist aber falsch da nur die JSON-LD Daten fehlten.
Durch die Entfernung des vorbelegten Wertes und Prüfen auf die Existenz des Schlüssels kann nun eine spearate Fehlermeldung auf das Fehlen der JSON-LD Daten hinweisen.

2020-02-24 08:24 UTC, aschempp commented
I'd rather think `extendMetaFromJsonLdScripts` should throw the exception directly? It *knows* whether there was JSON-LD data

2020-02-24 08:25 UTC, aschempp requested changes
I'd rather think extendMetaFromJsonLdScripts should throw the exception directly? It knows whether there was JSON-LD data.

2020-02-25 13:08 UTC, Toflar commented
No i think the way this is proposed in this PR should be fine. But the unit tests have to be adjusted accordingly :)

2020-02-27 10:40 UTC, leofeyer commented
See #1420.

2020-02-27 10:40 UTC, closed without merging