Revert the document.write() changes
contao/contao pull request #1424
Opened 2020-02-27 12:11 UTC by leofeyer

This reverts the changes from #1332 so TinyMCE is initialized correctly when loaded in a sub-palette (see https://github.com/contao/contao/issues/1313#issuecomment-591931996).

2020-02-27 12:11 UTC, aschempp submitted a review, later dismissed

2020-02-27 12:12 UTC, Toflar requested changes
Can we add a comment why we use document.write()? Otherwise we'll end up removing it again in two years.

2020-03-02 18:08 UTC, bytehead approved these changes

2020-03-02 18:13 UTC, Toflar approved these changes

2020-03-02 18:14 UTC, merged