Determine ptable dynamically
contao/contao pull request #1446
Opened 2020-03-01 23:36 UTC by fritzmg

Currently you have to do something like

```php
// src/Resources/contao/dca/tl_content.php
if (Contao\Input::get('do') == 'foo')
{
	$GLOBALS['TL_DCA']['tl_content']['config']['ptable'] = 'tl_foo';
}
```

in order to be able to use content elements for your own back end module's table. With this PR the parent table will be determined dynamically according to the back end module configurations.

2020-03-02 09:38 UTC, fritzmg commented
Failing tests looks unrelated to this PR (use of undefined constant `TL_MODE` in `core-bundle\src\Controller\BackendCsvImportController.php`).

2020-03-02 13:49 UTC, leofeyer requested changes
Maybe we can reduce the complexity of the `setDynamicPTable()` method with some early returns?

2020-03-02 13:49 UTC, leofeyer commented on core-bundle/src/Resources/contao/library/Contao/Controller.php
> +		if (!isset($GLOBALS['TL_DCA'][$strTable]['config']['ptable']) || empty($GLOBALS['TL_DCA'][$strTable]['config']['ptable']))
```suggestion
		if (empty($GLOBALS['TL_DCA'][$strTable]['config']['ptable']))
```

I'm pretty sure that `empty()` implies the `isset()` check.

2020-03-02 17:09 UTC, bytehead submitted a review, later dismissed

2020-03-10 09:53 UTC, aschempp reviewed
Interesting approach! I wonder if we ever need to set `ptable` at all, because it could be determined by this statement (regardless of being `dynamicPtable`)?

2020-03-10 09:53 UTC, aschempp commented on core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
> +					foreach ($module['tables'] ?? array() as $table)
```suggestion
				if ($do === $key && isset($module['tables']) && is_array($module['tables']))
				{
					foreach ($module['tables'] as $table)
```

2020-03-10 14:10 UTC, fritzmg commented
> Interesting approach! I wonder if we ever need to set `ptable` at all, because it could be determined by this statement (regardless of being `dynamicPtable`)?

In theory. But performance-wise it would be better to define it.

2020-03-10 15:51 UTC, Toflar commented
Is there any reason why the current code is not adjusted? I mean the one in news, calendar etc.

2020-03-10 16:06 UTC, fritzmg commented
> Is there any reason why the current code is not adjusted? I mean the one in news, calendar etc.

I only did not remove it, because there are still other adjustments that the news-bundle makes within `tl_content.php`. And then it is still more efficient to directly set the ptable anyway. However, as we found out at the meeting, these two can be removed:

```php
array_unshift($GLOBALS['TL_DCA']['tl_content']['config']['onload_callback'], array('tl_content_news', 'checkPermission'));
$GLOBALS['TL_DCA']['tl_content']['list']['operations']['toggle']['button_callback'] = array('tl_content_news', 'toggleIcon');
```

So the only remaining line is

```php
$GLOBALS['TL_DCA']['tl_content']['config']['onload_callback'][] = array('tl_content_news', 'generateFeed');
```

But I think this can be changed too, so that the `onload_callback` is always loaded, and within it, you simply check whether the `ptable` is `tl_news`.

Overall I would do that in a follow-up PR, if this gets merged.

2020-06-15 14:43 UTC, leofeyer requested changes

2020-06-15 14:43 UTC, leofeyer commented on core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
> +		if (null !== ($do = Input::get('do')))
This should be an early return.

```suggestion
		if (!$do = Input::get('do'))
		{
			return;
		}
```

2020-06-15 14:43 UTC, leofeyer commented on core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
> +				if ($do === $key && isset($module['tables']) && \is_array($module['tables']))
This should be an early return, too.

```suggestion
				if ($do !== $key || !isset($module['tables']) || !\is_array($module['tables']))
				{
					continue;
				}
```

2020-06-18 13:13 UTC, leofeyer reviewed
Looks good. 👍 Can/should we remove `'dynamicPtable' => true,` from the tl_content DCA file?

2020-06-18 14:32 UTC, fritzmg commented
> Can/should we remove `'dynamicPtable' => true,` from the tl_content DCA file?

No, that's still necessary. What's not necessary anymore is doing this in your own bundle:

```php
// src/Resources/contao/dca/tl_content.php
if (\Contao\Input::get('do') == 'foo') {
	$GLOBALS['TL_DCA']['tl_content']['config']['ptable'] = 'tl_foo';
}
```

2020-06-18 14:35 UTC, bytehead approved these changes

2020-06-19 10:55 UTC, ausi approved these changes

2020-06-19 14:16 UTC, leofeyer commented
Ok, then we should remove `$GLOBALS['TL_DCA']['tl_content']['config']['ptable'] = '…';` in the following files, shouldn't we?

* `calendar-bundle/src/Resources/contao/dca/tl_content.php`
* `core-bundle/src/Resources/contao/dca/tl_content.php`
* `news-bundle/src/Resources/contao/dca/tl_content.php`

2020-06-19 14:20 UTC, ausi commented
Wouldn’t that be a BC break then if someone reads from `$GLOBALS['TL_DCA']['tl_content']['config']['ptable']` ?

2020-06-19 14:22 UTC, leofeyer commented
I don't think so, as the value is re-added dynamically, isn't it?

2020-06-20 09:36 UTC, fritzmg commented
> I don't think so, as the value is re-added dynamically, isn't it?

For callbacks, that's true. However, if anyone is relying on `$GLOBALS['TL_DCA']['tl_content']['config']['ptable']` being present in `contao/dca/tl_content.php` of their application or extension, then it would be missing there, since it is of course only added after all DCA files have been loaded.

2020-06-20 09:39 UTC, fritzmg commented
> And then it is still more efficient to directly set the ptable anyway. However, as we found out at the meeting, these two can be removed:
> 
> ```php
> array_unshift($GLOBALS['TL_DCA']['tl_content']['config']['onload_callback'], array('tl_content_news', 'checkPermission'));
> ```

I was wrong about this one. While `tl_content_news::checkPermission` _almost_ identical to `tl_content::checkPermission`, it does have a few adjustments of course.

2020-06-21 13:22 UTC, aschempp approved these changes
I think the feature and implementation is „perfect“. But should we consider setting it in a loadDataContainer hook instead of DC_Table? On the other hand, the value can‘t be present e.g. in the front end anyway 🤔

2020-06-22 14:41 UTC, leofeyer commented
Why not?

2020-06-22 14:48 UTC, fritzmg commented
Hmm... what would be the advantage of having it in the hook instead?

2020-06-24 10:08 UTC, leofeyer approved these changes
This PR is ready to be merged from my point of view. Let's wait for @aschempp to elaborate.

2020-06-25 09:44 UTC, aschempp commented
> > the value can‘t be present e.g. in the front end anyway 🤔
> 
> Why not?

because the `ptable` is based on the current back end module?

2020-06-25 12:38 UTC, leofeyer commented
As briefly discussed in Slack:

> The `onload_callback` will only set the ptable if `new DC_Table()` is run. The hook would set the ptable anywhere when `Controller::loadDataContainer()` is executed.

That is a good point actually. Are we 100% sure that we only need the ptable in the back end? Because I am not…

2020-06-26 13:48 UTC, merged

2020-06-26 13:48 UTC, leofeyer commented
Thank you @fritzmg.

2021-08-19 20:40 UTC, fritzmg commented
For anyone interested: a backport of this functionality is also available now for Contao 4.9: https://packagist.org/packages/inspiredminds/contao-dynamic-ptable-backport