Correctly symlink tcpdf config when using the mono repository
contao/contao pull request #149
Opened 2018-10-30 09:13 UTC by bezin

This PR add adds a check for the monorepository to the SymlinksCommand and uses the correct path to symlink tcpdf config.

2018-10-30 09:22 UTC, fritzmg commented on core-bundle/src/Command/SymlinksCommand.php
> +        }    }
Some minor formatting issue here :)

2018-10-30 09:28 UTC, bezin commented on core-bundle/src/Command/SymlinksCommand.php
> +        }    }
Thanks for the hint, gonna fix this

2018-10-30 09:33 UTC, leofeyer commented
I think the PR should be targeted at the `4.4` branch since it is a bugfix.

2018-10-30 09:39 UTC, bezin commented
I thought about that as well... in 4.4 tcpdf.php is symlinked in the InstallCommand and was then moved to the SymlinksCommand. Should we backport this refactoring to 4.4 then? 

Besides: why is kernel.packages not existing in the tests? 🤔

2018-10-30 09:44 UTC, leofeyer commented
> Should we backport this refactoring to 4.4 then?

No, in this case not. Then it needs to be targeted at the `4.6` branch.

> Besides: why is kernel.packages not existing in the tests?

Because we are using `vendor/composer/installed.json` to get the packages in Contao 4.4.

2018-10-30 13:27 UTC, bezin commented
Ok, so as far as I see it:

1. Target this PR against ```4.5```  (since then the symlinking happens in SymlinkCommand). Changes can than be ported to 4.6
2. Fix in ```4.4``` as well. Do not use ```kernel.packages``` here, but ```vendor\composer\installed.json```

However I still don't get, why ```kernel.packages``` does not exist in the tests? Tests are run against ```master``` and this is the most recent code base, isn't it?

2018-10-30 13:35 UTC, leofeyer commented
> Target this PR against `4.5`

Contao 4.5 has already reached its EOL. It is either `4.4` (LTS version), `4.6` (active version) or `master` (upcoming version).

2018-10-31 17:06 UTC, leofeyer requested changes
The PR needs to be retargeted at the `4.6` branch.

2018-10-31 19:14 UTC, dmolineus commented on core-bundle/src/Command/SymlinksCommand.php
> +        }    }
You could use `kernel.bundles` and get the path of the `ContaoCoreBundle`. So you could get rid of the if statement, couldn't you?

2018-11-03 09:43 UTC, closed without merging

2018-11-03 09:53 UTC, bezin commented
See https://github.com/contao/contao/pull/158

2019-01-07 16:02 UTC, bezin commented
Hello again,

just as I was about to use the mono repo for some 4.4 fixing, I remembered (or was remembered), that this fix is not yet backported to Contao 4.4. Hence, Contao 4.4 cannot be installed from the mono repository.

Quick recap:
 
The issue is the same as discussed here. The location of tcpdf.php config depends on the location of the Contao Core Bundle. We fixed this for Contao 4.6  in #158 

However, in Contao 4.4. the code is a little different: The symlinking of tcpdf.php is done in the InstallCommand rather than in the SymlinksCommand.

The question know is: Should we backport the refactoring from 4.6 to 4.4 or should we fix the issue in 4.4 as the code base is right now?

2019-01-28 12:17 UTC, bezin commented
@contao/developers

2019-01-28 12:19 UTC, bezin commented
@leofeyer @fritzmg @dmolineus

2019-01-29 15:55 UTC, leofeyer commented
> Should we backport the refactoring from 4.6 to 4.4 or should we fix the issue in 4.4 as the code base is right now?

The latter.