Hide the crawler in maintenance mode
contao/contao pull request #1583
Opened 2020-03-27 15:34 UTC by leofeyer

| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1379
| Docs PR or issue | -

2020-03-27 15:35 UTC, aschempp requested changes
aren't we missing an information that crawling is not possible (like mentioned in the issue)?

2020-03-27 15:57 UTC, leofeyer commented
Feel free to provide a fix yourself if you think that this is important. 🙈

2020-06-04 08:32 UTC, aschempp commented
Sorry I didn't really intend to push to your fork, PHPStorm did automatically 🙈 

Here's what it looks like now in the back end:

<img width="692" alt="Bildschirmfoto 2020-06-04 um 10 32 14" src="https://user-images.githubusercontent.com/1073273/83734040-b9051780-a64e-11ea-9137-ff8aaf3ce361.png">

2020-06-04 21:48 UTC, Toflar approved these changes

2020-06-05 07:09 UTC, bytehead approved these changes

2020-06-05 08:58 UTC, aschempp approved these changes

2020-06-09 09:42 UTC, merged