ADD: #87 Feature: News um Meta-Description und Meta-Titel erweitern (SEO)
contao/contao pull request #161
Opened 2018-11-03 21:29 UTC by eS-IT

2018-11-03 21:32 UTC, Toflar reviewed
Two minor comments, excellent work otherwise :)

2018-11-03 21:32 UTC, Toflar commented on news-bundle/src/Resources/contao/classes/News.php
> +        $news = \NewsModel::findOneBy(array('alias=?', 'published=?'), array($this->Input->get('items'), 1));
You can use `\Input::get('items')` here again, or even better, store it in a variable on line 506 :)

2018-11-03 21:32 UTC, Toflar commented on news-bundle/src/Resources/contao/languages/de/tl_news.xlf
> +      <trans-unit id="tl_news.metatitle.0">
You only need to add English, the rest is managed on Transifex :)

2018-11-03 22:00 UTC, Toflar commented on news-bundle/src/Resources/contao/languages/de/tl_news.xlf
> -</xliff>
This file does not need to be adjusted :) (you've deleted the final new line. Our coding style forces to always end a file with a new line :)

2018-11-14 16:26 UTC, leofeyer commented on news-bundle/src/Resources/contao/config/config.php
> +$GLOBALS["TL_HOOKS"]['generatePage'][] = array('News', 'setMetaData');
We already have a listener for the `generatePage` hook three lines above. Wouldn't it make sense to re-use it?

2018-11-14 16:29 UTC, leofeyer commented
Here's what needs to be done IMHO:

- [ ] Re-use the existing listener
- [ ] Rename the fields from `metatitle` to `title` and from `metadescription` to `description`, so they match `tl_page.title` and `tl_page.description`
- [ ] Put the fields into a separate palette analogous to `tl_page`

2018-11-14 17:00 UTC, eS-IT commented
In `tl_page` heißt das Feld `pageTitle`, da das Feld `title` der " Seitenname" ist. Soll es in `tl_news` `title` oder `pageTitle` heißen?

2018-11-14 18:42 UTC, ausi requested changes
IMO `GeneratePageListener::setMetaData()` is missing a check if we are actually on a news page. If I got a calendar event with the same alias as a news entry, wouldn’t this code set the title/description for the news on the event page then?

Shouldn’t the code for setting the title/description instead go into the reader module as we already set the page title there? https://github.com/contao/contao/blob/578044764b17db7cbec78c94d0beae589dc6dbd6/news-bundle/src/Resources/contao/modules/ModuleNewsReader.php#L105

2018-11-15 09:44 UTC, leofeyer commented
> Shouldn’t the code for setting the title/description instead go into the reader module as we already set the page title there?

@ausi You are absolutely right.

2018-11-15 09:55 UTC, leofeyer commented
> In `tl_page` heißt das Feld `pageTitle`, da das Feld `title` der " Seitenname" ist. Soll es in `tl_news` `title` oder `pageTitle` heißen?

Gute Frage. Ich denke `tl_news.pageTitle`, weil das zumindest konsistent wäre.

2018-11-15 12:14 UTC, contaoacademy commented
Vielen herzlichen Dank, dass Ihr das Feature so schnell implementiert.

2018-11-23 14:07 UTC, merged

2018-11-23 14:07 UTC, leofeyer commented
Thank you @eS-IT.