Update comment of FrontendController::checkCookiesAction
contao/contao pull request #1628
Opened 2020-04-02 21:30 UTC by Mynyx

Avoid misunderstandings that the RememberMe cookie is set by ``FrontendController::checkCookiesAction``.

2020-04-05 21:04 UTC, ausi submitted a review, later dismissed

2020-04-07 06:00 UTC, aschempp submitted a review, later dismissed

2020-04-07 06:37 UTC, bytehead submitted a review, later dismissed

2020-05-01 08:09 UTC, leofeyer requested changes

2020-05-01 08:09 UTC, leofeyer commented on core-bundle/src/Controller/FrontendController.php
> +     * is enabled to evaluate the RememberMe cookie and then set the session cookie).
```suggestion
     * the output is cached (used in the core if the "alwaysLoadFromCache"
     * option is enabled to evaluate the RememberMe cookie and then set
     * the session cookie).
```

2020-05-01 13:31 UTC, leofeyer approved these changes

2020-05-01 13:31 UTC, merged

2020-05-01 13:31 UTC, leofeyer commented
Thank you @Mynyx.