Correctly check if search panel is active
contao/contao pull request #1638
Opened 2020-04-07 09:59 UTC by dmolineus

| Q                | A
| -----------------| ---
| Fixed issues     | 
| Docs PR or issue | 

At the moment the search panel is always in an active state if the search panel was used before. The active state is detected by `isset`, but the search is only applied then the value is not empty.

How to reproduce:

1. Use any panel filter (search or filter doesn't matter)
2. Clear the search field
3. The search is still marked as active though it's not used

2020-04-07 16:24 UTC, leofeyer requested changes
> but the search is only applied then the value is not empty.

Then we should use `$active = !empty()` instead of `isset() && != ''`, shouldn't we?

2020-04-08 06:51 UTC, dmolineus commented
> Then we should use $active = !empty() instead of isset() && != '', shouldn't we?

I don't think so, as it has different results.

 ```php
$foo = '0'; 
assert(empty($foo) === ($foo == ''));
 ```

Searching for `0` sounds like a valid case for me and the search would be applied for that case (See 
https://github.com/contao/contao/pull/1638/files#diff-073ea90941450968f22379234bb6dff7L2883), I decided to use the same comparison here instead of `empty`.

2020-04-08 07:55 UTC, leofeyer commented
But when using `!=` instead of `!==`, `0 != ''` will still return `false`: https://3v4l.org/MEjDC

2020-04-08 09:15 UTC, dmolineus commented
> But when using `!=` instead of `!==`, `0` will still return `false`: https://3v4l.org/MEjDC

Not talking about `0` but about `'0'`: https://3v4l.org/7bhcS

2020-04-08 09:25 UTC, leofeyer commented
You are right about `'0'` (see https://3v4l.org/sl574). And can we be sure that `$session['search'][$this->strTable]['value']` is always a string?

2020-04-08 12:50 UTC, dmolineus commented
Afaik `Input::postRaw()` returns a string or null. The value is processes by `ltrim` which always returns a string, so I guess yes, we can assume it's always a string (if defined).

https://github.com/contao/contao/blob/a60bda4d52feba067a9c72975b65706851162a73/core-bundle/src/Resources/contao/drivers/DC_Table.php#L5164

2020-04-08 13:28 UTC, leofeyer approved these changes

2020-05-01 13:31 UTC, merged

2020-05-01 13:31 UTC, leofeyer commented
Thank you @dmolineus.