Fix index deletion
contao/contao pull request #166
Opened 2018-11-03 22:22 UTC by Toflar

See https://github.com/contao/contao/issues/140

2018-11-12 08:20 UTC, leofeyer requested changes
Unfortunately, the fix does not work yet. It will add the `DROP INDEX` command twice, once in the `ALTER_TABLE` section and again in the `ALTER_CHANGE` section, which leads to a `Can't DROP INDEX …; check that it exists` error.

@m-vo discovered that the Doctrine schema manager already sorts the queries to take care of the problem we are trying to fix here, so maybe we should just drop our logic and use the pre-sorted queries?

2018-11-12 08:21 UTC, leofeyer commented on installation-bundle/src/Database/Installer.php
>                      if ('primary' !== $index->getName()) {
This needs to be `strtolower($index->getName())` to fix https://github.com/contao/contao/issues/140#issuecomment-436284620.

2018-11-12 08:58 UTC, leofeyer commented
I have fixed this intermediately in 3d9c5943f6cd933a0aad539d5ffddca7c55981af, however we should definitely review this and use the Doctrine routines if possible IMHO.

2018-11-12 10:21 UTC, m-vo commented
You may want to have a look if #169 also fixes this problem. There I'll just kept the original sorting order - in my use case to allow dropping tables with foreign keys (drop key first, then table) which doctrine already supports.

2018-11-23 12:06 UTC, leofeyer commented
Ok, then I'm closing this in favor of #169.

2018-11-23 12:06 UTC, closed without merging