Prevent brute force in ModuleCloseAccount
contao/contao pull request #1769
Opened 2020-05-27 18:25 UTC by Mynyx

Prevent brute force in ``ModuleCloseAccount`` with ``sleep(2)`` as in ``ModuleChangePassword``.

https://github.com/contao/contao/blob/9c0502bc4b41f5208a3f54e0e07e5d509be2654e/core-bundle/src/Resources/contao/modules/ModuleChangePassword.php#L149-L154

2020-05-27 18:29 UTC, aschempp approved these changes

2020-05-27 20:33 UTC, ausi commented
Please follow our [security policy](https://github.com/contao/contao/security/policy) for security related issues.

2020-05-28 05:58 UTC, bytehead approved these changes

2020-05-28 08:18 UTC, leofeyer requested changes
The protective effect of this is only very marginal and assumes that the number of PHP processes is limited (e.g. on shared hosting servers). And even then, it cannot be considered a real mitigation. Therefore, instead of merging this PR, I suggest we remove the existing lines of code altogether.

2020-05-28 08:50 UTC, m-vo commented
>  I suggest we remove the existing lines of code altogether

I absolutely agree. If the problem is real, there should be other solutions.

Plus: From all working delay/jitter based solutions against brute forcing or timing attacks (information disclosure) I've seen so far, none does execute the mitigation in only one code path.

2020-06-19 13:50 UTC, leofeyer commented
See #1848.

2020-06-19 13:50 UTC, closed without merging