Remove hard dependency on assets.packages
contao/contao pull request #1883
Opened 2020-06-26 18:41 UTC by fritzmg

| Q                | A
| -----------------| ---
| Fixed issues     | N/A
| Docs PR or issue | N/A

`contao.listener.insert_tags.asset` currently has a hard dependency on `assets.packages` - however, that service might not exist in the container. 

```
The service "contao.listener.insert_tags.asset" has a dependency on a non-existent service "assets.packages".
```

For example, if you install `symfony/symfony` (e.g. for development purposes), `framework.assets` will be disabled by default - and then the service will not be registered. Or if you specifically have `framework.assets: false` in your config.

This PR simply makes the dependency in the listener optional and throws a `\RuntimeException` when still used. I also added the same exception to `Template::asset`, to stay consistent.

2020-06-29 07:47 UTC, bytehead submitted a review, later dismissed

2020-06-29 11:14 UTC, aschempp requested changes
as discussed on the phone, we should enable assets in the framework configuration by default

2020-06-29 11:16 UTC, fritzmg commented
As discussed in slack, we want to enable assets via the Manager Bundle, since Contao does in fact have a hard dependency on `assets.packages`.

_Note:_ we need to add

```yml
framework:
    assets: true
```

[here](https://docs.contao.org/dev/getting-started/initial-setup/symfony-application/contao-4.9/#configure-your-contao-installation) too. (/cc @bytehead)

2020-06-29 11:18 UTC, bytehead commented
Fine for me 👍

2020-06-30 06:54 UTC, bytehead approved these changes

2020-06-30 06:59 UTC, aschempp approved these changes
I hope this does not cause any trouble if I configure assets in my local `config.yml`?

2020-06-30 07:03 UTC, bytehead commented
Your local setting probably overrides the one from the manager bundle?

2020-06-30 08:16 UTC, fritzmg commented
Yes, this should not cause any trouble. Even if you only have

```yml
framework:
    assets:
        version_strategy: …
```
it will still be enabled. And
```
framework:
    assets: false
```
disables ist as expected.

2020-06-30 08:54 UTC, merged

2020-06-30 08:54 UTC, leofeyer commented
Thank you @fritzmg.