Improve performance of fuzzy search when having a huge search index
contao/contao pull request #1912
Opened 2020-07-06 12:25 UTC by Toflar

Based on our latest improvements in the search storage (https://github.com/contao/contao/pull/1679), I tried to improve other edge cases.

By storing all word variants (so for e.g. `foobar` we store `foobar`, `oobar`, `obar`, `bar`, `ar` and `r`), we can omit the leading `%` in the wild card and thus, MySQL can use the `term` index to find the matching terms instead of doing a full table scan.

I did some tests with smaller pages compared to huge indexes:

* Small website (~ 70 URLs):
    * Current master:
        * Number of entries in `tl_search_term`: ~ 1,200
        * Searching for `gati` and `e` takes about the same time: 2.8 ms
    * This PR :
        * Number of entries in `tl_search_term`: ~ 4,100
        * Searching for `gati` and `e` takes about the same time: 2.4 ms

* Bigger website (~ 800 URLs):
    * Current master:
        * Number of entries in `tl_search_term`: ~ 27,000
        * Searching for `gati`: 25.13 ms
        * Searching for  `e`: 491.61 ms
    * This PR :
        * Number of entries in `tl_search_term`: ~ 94,000
        * Searching for `gati`: 31.61 ms
        * Searching for  `e`: 305.59 ms

* Even bigger website: (~ 2,000 URLs):
    * Did not bother comparing the results with the current implementation anymore, I only checked the performance of this PR:
    * Number of entries in `tl_search_term`: ~ 127,000
    * Searching for `gati`: 33.63 ms (this is `gati%`), `%gati%` would be  124.45 ms
    * Searching for `e`: 632.63 ms (this is `e%`), `%e%` would be 5.14 s (! not ms)

So in other words, I guess we can conlude the following statements from my tests:

* There's not much difference in performance for smaller sites. The difference is not noticeable at all. This is true for both, the query perfomance as well as the number of entries in `tl_search_term`. We have about 350% more entries.

* The longer the keyword, the better the performance. This is true for both implementations.

* This PR provides a significant improvement for very short keywords like `e` which turns into `%e%` and thus basically matches everything.

* The number of entries in `tl_search_term` relative to the pages index (`tl_search`) is about 3.5 times higher for small pages but that ratio gets better as the index grows because chances that compound words have already been indexed increases.

I find the number of entries in `tl_search_term` is not really relevant. The bigger page I tested (~2,000 entries) current generates 2.6 million entries in 4.9 so I guess the 127,000 terms should not be a big deal ;)

Long story short: This PR improves performance for really big search indexes when searching for short keywords and it has no negative impact on the regular performance. The only "disadvantage" is an increased number of terms in the database which is still an order of magnitude lower than what we've been working with for years.

2020-07-06 12:35 UTC, aschempp requested changes
The idea is great, however, I can't configure whether to find fuzzy words or not anymore. The search is always fuzzy with this.

2020-07-06 12:39 UTC, Toflar commented
True, we'd need to store the regular words in `tl_search_terms` and the fuzzy variants in `tl_search_terms_fuzzy` or whatever. Wdyt, @ausi?

2020-07-06 13:28 UTC, ausi commented
I think the problem is not that searching for `%e%` is slow. This takes about 7ms with my test data while `e%` takes about 4ms.

The problem is that `%e%` returns a very large set of rows that gets then merged with the very, very large `tl_search_index` table.

To improve fuzzy search we should create an optimized index for one- two- and three-letter wildcards that only correspond to a single `tl_search_index` row. This would result in about 10,000 rows after the JOIN for `%e%` instead of 1,662,000 rows. This would make searching for `%e%` basically as fast as searching for `%e%`.

But I’m not sure how far we want to go with the “old” search implementation.

2020-07-07 07:30 UTC, Toflar commented
After further discussions with @ausi I'm going to close this because it's not the right approach. The problem isn't really searching the terms, it's the fact that there's too many joins to make after that. This can only be fixed by adding stemming and decomposition to the search indexing process so we don't even need wildcard search anymore.
But this will be for another day.

2020-07-07 07:30 UTC, closed without merging