Provide migration for folderUrl setting
contao/contao pull request #1987
Opened 2020-07-24 17:06 UTC by fritzmg

| Q                | A
| -----------------| ---
| Fixed issues     | -
| Docs PR or issue | -

When upgrading a Contao 4.9 instance to 4.10 I noticed that the `folderUrl` setting wasn't migrated to the `tl_page` settings.

_Note:_ I need some help with the unit tests, as I am not sure how to properly mock the `Config` singleton, which also has static methods.

2020-07-24 17:10 UTC, m-vo commented
> Note: I need some help with the unit tests, as I am not sure how to properly mock the Config singleton, which also has static methods.

What do you need exactly? Maybe you can solve it with `$this->mockClassWithProperties(Config::class, [...]);`

2020-07-24 17:16 UTC, fritzmg commented
> What do you need exactly? Maybe you can solve it with `$this->mockClassWithProperties(Config::class, [...]);`

Well the static function is not a property. I want to do 

```php
$config = $this->createMock(Config::class);
$config
    ->expects($this->once())
    ->method('has')
    ->with('folderUrl')
    ->willReturn(false)
;
``` 

But this will fail:

```
1) Contao\CoreBundle\Tests\Migration\Version409\FolderUrlMigrationTest::testDoesNothingIfFolderUrlNotEnabled
Static method "has" cannot be invoked on mock object
```

2020-07-24 19:29 UTC, aschempp requested changes
I don't think this will work. If `folderUrl` is disable in the root pages, the migration will always run again. The correct migration would be to check if the field exists in the database, and only migrate if it does not. That obviously won't fix current RCs, but we don't provide such fixes for RCs.

2020-07-24 20:30 UTC, fritzmg commented
> I don't think this will work. If `folderUrl` is disable in the root pages, the migration will always run again.

Only if you re-add the setting in your `localconfig.php` or don't remove `contao.localconfig.folderUrl = true` from your `config.yml`.

2020-07-24 20:59 UTC, aschempp commented
It could even be added to the `RoutingMigration` in my view 😊

2020-07-25 09:20 UTC, fritzmg commented
Alright, I have integrated it into the `RoutingMigration` now. Which caused me to notice, that the `RoutingMigration` wasn't actually registered as a service and thus would have never been executed in the first place 🙈 

(also, there are no tests what so ever for any 410 migration 😶)

2020-07-25 21:58 UTC, leofeyer commented on core-bundle/src/Migration/Version410/RoutingMigration.php
> +    public function __construct(Connection $connection, ContaoFramework $framework, string $urlSuffix = '.html', bool $prependLocale = false)
You also have to adjust the `RoutingMigrationTest` class (see the CI chain).

2020-07-26 07:32 UTC, fritzmg commented
Right, forgot about the functional tests. Updated.

2020-07-26 10:55 UTC, aschempp approved these changes

2020-07-26 14:26 UTC, merged

2020-07-26 14:26 UTC, leofeyer commented
Thank you @fritzmg.