Call rgxp callback in BackendPassword controller
contao/contao pull request #2190
Opened 2020-08-24 16:17 UTC by richardhj

| Q                | A
| -----------------| ---
| Fixed issues     | Fixes terminal42/contao-password-validation#3
| Docs PR or issue | 

The `BackendPassword` controller implements its own form validation.
Usually, we would do a `$objWidget = new Password();` and call `$objWidget->validate()` to have all form validation done, but this is not the case in the `BackendPassword` controller.

In this case, the BackendPassword controller lacks the `rgxp` check, which validates the value if a custom rgxp is set on the password field.
This results in an issue in our "terminal42/contao-password-validation" extension that validates the password.

I don't know, why the `BackendPassword` controller is not using the Widget to build and validate the form, but there might be a reason. I decided to check for registered rgxp hooks.

## Thoughts
- [ ] In the back end scope, you usually can throw \Exceptions in the save_callback to add an error to the widget. This will not work in the current implementation. Do we need to change this as well to be consistent?
- [ ] Do we rather need to change the whole implementation, e.g. populate  a `$objWidget = new Password();`? 

cc @aschempp

2020-08-26 06:19 UTC, leofeyer requested changes

2020-08-26 06:19 UTC, leofeyer commented on core-bundle/src/Resources/contao/controllers/BackendPassword.php
> +
I would prefer to keep this code in the `elseif` and `else` condition, even though this means duplicating it. Loading a DCA and instantiating a new DC object are expensive operations that are not necessary for the `if` condition.

2020-08-26 06:21 UTC, leofeyer commented
> Do we rather need to change the whole implementation, e.g. populate  a `$objWidget = new Password();`?

Yes, I think so.

2020-08-26 06:26 UTC, aschempp commented
I think so too. Maybe the profile tab/module might give us a hint on how to implement that. As far as I remember, thats some special backend view as well.

2020-10-05 07:23 UTC, aschempp commented
@richardhj can you take care of this?

2020-12-16 15:56 UTC, leofeyer commented
@richardhj Since Contao 4.4 is now in the "security updates only" phase of the LTS cycle, please rebase this PR on the `4.9` branch.

2021-02-18 07:57 UTC, aschempp commented
/ping @richardhj

2021-04-27 22:55 UTC, closed without merging

2022-09-23 08:47 UTC, AlexanderWillner commented
Would you merge it if I rebase it for 4.13?