Always use absolute paths
contao/contao pull request #2262
Opened 2020-09-09 07:33 UTC by aschempp

| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2171

In Contao 4.10, we switched to using the current page model in routing. If a page's host does not match the current host, Symfony automatically adds the host name by using `NETWORK_PATH` (see https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L264-L269).

Our current attempt at making paths relative breaks the `NETWORK_PATH`, and I don't think it's necessary. I know we used to need that for some browser quirks regarding the base tag, but according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) the base tag should only be applied _for all relative URLs in a document_.

I think we should adhere to the Symfony standard and always use absolute paths (or absolute URLs).

2020-09-09 07:34 UTC, Toflar approved these changes

2020-09-09 07:39 UTC, leofeyer requested changes
The fix is wrong. The code is required to make relative paths compatible with the base URL:

* Base URL: `https://domain.com/path/`
* Generated path: `/news.html`
* Translates to: `https://domain.com/news.html` <-- `/path` is missing!

Instead, we should make sure not to apply `substr()` to network paths beginning with `//`.

2020-09-09 07:41 UTC, aschempp commented
I don't think so. The generated path includes `/path/`, thats why we currently strip `Environment::get('path')`.

2020-09-09 07:53 UTC, leofeyer commented
Independent of this, using a network path (aka protocol-relative URL) even if there is a given scheme seems wrong to me. I would expect the Symfony UrlGenerator to generate an absolute URL if I provide host and scheme.

2020-09-09 14:01 UTC, leofeyer commented
https://github.com/symfony/symfony/issues/38130

2020-09-10 09:14 UTC, leofeyer commented
Since Symfony most likely will not change the behavior of the UrlGenerator, we have to decide how to proceed here. Shall we handle the network path case and prepend the protocol or do we go with protocol-relative URLs?

2020-09-10 09:21 UTC, leofeyer commented
FYI, I have applied the changes from this PR to contao.org and indeed everything seems to work fine.

2020-09-10 10:08 UTC, aschempp commented
I think this PR should fix everything just fine. Relying on `ABSOLUTE_URL` shouldn't be necessary, we can just stick with the Symfony default (`ABSOLUTE_PATH`).

2020-09-10 10:11 UTC, ausi commented
I don’t like changing the URL behavior in a bug fix release. I think we should handle the `//` case and keep the existing logic for 4.10.

2020-09-10 10:32 UTC, leofeyer commented
Since the previous behavior is broken in Contao 4.10, it is ok to change this in a bugfix release IMHO.

2020-09-10 11:33 UTC, aschempp commented
4.10 changes routing in a lot of ways, I would say this change can be seen as related to that 🙃

2020-09-10 12:53 UTC, ausi commented
All versions from 4.0.0 until 4.10.0 returned a URL relative to the base URL in `getFrontendUrl()` (and basically in every other place Contao handles URLs). I don’t like changing that in 4.10.1.

As noted in https://github.com/contao/contao/issues/2254#issuecomment-690131311 I think we should discuss the URL concept in general before changing it in some places in bugfix releases of different minor versions.

2020-09-10 13:13 UTC, leofeyer commented
Alternative PR here: #2279

2020-09-10 13:20 UTC, leofeyer commented
If we really decide not to change this in Contao 4.10, I would like to rebase this PR onto the `master` branch so we can make the change in Contao 4.11.

2020-09-22 08:58 UTC, leofeyer commented
Now fixed in #2323.

2020-09-22 08:58 UTC, closed without merging