Do not allow registering a Model with an empty primary key
contao/contao pull request #230
Opened 2018-12-12 11:24 UTC by gmpf

Consider the following:
```
$model = new Contao\PageModel();
$model->title = 'Foo';
$model->attach();
```
This works once per table (in this example, `tl_page`), because `Contao\Model\Registry::arrRegistry` then has one key for that table that is `""` (empty string):
```
array(13) {
  // …
  ["tl_page"]=>
  array(58) {
    [1]=>
    object(Contao\PageModel)#641 (6) { /* … */ }
    [4]=>
    object(Contao\PageModel)#768 (6) { /* … */ }
    // …
    [""]=>
    object(Contao\PageModel)#2094 (6) { /* Our Model */ }
  }
  // …
}
```
Once we do the same thing again:
```
$model2 = new Contao\PageModel();
$model2->title = 'Bar';
$model2->attach();
```
we suddenly get an exception:
> The registry already contains an instance for tl_page::id()

Obviously, this is not the expected behavior. The Registry should either categorically allow registering a model without a primary key or categorically not allow it. This fix implements the latter. It does not use `empty()` because that would overshoot and prevent the primary key from being `0` or `"0"`, which may not be recommendable, but does not have to be forbidden in this context.

2018-12-13 18:43 UTC, gmpf commented
Note: The Travis check failed initially because, in the "Test installing the split repos" job, Composer ran into an out-of-memory error:
https://travis-ci.com/contao/contao/jobs/164602245#L950-L958
So I did
```
git remote add contao https://github.com/contao/contao.git
git pull contao 4.4 --rebase
```
to update my local repo and
```
git push -f
```
to my fork so that the checks would rerun for this PR. And it happened again:
https://travis-ci.com/contao/contao/jobs/165007773#L948-L956

I guess it's better to not try this again. :D

2018-12-14 06:57 UTC, fritzmg commented
Yeah, it's the typical 1536M memory_limit problem. The travis environment needs to set its memory_limit to -1.

2018-12-19 08:42 UTC, leofeyer commented
> prevent the primary key from being `0` or `"0"`, which may not be recommendable, but does not have to be forbidden in this context

Why not? `0` is not a valid primary key IMHO.

2018-12-19 15:13 UTC, gmpf commented
> Why not? `0` is not a valid primary key IMHO.

Because of this:

> does not have to be forbidden *in this context*

What I mean by that is that this fix relates to not allowing a model to be registered without a set PK value. It's two different issues. If you do this
```
$model0 = new Contao\FooModel();
$model0->id = 0;
$model0->attach();
```
that may be odd, but it does not cause any problems within the Registry (the key in `Contao\Model\Registry::arrRegistry` becomes `0`, not `""`, in this case).

IMHO, the Registry should not care about what the database allows, only about things working correctly within itself.

I do agree with this though:
> `0` is not a valid primary key IMHO.

At the moment, we can do something like this, which shouldn't be allowed:
```
$model0 = new Contao\FooModel();
$model0->id = 0;
$model0->save();
```
The moment this becomes a problem is `$model0->save();`.
I have expanded and renamed this PR accordingly.

2018-12-19 15:37 UTC, fritzmg commented
Why do you want to attach manually created models to the registry? It wouldn't be able to be retrieve them from the registry anyway, would they?

2018-12-19 17:39 UTC, gmpf commented
> Why do you want to attach manually created models to the registry?

I do not want to do anything, the code snippets in this thread are just short demonstrations for what I'm talking about. :D

The point is that things shouldn't implicitly happen if they are not valid:

1. It shouldn't be possible to register a Model without a PK value once per table, without any feedback that this is not actually supported.

2. It shouldn't be possible to save a model that has a PK value of `0` because as of now, the data set would get saved to the database, but not with PK value `0`, without any feedback that it does not happen that way (obviously assuming one has not set `sql_mode='NO_AUTO_VALUE_ON_ZERO'`, in which case one would probably have some more problems than just this :D).

This is not something I personally need for any particular purpose, it is just helpful, when you do something wrong, to then get some feedback telling you that you did something wrong, especially when the alternative is something unintended happening implicitly.

[OT]
> It wouldn't be possible to be retrieve them from the registry anyway, would they?

You could do this:
```
$model = new FooModel();
$model->id = 23;
$model->attach();
// ...
$modelAgain = Registry::getInstance()->fetch(FooModel::getTable(), 23);
```
But you would have to know the ID at every point.

And, of course, a funny thing you can do, as of right now, is this:
```
$model = new FooModel();
$model->attach();
// ...
$modelAgain = Registry::getInstance()->fetch(FooModel::getTable(), '');
```
but, as pointed out, only once per table. ;P
[/OT]

2018-12-21 15:21 UTC, leofeyer commented
@contao/developers IMHO it should not be possible to save a model with ID 0 nor attach it to the registry. WDYT?

2019-01-17 15:23 UTC, leofeyer commented
As discussed in Mumble on January 17th, we want to throw an exception if the primary key is `null` (meaning "not set") but we do want to allow `0` as primary key.

2019-01-17 15:24 UTC, leofeyer commented on core-bundle/src/Resources/contao/library/Contao/Model/Registry.php
> +		if ($varPk === null || $varPk === '')
`$varPk === ''` needs to be removed.

2019-01-17 15:25 UTC, leofeyer requested changes
Please revert the changes in the `Model` class.

2019-01-22 10:00 UTC, merged

2019-01-22 10:00 UTC, leofeyer commented
Thank you @gmpf.