Remove the Google web fonts field from the page layout
contao/contao pull request #2431
Opened 2020-10-15 10:46 UTC by leofeyer

| Q                | A
| -----------------| ---
| Implemented feature     | #1791
| Docs PR or issue | -

2020-10-15 10:49 UTC, fritzmg approved these changes, later dismissed

2020-10-15 11:00 UTC, m-vo requested changes

2020-10-15 11:00 UTC, m-vo commented on core-bundle/src/Migration/Version411/MergeWebfontsMigration.php
> +        ");
```suggestion
        $rows = $this->connection->fetchAllAssociative("SELECT id, webfonts, head FROM tl_layout WHERE webfonts != ''");
```

2020-10-15 11:00 UTC, m-vo commented on core-bundle/src/Migration/Version411/MergeWebfontsMigration.php
> +        $this->connection->executeStatement("ALTER TABLE tl_layout DROP $webfontsFieldQuoted");
```suggestion
        $this->connection->executeStatement('ALTER TABLE tl_layout DROP webfonts');
```

2020-10-15 11:03 UTC, leofeyer commented on core-bundle/src/Migration/Version411/MergeWebfontsMigration.php
> +        ");
Not sure about this. I took the code from @ausi's migration:

https://github.com/contao/contao/blob/b0f4b53f4e869d63af16323aa24a4d1bd6adc421/core-bundle/src/Migration/Version410/OrderFieldMigration.php#L98-L112

2020-10-15 11:07 UTC, m-vo commented on core-bundle/src/Migration/Version411/MergeWebfontsMigration.php
> +        ");
Mh, I don't like this added complexity - this also breaks SQL validation in PhpStorm.

If you still want to go down this route, there is a leftover `tl_layout` in the last query. :stuck_out_tongue:

2020-10-15 11:08 UTC, m-vo commented on core-bundle/src/Migration/Version411/MergeWebfontsMigration.php
> +                ->prepare("UPDATE $tableQuoted SET $headFieldQuoted = :head WHERE id = :id")
Might even want to change this to `$this->connection->update(...)`.

2020-10-15 11:11 UTC, m-vo commented on core-bundle/src/Migration/Version411/MergeWebfontsMigration.php
> +            ;
```suggestion
            $head = $row['head']."\n".'<link rel="stylesheet" href="https://fonts.googleapis.com/css?family='.str_replace('|', '%7C', $row['webfonts']).'">';

            $this->connection->update('tl_layout', ['head' => $head], ['id' => $row['id']]);
```

2020-10-15 13:25 UTC, ausi commented on core-bundle/src/Migration/Version411/MergeWebfontsMigration.php
> +        ");
`quoteIdentifier()` is only needed when the identifier is dynamic. For static identifiers like in this case we normaly write them directly into the query as suggested by @m-vo

2020-10-15 14:39 UTC, leofeyer commented on core-bundle/src/Migration/Version411/MergeWebfontsMigration.php
> +        ");
Changed in 7e3c42d2bc2592001430c275161e5fe5e3b75bd6.

2020-10-15 14:40 UTC, leofeyer commented on core-bundle/src/Migration/Version411/MergeWebfontsMigration.php
> +        $this->connection->executeStatement("ALTER TABLE tl_layout DROP $webfontsFieldQuoted");
Changed in 7e3c42d2bc2592001430c275161e5fe5e3b75bd6.

2020-10-15 20:35 UTC, aschempp approved these changes
I would check if there's any layout with fonts in `shouldRun` but otherwise looks good

2020-10-16 06:48 UTC, leofeyer commented
The migration needs to run even if there are no layouts with web fonts, because it will remove the database column and thus prevent itself from running multiple times.

2020-10-16 06:49 UTC, merged

2020-10-16 06:56 UTC, aschempp commented
> The migration needs to run even if there are no layouts with web fonts, because it will remove the database column and thus prevent itself from running multiple times.

well if there's no field with data, it does not need to run, and it wouldn't run again because there's still no field with data 😉

2020-10-16 07:27 UTC, frontendschlampe commented
I think, to migrate the field isn't a good idea. I would give a hint to anybody, that the field will be deleted in Contao 4.11 and the webmaster should add the fonts again (or change it before update). If you update from 4.10 to 4.11, you have to do and check much more than just pressing the update button anyway. Maybe a hint on homescreen in the backend ...

2020-10-20 06:48 UTC, aschempp commented
@frontendschlampe not sure what you're referring to. Migrations are there to make sure people can upgrade without breaking their sites. You're suggesting we should break their site, which makes no sense except something like an "opinion" they _should_ switch to local fonts…

2020-10-20 08:29 UTC, frontendschlampe commented
First of all: we don't break any installation because of a webfont. Then it's an update which will surely require more adjustments than just pressing the update button in the Manager. In addition, third party extensions that might do something with the web fonts will get function problems because the field is no longer available or the desired function of the extension is no longer available - and this without any message. Not to mention the recommendation for local integration of web fonts.

But it's just my opinion. We have lot of other things to do, so you don't have to worry about copying web fonts. It's everytime the same discussion: should we migrate or not.

2020-10-20 08:33 UTC, m-vo commented
>  Then it's an update which will surely require more adjustments than just pressing the update button in the Manager

I don't think so. After running the migrations you should be fine. Where are you seeing problems?

2020-10-20 08:37 UTC, frontendschlampe commented
> I don't think so. After running the migrations you should be fine. Where are you seeing problems?

We talk about 4.11 ... I don't know. We will see ...

> We have lot of other things to do

This sentence does not refer to an update, but to the load on the core team. ;-)