hide manager link in back end
contao/contao pull request #2508
Opened 2020-11-19 16:13 UTC by MDevster

## feature

# Question
Is there a parameter for the config to hide the back end link for the manager?

# Solution
Now you can set manager_path to false in parameters.yml and the link will not be added.

```
parameters:
    contao_manager:
        manager_path: false

```

Note: The test should be viewed again by someone who is familiar with it ;)

2020-11-20 07:41 UTC, baumannsven commented
I think this must configure in the configuration for the contao manager bundle.

```yaml
contao_manager:
    manager_path: 'Enter a path where contao.manager.pahr.php does not exist.'
```

With this configuration is this pull request obsolete.

2020-11-20 07:51 UTC, baumannsven commented
https://github.com/contao/contao/blob/4cfc0ef8b3d69c28c14bfa50abc47d9780509190/manager-bundle/src/DependencyInjection/Compiler/ContaoManagerPass.php#L29

In the compiler pass the manager_path should be set to false, be allowed.

2021-01-02 09:16 UTC, aschempp requested changes
I think @baumannsven is right, this would keep the default path and not remove the back end link.

2021-01-14 16:50 UTC, leofeyer commented
Does the following not work?

```yaml
parameters:
    contao_manager:
        manager_path: ~
```

2021-01-18 05:45 UTC, aschempp commented
`null` is the default value, so Contao would check if the file exists and display a link.

2021-04-08 15:50 UTC, leofeyer commented
@MDevster Do you know that you can rename the `contao-manager.phar.php` file (e.g. to `cm.phar.php`), which will make the link disappear?

We have discussed the issue in Mumble on April 8th. If we decide to merge the PR, we will have to use a real boolean `false` instead of `'false'`. Also, the validation of the path should be in the `Configuration.php` file instead of the pass.

2021-06-14 21:27 UTC, closed without merging