Ensure language files are loaded when adding default labels
contao/contao pull request #2536
Opened 2020-12-02 17:34 UTC by fritzmg

| Q                | A
| -----------------| ---
| Fixed issues     | -
| Docs PR or issue | -

In Contao 4.9 you do not have to provide a dedicated `label` key for each field of your data container in the data container array, as `DcaLoader::loadDcaFiles` will automatically add the labels from `$GLOBALS['TL_LANG']` when present.

However, this will fail if `Controller::loadDataContainer` or `DcaLoader::load` is executed for a DCA _before_ its language files have been loaded. Thus `DcaLoader::addDefaultLabels` also needs to ensure that the language files have already been loaded.

This might happen in unexpected circumstances. Suppose you have a `tl_foo` DCA with a `FooModel`. If you now execute the following somewhere:

```
$fooModel = new FooModel();

System::loadLanguageFile('tl_foo');
Controller::loadDataContainer('tl_foo');
```
then the labels within `$GLOBALS['TL_DCA']['tl_foo']['fields']` will be empty, because `\Contao\Model::__construct()` already loads the DCA of `tl_foo`, but before the language files of `tl_foo` have been loaded in this case.

2020-12-02 21:28 UTC, ausi approved these changes

2020-12-03 07:25 UTC, leofeyer requested changes
This is wrong, because it is not the responsibility of the DcaLoader to load language files. Also, we must not enforce loading the language files, because there are use cases in which we do not want to load them (e.g. in the DcaExtractor).

IMHO, the "correct" fix is to call `addDefaultLabels()` in line 71 so it is executed even if the DCA has been loaded before. The method will return early once the labels have been added.

2020-12-03 09:00 UTC, aschempp requested changes
Imho the correct fix would be to not check if a label exists (https://github.com/contao/contao/pull/2536/files#diff-4600f89ff1d6f53ddc624cc0976a50e991196ebbad78e52aa3f6837af02f13aeR172). Thats the same a DCA does, it links to the language array by reference, so the labels are also assigned when loaded later.

2020-12-03 09:26 UTC, fritzmg commented
@leofeyer hm, yeah so this is a bug that was introduced with https://github.com/contao/contao/pull/2200, but moving it back to its old place would reintroduce that bug.

@aschempp you mean in addition to moving it back to line #71? That alone won't work (see #2200).

2020-12-03 16:50 UTC, leofeyer commented
Ok, so we have to figure out the correct solution. But this premise remains:

> it is not the responsibility of the DcaLoader to load language files. Also, we must not enforce loading the language files, because there are use cases in which we do not want to load them (e.g. in the DcaExtractor).

2020-12-04 13:32 UTC, aschempp commented
https://github.com/contao/contao/pull/2540 here's my suggestion. Maybe this makes it clearer.

2020-12-04 14:31 UTC, fritzmg commented
> But this premise remains:
> 
> > it is not the responsibility of the DcaLoader to load language files. Also, we must not enforce loading the language files, because there are use cases in which we do not want to load them (e.g. in the DcaExtractor).

Thinking about it, I am not sure if we can do that actually? I mean the `addDefaultLabels` method adjusts the DCA according to data within `$GLOBALS['TL_LANG']`.

2020-12-08 12:59 UTC, leofeyer commented
See #2540.

2020-12-10 13:04 UTC, ausi commented
@fritzmg regarding your example from https://github.com/contao/contao/pull/2540#issuecomment-740709228 : you must not use references in your language file, then everything should work fine.

https://3v4l.org/QBXrr shows why this doesn’t work with references.

2020-12-10 13:17 UTC, fritzmg commented
@ausi but this has been working before and I have seen such references in other extensions as well. These might break then under certain circumstances as well, presumably.

2020-12-10 13:25 UTC, ausi commented
> but this has been working before

As far as I understand references in PHP, this could have never worked if the DCA was loaded before your language file.

I think we either have to define that using references in language files is wrong or otherwise we would have to make sure that the language files are always loaded before the DCA (but this would make using references in the DCA labels useless).

2020-12-10 13:36 UTC, fritzmg commented
> I think we either have to define that using references in language files is wrong or otherwise we would have to make sure that the language files are always loaded before the DCA.

Agreed. I am actually fine with saying that using `&$GLOBALS['TL_LANG']` within language files themselves is not really supported. After all, if you use XLF or YAML, you wouldn't be able to do that anyway. However, it is pretty convenient to not have to translate everything and rather rely on existing translations instead.

> (but this would make using references in the DCA labels useless)

Why would that be the case? If `$GLOBALS['TL_LANG']` is filled before the DCA, then refrences to TL_LANG or within TL_LANG should always work? After all TL_DCA references TL_LANG, but never the other way around.

2020-12-10 13:48 UTC, ausi commented
> However, it is pretty convenient to not have to translate everything and rather rely on existing translations instead.

This still works by copying assigning the value without a reference from the other language file:

```php
\Contao\System::loadLanguageFile('tl_member');
$GLOBALS['TL_LANG']['tl_foo']['firstname'] = $GLOBALS['TL_LANG']['tl_member']['firstname'];
```

> > (but this would make using references in the DCA labels useless)
> 
> Why would that be the case?

If *language files are always loaded before the DCA* then *after loading the DCA $GLOBALS['TL_LANG'] will not change* and so there is no need in the DCA to use a reference.

> Agreed. I am actually fine with saying that using `&$GLOBALS['TL_LANG']` within language files themselves is not really supported.

👍 We can close this issue then I think. Or should we document this somewhere?

2020-12-11 09:58 UTC, closed without merging