Fix the execution order of DCA callbacks registered via annotations or service tags
contao/contao pull request #2538
Opened 2020-12-03 09:52 UTC by qzminski

Up until now the priority of DCA callbacks registered via annotations or service tags was irrelevant:

```
tl_page => [
    list.operations.articles.button_callback => [
        0 => […],
        16 => […],
        -16 => […],
    ],    
],
```

This PR should fix it and put in correct order:

```
tl_page => [
    list.operations.articles.button_callback => [
        16 => […],
        0 => […],
        -16 => […],
    ],    
],
```

[According to the documentation](https://docs.contao.org/dev/framework/dca/#using-service-tagging) the callback with highest priority should be executed first.

2020-12-03 09:56 UTC, bytehead approved these changes

2020-12-03 13:47 UTC, richardhj approved these changes

2020-12-03 15:29 UTC, aschempp requested changes
They are sorted in https://github.com/contao/contao/blob/master/core-bundle/src/EventListener/DataContainerCallbackListener.php#L90 because they are merged with existing items.

2020-12-04 09:15 UTC, qzminski commented
@aschempp you are actually right, and now I am no longer able to reproduce the problem with overriding a singleton button callback. Must have been some mistake on my side then.

Please consider this PR as irrelevant then.

2020-12-04 09:15 UTC, closed without merging