Support native transport and other mailer transport options
contao/contao pull request #2554
Opened 2020-12-10 00:39 UTC by fritzmg

| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2164
| Docs PR or issue | -

This PR adds support for the `native://default` mailer transport, which uses the PHP `sendmail_path` configuration. Some notes:

* This feature is available in Symfony `5.2.0` and up. Since the `symfony/mailer` dependency is independent from other Symfony packages, it can be allowed to be installed, while everything else stays at Symfony `4.4.*`.
* Since the actual transport factory for the native transport is however defined by the `symfony/framework-bundle`, an additional compiler pass is necessary, to add said transport factory to the container, if supported and not already present.
* Changing the `symfony/mailer` dependency to include `5.2.*` also allows you to use [additional options](https://github.com/symfony/symfony/pull/37432) for your transport (like a local domain for an SMTP relay or a custom sendmail command).

It would be important to include this in the upcoming Contao 4.11 version, as otherwise there exists no possibility of using a custom sendmail command and thus you are stuck with the hardcoded one.

2020-12-10 12:51 UTC, ausi commented on core-bundle/src/DependencyInjection/Compiler/AddNativeTransportFactoryPass.php
> +        return version_compare(PackageUtil::getNormalizedVersion('symfony/mailer'), '5.2.0', '>=');
I think it would be better to use `class_exists(NativeTransportFactory::class)` here.

2020-12-10 13:17 UTC, ausi approved these changes, later dismissed

2020-12-15 09:29 UTC, aschempp submitted a review, later dismissed

2020-12-15 09:35 UTC, Toflar approved these changes, later dismissed

2021-01-06 16:38 UTC, leofeyer requested changes

2021-01-06 16:38 UTC, leofeyer commented on composer.json
> +            "require": "4.4.* || 5.2.*"
```suggestion
            "require": "4.4.* || ^5.2"
```

This will also allow Symfony packages that are no direct requirements in version 5.3.

2021-01-06 16:38 UTC, leofeyer commented on core-bundle/composer.json
> +            "require": "4.4.* || 5.2.*"
```suggestion
            "require": "4.4.* || ^5.2"
```

2021-01-06 16:38 UTC, leofeyer commented on core-bundle/src/DependencyInjection/Compiler/AddNativeTransportFactoryPass.php
> +        if ($container->hasDefinition('mailer.transport_factory.native') || !$this->supportsNativeMailer()) {
What is the advantage of encapsulating a single `class_exists()` call in a separate method? It is never re-used IIRC.

2021-01-06 16:38 UTC, leofeyer commented on manager-bundle/composer.json
> +            "require": "4.4.* || 5.2.*"
```suggestion
            "require": "4.4.* || ^5.2"
```

2021-01-07 11:18 UTC, leofeyer approved these changes

2021-01-07 11:32 UTC, merged

2021-01-07 11:32 UTC, leofeyer commented
Thank you @fritzmg.