Correctly validat min and max value in text field
contao/contao pull request #2609
Opened 2020-12-29 15:52 UTC by aschempp

Without the config value, the input is not validated on the server (e.g. if browser side validation is disabled): https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Widget.php#L840

2020-12-29 16:14 UTC, fritzmg requested changes
That should not be necessary. Accessing `$this->minval`/`$this->maxval` will load the value either from `$this->arrAttributes` or `$this->arrConfiguration`:

https://github.com/contao/contao/blob/0e7bb7ab60634f1266c92bbccb643e098e98acf4/core-bundle/src/Resources/contao/library/Contao/Widget.php#L411-L421

2020-12-29 16:15 UTC, aschempp commented
you're right, but it refers to `minval` but we're only setting `min` (and max accordingly)

2020-12-29 16:15 UTC, fritzmg commented
Oh yeah, you are right. But may be we should instead normalize this in `__get`?

2021-01-08 15:32 UTC, leofeyer requested changes
<img width="710" alt="" src="https://user-images.githubusercontent.com/1192057/104032923-22de3480-51cf-11eb-92f4-005ec906cde1.png">

2021-01-09 12:52 UTC, fritzmg submitted a review, later dismissed

2021-01-11 10:19 UTC, leofeyer approved these changes

2021-01-11 10:19 UTC, merged