Mention removal of MediaElement.js
contao/contao pull request #2713
Opened 2021-02-03 14:55 UTC by fritzmg

2021-02-03 14:58 UTC, bytehead submitted a review, later dismissed

2021-03-25 10:52 UTC, leofeyer requested changes
Please move your chapter into the "Version 4.* to 4.8" section.

2021-04-29 12:29 UTC, fritzmg commented
> Please move your chapter into the "Version 4.* to 4.8" section.

Done

2021-05-10 13:38 UTC, aschempp approved these changes, later dismissed

2021-05-13 10:03 UTC, leofeyer approved these changes

2021-05-13 10:03 UTC, leofeyer commented
Thank you @fritzmg.

2021-05-13 10:03 UTC, merged