Fix type casting for FigureBuilder
contao/contao pull request #2782
Opened 2021-02-21 17:05 UTC by richardhj

| Q                | A
| -----------------| ---
| Fixed issues     | 
| Docs PR or issue | 

Fixes the following error:

> TypeError:
Argument 1 passed to Contao\CoreBundle\Image\Studio\FigureBuilder::enableLightbox() must be of the type bool, null given, called in /Users/richard/Sites/studyw***/vendor/contao/news-bundle/src/Resources/contao/modules/ModuleNews.php on line 192
  at vendor/contao/core-bundle/src/Image/Studio/FigureBuilder.php:463
  at Contao\CoreBundle\Image\Studio\FigureBuilder->enableLightbox(null)
     (vendor/contao/news-bundle/src/Resources/contao/modules/ModuleNews.php:192)
  at Contao\ModuleNews->parseArticle(object(NewsModel), false, ' odd', 2)
     (vendor/contao/news-bundle/src/Resources/contao/modules/ModuleNews.php:272)
  at Contao\ModuleNews->parseArticles(object(Collection))
     (vendor/contao/news-bundle/src/Resources/contao/modules/ModuleNewsList.php:160)
  at Contao\ModuleNewsList->compile()
     (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:214)
  at Contao\Module->generate()
     (vendor/contao/news-bundle/src/Resources/contao/modules/ModuleNewsList.php:76)
  at Contao\ModuleNewsList->generate()
     (vendor/codefog/contao-news_categories/src/FrontendModule/NewsListModule.php:42)
  at Codefog\NewsCategoriesBundle\FrontendModule\NewsListModule->generate()
     (vendor/contao/core-bundle/src/Resources/contao/elements/ContentModule.php:75)
  at Contao\ContentModule->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:557)
  at Contao\Controller::getContentElement(object(ContentModel), 'main')
     (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php:192)
  at Contao\ModuleArticle->compile()
     (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:214)
  at Contao\Module->generate()
     (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php:71)
  at Contao\ModuleArticle->generate(false)
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:497)
  at Contao\Controller::getArticle(object(ArticleModel), false, false, 'main')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:360)
  at Contao\Controller::getFrontendModule('0', 'main')
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:165)
  at Contao\PageRegular->prepare(object(PageModel))
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:46)
  at Contao\PageRegular->getResponse(object(PageModel), true)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:343)
  at Contao\FrontendIndex->renderPage(object(PageModel))
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/index.php:31)   

Introduced in #2072.

Requesting review from @m-vo :-)

2021-02-21 17:09 UTC, richardhj commented
Failing tests unrelated.

2021-02-21 18:04 UTC, m-vo requested changes

2021-02-21 18:04 UTC, m-vo commented on core-bundle/src/Resources/contao/library/Contao/Controller.php
> +			->enableLightbox($rowData['fullsize'] ?: false)
Elvis does not check array access, null coalescing does. So this must IMHO stay as it is with an added cast.

```suggestion
			->enableLightbox((bool)($rowData['fullsize'] ?? false))
```

2021-02-21 18:08 UTC, m-vo approved these changes

2021-02-22 06:49 UTC, aschempp approved these changes

2021-02-22 07:56 UTC, bytehead approved these changes

2021-02-23 13:23 UTC, ausi approved these changes

2021-03-03 17:05 UTC, merged

2021-03-03 17:05 UTC, leofeyer commented
Thank you @richardhj.