add @media keyword to stylesheet exports
contao/contao pull request #281
Opened 2019-01-17 09:05 UTC by mktcode

fixes part of #273

2019-01-18 16:37 UTC, leofeyer requested changes

2019-01-18 16:37 UTC, leofeyer commented on core-bundle/src/Resources/contao/classes/StyleSheets.php
> +			$objFile->append('@media ' . str_replace('@media ', '', $objStyleSheet->mediaQuery) . ' {');
Adding `@media` in the "Media query" field will break the front end, therefore we do not need the `str_replace()`.

2019-01-21 08:16 UTC, mktcode commented
I don't understand. This method is only used to send a file to the browser, for the export functionality in the backend. Do I miss something here?

2019-01-21 09:34 UTC, leofeyer commented
`$objStyleSheet->mediaQuery` can never contain `@media`, otherwise the generated `<style>` tag in the front end would be invalid. Therefore the `str_replace()` is unnecessary.

2019-01-21 09:38 UTC, mktcode commented
Ahhh okay.... gotya!

2019-01-22 08:50 UTC, merged

2019-01-22 08:50 UTC, leofeyer commented
Thank you @mktcode.