Quote parameter name in UserCreateCommand statement
contao/contao pull request #2858
Opened 2021-03-08 12:42 UTC by richardhj

| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2849
| Docs PR or issue | 

Fixes a SQL error caused by missing parameter quoting.

The source code of DBAL demonstrates that DBAL is not performing any quoting in this case: https://github.com/doctrine/dbal/blob/7da29b1c5b6ec4fe8636c0a022d98d68058a9053/src/Connection.php#L732

2021-03-08 12:51 UTC, bytehead approved these changes, later dismissed

2021-03-08 12:56 UTC, fritzmg approved these changes, later dismissed

2021-03-08 17:19 UTC, m-vo commented
This is so weird - is this at least fixed in `doctrine/dbal` 3.0? I get that they have issues with BC but having to quote identifiers is exactly the thing an abstraction layer must handle. And, apparently, that's already the case in the schema tool (see https://github.com/contao/contao/issues/1696#issuecomment-623492105).

2021-03-08 17:22 UTC, richardhj commented
> This is so weird - is this at least fixed in `doctrine/dbal` 3.0? I get that they have issues with BC but having to quote identifiers is exactly the thing an abstraction layer must handle. And, apparently, that's already the case in the schema tool (see [#1696 (comment)](https://github.com/contao/contao/issues/1696#issuecomment-623492105)).

Maybe this is different for queries that are executed from a QueryBuilder query. Idk.

2021-03-08 19:40 UTC, ausi commented
> This is so weird - is this at least fixed in `doctrine/dbal` 3.0?

No. See https://github.com/doctrine/dbal/blob/3.0.0/src/Connection.php#L690

2021-03-09 07:16 UTC, leofeyer requested changes

2021-03-09 07:16 UTC, leofeyer commented on core-bundle/src/Command/UserCreateCommand.php
> +            $data[$this->quote('groups')] = serialize(array_map('strval', $groups));
```suggestion
            $data[$this->connection->quoteIdentifier('groups')] = serialize(array_map('strval', $groups));
```

No need to add a private method in this case.

2021-03-09 18:45 UTC, m-vo approved these changes

2021-03-12 11:17 UTC, leofeyer approved these changes

2021-03-12 11:17 UTC, merged

2021-03-12 11:17 UTC, leofeyer commented
Thank you @richardhj.