Fix dc panel order dependency
contao/contao pull request #2979
Opened 2021-04-27 09:15 UTC by bezin

Follow-up to #2933

2021-04-27 09:16 UTC, fritzmg commented on core-bundle/src/Resources/contao/classes/DataContainer.php
> +use Symfony\Component\VarDumper\VarDumper;
```suggestion
```

2021-04-28 15:30 UTC, bezin commented
@leofeyer Just pinging you here to make sure you see this: This PR should be merged before the next 4.9 release 👍

2021-04-28 16:51 UTC, fritzmg requested changes
This PR contains changes, that are already present in the `4.9` branch. I think you based this branch off an outdated version? Thus it's hard to read what actually changed.

2021-04-29 07:31 UTC, ausi approved these changes

2021-04-29 07:31 UTC, bezin commented
Sorry for the mess, fixed it now. Now it is just the single commit it should be.

2021-04-29 07:59 UTC, aschempp approved these changes

2021-04-29 08:14 UTC, fritzmg approved these changes

2021-04-29 08:25 UTC, merged

2021-04-29 08:25 UTC, leofeyer commented
Thank you @bezin.