Add contao.import_user event (see #3157)
contao/contao pull request #3160
Opened 2021-07-06 20:49 UTC by bytehead

| Q                | A
| -----------------| ---
| Fixed issues     | https://github.com/contao/contao/issues/3157#issuecomment-874945013
| Docs PR or issue | contao/docs#...

Adds the missing `contao.import_user` event.

2021-07-06 20:58 UTC, m-vo approved these changes, later dismissed
btw.: Why is this called `contao.import_user`? It's only a notification, isn't it? I'd probably would expect that the event allows storing a new user or something if it has 'import' in the name. :smile:

2021-07-06 21:01 UTC, bytehead commented
Indeed. The behaviour is somehow strange as you read the docs: 

> A record must exist in the database for Contao to load a user. Return true if you added the user to the respective table, or false if not.

https://docs.contao.org/dev/reference/hooks/importUser/#return-values

I'm open for naming proposals 😬

2021-07-07 06:05 UTC, leofeyer requested changes
The hook returns `$blnLoaded` therefore the event should do, too. Something like this:

```php
$event = new ImportUserEvent($username, $password, $user->strTable);

System::getContainer()->get('event_dispatcher')->dispatch($event, ContaoCoreEvents::IMPORT_USER);

if (!$event->isLoaded() && self::triggerImportUserHook($username, $password, $user->strTable) === false)
{
    return null;
}
```

2021-07-07 07:17 UTC, bytehead commented
Like in 173fe9759?

2021-07-07 08:02 UTC, m-vo commented
Or maybe just an `addUser` method on the event? And then the dispatching code performs the db operation + sets loaded accordingly?

2021-07-07 08:20 UTC, leofeyer commented
> Like in [173fe97](https://github.com/contao/contao/commit/173fe97591b3eb39680199ceeeef1235b169f25b)?

Yes, I guess so. This at least reproduces the current behavior of the hook.

@contao/developers Do we want to keep it this way or do we want to improve the event logic?

2021-07-07 08:25 UTC, fritzmg commented
I am in favor of @m-vo 's suggestion to add an `addUser` or `setUser` method. If it's only `setUser`, the last event listener that sets a user would win (whereas wit the hook the first event listener that returns `true` wins).

2021-07-07 08:35 UTC, bytehead commented
I like the idea of @m-vo. But I'm not sure, which one should be the "winning" event?

2021-07-07 08:39 UTC, m-vo commented
>  But I'm not sure, which one should be the "winning" event?

Good question. I'd say the first one, then it reflects the event priority. Maybe `setUser` can only be called once and throws on subsequent calls?

2021-07-07 14:49 UTC, aschempp requested changes
I'm against adding this event. We agreed to not add events that simply replace hooks, and there is no advantage in using this event than the current hook. Also, the event is most likely not gonna stay in Contao 5 (with updated Symfony security).

2021-07-29 13:22 UTC, leofeyer commented
As discussed in Mumble on July 29th, we do not want to add the hook, because it would most likely be removed again in Contao 5. Symfony security has changed massively and we will have to rework the implementation.

2021-07-29 13:22 UTC, closed without merging