Use upcoming v2 of league/commonmark
contao/contao pull request #3191
Opened 2021-07-13 16:36 UTC by Toflar

Looks like league/commonmark is released as v2 very soon so I think we should ship our own 4.12 RC already with the updated version. Timing looks like we'll be able to use v2 stable soon :)

See https://twitter.com/colinodell/status/1413951540885344261

2021-07-13 16:43 UTC, Toflar commented
Oh, it requires PHP 7.4 🙈 Makes sense to me as 7.3 is security fixes only.
What are we doing now @contao/developers? Providing a brand new content element with the latest version of the library sounds desirable somehow...

2021-07-13 16:48 UTC, m-vo commented
Can we be compatible to both versions?

2021-07-13 16:52 UTC, Toflar commented
Well, then we can also just leave it as is and merge it for 4.13. I guess we'll bump the minimum PHP version there anyway (it's about time).

2021-07-13 21:41 UTC, ausi commented
> Oh, it requires PHP 7.4 🙈 Makes sense to me as 7.3 is security fixes only.

+1 for requiring PHP 7.4 for Contao 4.12.

2021-07-13 21:54 UTC, ausi commented on composer.json
> +        "league/commonmark": "^2.0@dev",
```suggestion
        "league/commonmark": "^2.0@RC",
```
Using `@RC` should be possible here I think, and should be better compatible with installing the Contao RC version.

2021-07-13 21:59 UTC, m-vo commented
I just realized it's only 3,5 months after the 4.12 release that PHP7.3 will be EOL. So I'm all for raising the requirement to 7.4 as well. 👍

2021-07-14 07:56 UTC, aschempp requested changes, later dismissed
`@dev` requirements are not propagated to the root package. Merging this would mean Contao 4.x can no longer be installed without lowering `minimum-stability` in a root package. I suggest to change this and only merge if the package has been released in a stable version.

2021-07-14 07:59 UTC, ausi commented
> `@dev` requirements are not propagated to the root package.

But `@RC` should work I think https://github.com/contao/contao/pull/3191#discussion_r669136391 (as long as Contao is `RC` itself)

But it would be nice if we could get an ETA on the relase date of the stable version of the library.

2021-07-14 08:06 UTC, Toflar commented
I've updated the PR to the state it would be once the release is here and converted it to a draft for now.

2021-07-31 16:19 UTC, m-vo commented
Looks like there is a release by now: https://github.com/thephpleague/commonmark/releases/tag/2.0.0

2021-08-02 12:55 UTC, Toflar commented
Ready for review then. Failing CS does not seem to be related.

2021-08-02 13:05 UTC, ausi submitted a review, later dismissed

2021-09-07 15:37 UTC, leofeyer approved these changes

2021-09-07 15:38 UTC, merged

2021-09-07 15:38 UTC, leofeyer commented
Thank you @Toflar.