Update tl_settings.xlf tl_settings.defaultGroup.1
contao/contao pull request #3205
Opened 2021-07-18 11:43 UTC by Mynyx

Adjustment of the explanation ``tl_settings.defaultGroup.1`` in respect of the title of the back end module "User groups".

2021-07-19 09:55 UTC, fritzmg requested changes
If this really needs to be changed, then this needs to be changed in multiple places, not just this one. Further examples:

* `tl_article.groups.1`
* `tl_content.groups.1`
* `tl_module.groups.1`
* `tl_page.groups.1`
* `tl_page.cgroup.1`

2021-07-19 19:08 UTC, Mynyx commented
Thank you for the hint. I have also amended ``tl_page.cgroup.1`` now. 

However, the other places refer to member groups, which is already evident from the label there.

2021-07-28 11:36 UTC, aschempp approved these changes

2021-07-28 13:55 UTC, leofeyer commented
Thank you @Mynyx.

2021-07-28 13:55 UTC, merged