Check if indexer service exists first
contao/contao pull request #3283
Opened 2021-08-11 09:02 UTC by bytehead

| Q                | A
| -----------------| ---
| Fixed issues     | n/a
| Docs PR or issue | n/a

When the default search indexer is disabled and you click on purge search index you'll get a `ServiceNotFoundException`: `You have requested a non-existent service "contao.search.indexer".`

2021-08-11 09:30 UTC, ausi submitted a review, later dismissed

2021-08-11 09:36 UTC, Toflar requested changes

2021-08-11 09:36 UTC, Toflar commented on core-bundle/src/Resources/contao/library/Contao/Automator.php
>  		if (null === $searchIndexer)
This can be removed as well then, no?

2021-08-11 09:38 UTC, bytehead commented on core-bundle/src/Resources/contao/library/Contao/Automator.php
>  		if (null === $searchIndexer)
The `Container::get` could still return `null`, no?

2021-08-11 09:39 UTC, Toflar commented on core-bundle/src/Resources/contao/library/Contao/Automator.php
>  		if (null === $searchIndexer)
If you check for `has()` previously, I don't think that can work, no :)

2021-08-11 09:40 UTC, bytehead commented on core-bundle/src/Resources/contao/library/Contao/Automator.php
>  		if (null === $searchIndexer)
Removed in ecc8f31db.

2021-08-11 09:44 UTC, Toflar submitted a review, later dismissed

2021-08-12 09:48 UTC, ausi approved these changes

2021-08-12 11:14 UTC, merged

2021-08-12 11:14 UTC, leofeyer commented
Thank you @bytehead.

2021-08-16 07:37 UTC, aschempp commented
Shouldn't we just not offer this option instead in the back end or automator CLI ?

2021-08-17 08:44 UTC, bytehead commented
We could indeed. I've recognized that truncating the search tables needs the indexer service. As you have deactivated the search indexer, you're not able to clear the search tables anymore. Wouldn't make it sense to truncate the tables directly in the automator?
https://github.com/contao/contao/blob/f76879682c1280fbc11e6a20497213368e0939ae/core-bundle/src/Resources/contao/library/Contao/Automator.php#L47

2021-08-17 08:48 UTC, bytehead commented
Like here: https://github.com/bytehead/contao/commit/d68a3eb06e401f86e73862af0e00658bb49851fa

2021-08-17 08:48 UTC, leofeyer commented
We should open a new issue for that and optionally add the "up for discussion" flag.

2021-08-17 08:48 UTC, bytehead commented
I'll do :)

2021-08-17 09:14 UTC, bytehead commented
See #3326