Enable putenv for Dotenv
contao/contao pull request #3294
Opened 2021-08-11 21:13 UTC by fritzmg

While developing a Google Firestore connection within Contao I noticed that defining the project ID and service credentials could not be set via the respective environment variables, when using the `.env` files.

This is because `google/cloud-core` for instance reads these environment variables only via `getenv()`. The `ContaoKernel` of the manager bundle however specifically disables the usage of `putenv()` for `Dotenv`.

Is there any specific reason for that? Otherwise I think it would be helpful to enable this for the Managed Edition.

2021-08-11 21:24 UTC, ausi commented
> Is there any specific reason for that?

I think this might have been a mistake in d1b9f2e049649de3ff685b221ee826bd636f5275 because of the message from https://github.com/symfony/symfony/blob/8e45fc043ec74ebc2d112b1ce3196b452a11b4a3/src/Symfony/Component/Dotenv/Dotenv.php#L48

2021-08-11 21:27 UTC, fritzmg commented
Ah yes, then it worked before Contao 4.8.0 because in Symfony 4.4 the default was `true`.

_Note:_ with Symfony 5.0 the default was changed to `false` and with Symfony 5.1 the parameter is deprecated and you should use `->usePutenv(true)` instead.

2021-08-11 21:28 UTC, ausi commented
@fritzmg do we need to upate these places too?

https://github.com/contao/contao/blob/6a676204294a2613013bfb88a1be8d4247ac2254/manager-bundle/src/ContaoManager/ApiCommand/GetDotEnvCommand.php#L58

https://github.com/contao/contao/blob/6a676204294a2613013bfb88a1be8d4247ac2254/manager-bundle/src/Dotenv/DotenvDumper.php#L44

2021-08-11 21:29 UTC, fritzmg commented
> @fritzmg do we need to upate these places too?

I think it does not matter for these places, because they are only used to display the environment variables set via `.env` and they don't retrieve them via `getenv()`.

2021-08-11 21:36 UTC, ausi commented
> Is there any specific reason for that?

Symfony writes in the method description of `usePutenv()` _“Beware that `putenv()` is not thread safe, that's why this setting defaults to false”_

But the thread safety is not really relevant for us I guess? 
Shoud we additionaly create an issue at `google/cloud-store` to tell them about the problems with `getenv()`?

2021-08-11 21:37 UTC, ausi approved these changes

2021-08-11 21:46 UTC, fritzmg commented
> Symfony writes in the method description of `usePutenv()` _“Beware that `putenv()` is not thread safe, that's why this setting defaults to false”_
> 
> But the thread safety is not really relevant for us I guess?

I am not even sure if that's actually true? The PHP doc do not mention any thread safety issues with `putenv()`. And the PHP doc for `getenv()` mentions the following:

> If PHP is running in a SAPI such as Fast CGI, this function will always return the value of an environment variable set by the SAPI, even if putenv() has been used to set a local environment variable of the same name. Use the local_only parameter to return the value of locally-set environment variables.

2021-08-12 06:44 UTC, leofeyer commented
Is this really a Contao issue? Sounds more like `google/cloud-store` should adjust their .env handling, doesn't it?

2021-08-12 07:09 UTC, ausi commented
As the PHP doc doesn’t say anything about `getenv()` being deprecated or shouldn’t be used I think I would be in favor of enabling `putenv` in Contao.

From the docs:
<img width="588" alt="Bildschirmfoto 2021-08-12 um 09 07 15" src="https://user-images.githubusercontent.com/367169/129153274-9eddc8ed-c073-45b7-b3e5-6ab9b9fe2a83.png">

2021-08-12 07:15 UTC, ausi commented
From nicolas-grekas in https://github.com/symfony/recipes/pull/571#issuecomment-481711573

> Alternatively, you should ensure to always use `$_SERVER` and never `getenv()`. It's broken anyway.

2021-08-12 07:25 UTC, fritzmg commented
Threads like [this one](https://stackoverflow.com/questions/8798294/getenv-vs-env-in-php) actually overall recommend `getenv()` over `$_SERVER` or `$_ENV`.

2021-08-12 10:19 UTC, aschempp commented
I worry `setenv` can be a security issue on a shared hosting. Why would Google read the parameters from a **running** PHP environment?

2021-08-12 11:17 UTC, Toflar requested changes
👎  on this PR for the mentioned reasons.

2021-08-12 11:29 UTC, fritzmg commented
> I worry `setenv` can be a security issue on a shared hosting.

In what way?

> Why would Google read the parameters from a **running** PHP environment?

What do you mean by that?

> 👎 on this PR for the mentioned reasons.

Which reasons would that be? So far haven't found any actual references regarding thread safety or security issues when using `putenv()` and `getenv()`. When creating an issue in Google's repository I would need to have some basis for why it should be changed, otherwise there is no real reason for them to change it.

2021-08-12 11:39 UTC, Toflar commented
https://mattallan.me/posts/how-php-environment-variables-actually-work/ would be a good read as a start :)

2021-08-12 11:43 UTC, fritzmg commented
Thank you :). But that article actually suggests to use `putenv`, as you cannot make sure that `$_SERVER` or `$_ENV` are actually available. Instead you should use `putenv` - but make sure that `putenv` is not used in worker threads. Which I would argue is the case when using something like `Dotenv`, because you execute that once in the beginning of your script (i.e. the Kernel), before potentially any sub-threads are created.

2021-08-12 11:45 UTC, Toflar commented
No, that article suggests NOT to use `putenv()`. It explains the differences and why it's not safe to use `putenv()`. You cannot rely on `$_SERVER` as it is dependent on the SAPI but in the SAPIs we support, we know it's **always** there. If it wasn't there, nothing would work. You couldn't even access Contao at all.

2021-08-12 11:48 UTC, fritzmg commented
I was referring to this section of the article:

> How do we avoid the segmentation fault? Some developers have begun suggesting that you use $_SERVER or $_ENV instead of getenv to read environment variables. This certainly avoids the problem but it’s not as easy as you might think.
> 
> As mentioned above, if you don’t control the server you can’t guarantee $_SERVER and $_ENV will be enabled. $_ENV is disabled by default. It’s unlikely that $_SERVER is disabled but if you use $_SERVER your app won’t work with PHP’s built-in web > server.
> 
> Secondly, it’s very difficult to guarantee that all the C libraries you depend on will avoid getenv. For example, the finfo_open calls getenv if you don’t specify the $magic_file. Even $_SERVER and $_ENV call getenv when they are initialized. You > would need to audit all of libc, PHP, every PHP library, and every extension to guarantee getenv wasn’t being called.
> 
> Thirdly, if you are using pthreads the superglobals are empty in the worker thread. The only way to access the main thread’s environment variables is to call getenv.
> 
> A much simpler solution is to avoid calling putenv in worker threads. If you are using putenv to populate environment variables you only need to do that once. Each worker thread will inherit the environment variables of the parent thread, so you don’t need to populate them again. Get the bootstrapping out of the way before you create a thread and you won’t have any issues.

Specifically the last paragraph.

> You cannot rely on `$_SERVER` as it is dependent on the SAPI but in the SAPIs we support, we know it's **always** there. If it wasn't there, nothing would work. You couldn't even access Contao at all.

But that would be application specific and thus not really an argument for an independent library to not use `getenv()`.

2021-08-12 11:50 UTC, Toflar commented
We just cannot use `putenv()` by default on a CMS that's used on thousands on different server settings. No way.

2021-08-12 12:50 UTC, fritzmg commented
I tend to agree now. It just means that the convenience of `.env` will not work for every library. You'll either have to use true environment variables - or none.

For anyone stumbling over the same: I ended up defining the Firestore client service like this, so that I can still use `.env`:

```yaml
services:
    Google\Cloud\Firestore\FirestoreClient:
        arguments: [{keyFilePath: '%env(GOOGLE_APPLICATION_CREDENTIALS)%', projectId: '%env(GOOGLE_CLOUD_PROJECT)%'}]
```

2021-08-12 12:50 UTC, closed without merging