Add null check to array access
contao/contao pull request #3368
Opened 2021-08-23 13:15 UTC by bytehead

| Q                | A
| -----------------| ---
| Fixed issues     | Fixes n/a
| Docs PR or issue | n/a

Fixes `Warning: Undefined array key "class"`:

```
ErrorException:
Warning: Undefined array key "class"

  at vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:900
  at Contao\DataContainer->generateGlobalButtons()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:4822)
  at Contao\DC_Table->listView()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:350)
  at Contao\DC_Table->showAll()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:648)
  at Contao\Backend->getBackendModule('news', null)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:167)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:43)
```

2021-08-23 13:20 UTC, m-vo requested changes

2021-08-23 13:20 UTC, m-vo commented on core-bundle/src/Resources/contao/classes/DataContainer.php
> +				$v['class'] = trim($v['class'] ?? '' . ' header_icon');
```suggestion
				$v['class'] = trim(($v['class'] ?? '') . ' header_icon');
```

see https://3v4l.org/5AQjI#v8.0.9

2021-08-23 13:21 UTC, bytehead commented on core-bundle/src/Resources/contao/classes/DataContainer.php
> +				$v['class'] = trim($v['class'] ?? '' . ' header_icon');
🙈 thanks! fixed in 08effd89b.

2021-08-23 13:22 UTC, m-vo approved these changes

2021-08-23 17:41 UTC, ausi approved these changes

2021-08-24 08:46 UTC, leofeyer commented
Thank you @bytehead.

2021-08-24 08:46 UTC, merged