Correctly filter the root nodes in the extended tree view
contao/contao pull request #3563
Opened 2021-10-08 09:38 UTC by leofeyer

| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #3391
| Docs PR or issue | -

I have noticed that the changes from #3391 make some articles disappear:

<img width="690" alt="" src="https://user-images.githubusercontent.com/1192057/136533998-effabae9-4b7a-48a7-bfb9-d7d9f752ce39.png">

Here is how it should look:

<img width="619" alt="" src="https://user-images.githubusercontent.com/1192057/136534072-a4ba6dd2-d7ec-4d24-b0d9-3758aa52df87.png">

@Toflar Can you please confirm that the fix is correct? And could we not omit the check entirely for admins?

2021-10-08 12:24 UTC, Toflar requested changes
Changes are not correct, will check after my vacation :)

2021-10-21 12:22 UTC, Toflar commented
So imho the problem here is that this also filters on `tl_article` IDs whereas it should only on `tl_page`. Is that correct?

2021-10-21 16:17 UTC, leofeyer commented
Yes.

2021-10-22 07:02 UTC, Toflar commented
Then I think https://github.com/contao/contao/pull/3596 is the correct fix.

2021-10-22 07:48 UTC, closed without merging