Fix the base path in the asset context
contao/contao pull request #3595
Opened 2021-10-21 15:53 UTC by aschempp

| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #3448

2021-10-21 15:58 UTC, m-vo commented
Memo to myself: Is `getStaticUrl()` unaffected by this or are we using it correctly in https://github.com/contao/contao/blob/4.x/core-bundle/src/Image/Studio/ImageResult.php#L230? (/cc @ausi)

2021-10-21 16:19 UTC, leofeyer commented on core-bundle/src/Resources/contao/library/Contao/Template.php
>  		return ltrim($url, '/');
Is this still required now that we are using `Url::makeRelative()`?

2021-10-22 06:34 UTC, aschempp commented on core-bundle/src/Resources/contao/library/Contao/Template.php
>  		return ltrim($url, '/');
It is only applied if there is no request (e.g. on the command line).

2021-10-22 06:59 UTC, bennyborn commented on core-bundle/src/Resources/contao/library/Contao/Template.php
> +		$request = System::getContainer()->get('request_stack')->getMainRequest();
I guess that should also say `getMasterRequest`

2021-10-22 07:42 UTC, leofeyer submitted a review, later dismissed

2021-10-22 07:44 UTC, bennyborn commented
Still not quite working for me

![image](https://user-images.githubusercontent.com/226890/138414084-27a7f6af-78ae-4b4c-9bb7-5818260519b3.png)

2021-10-22 10:59 UTC, fritzmg requested changes

2021-10-22 10:59 UTC, fritzmg commented on core-bundle/src/Resources/contao/library/Contao/Template.php
> +		}
I'll test if this will work under Windows.

2021-10-22 11:00 UTC, aschempp commented on core-bundle/src/Resources/contao/library/Contao/Template.php
> +		}
i think it should since it is a URL and not a file path, but please test it

2021-10-22 11:10 UTC, fritzmg approved these changes

2021-10-22 11:10 UTC, fritzmg commented on core-bundle/src/Resources/contao/library/Contao/Template.php
> +		}
Yep, looks fine. `('assets.packages')->getUrl('js/swipe.min.js')` will return 

```
/subfolder/web/assets/js/swipe.min.js
```

(when Contao is accessed via `http://localhost/subfolder/web` for example) and `$basePath` will be 

```
/subfolder/web/
```

and thus the condition will be true and `assets/swipe/js/swipe.min.js` is returned 👍

2021-10-22 11:10 UTC, fritzmg commented
> Still not quite working for me

@bennyborn should be fine now, can you test again? :)

2021-10-22 11:22 UTC, bennyborn commented
Yep, works now! 🎉

2021-10-22 12:35 UTC, leofeyer commented on core-bundle/src/Resources/contao/library/Contao/Template.php
> +		return $url;
So now we do not need the `ltrim()` anymore? Haven't you just explained to me that it is still required if there is no request? https://github.com/contao/contao/pull/3595/files/46f536900cda60b46dc8cd8a7e993d75919a8fc8#r733842318

2021-10-25 07:11 UTC, aschempp commented on core-bundle/src/Resources/contao/library/Contao/Template.php
> +		return $url;
`$basePath` is `/` by default so will be stripped if available. The unit tests confirm that 😉

2021-10-25 13:53 UTC, merged