Add a setting for allowed insert tags
contao/contao pull request #3603
Opened 2021-10-25 17:16 UTC by ausi

2021-10-25 21:51 UTC, m-vo submitted a review, later dismissed

2021-10-26 08:10 UTC, aschempp commented on core-bundle/src/Resources/contao/library/Contao/InsertTags.php
> +				$strBuffer .= '{{' . $strTag . '}}';
doesn't this cause endless recursion?

2021-10-26 08:10 UTC, aschempp commented on core-bundle/src/DependencyInjection/Configuration.php
> +                ->arrayNode('allowed_tags')
I really don't like to create a config group for this only option. Maybe it could be added to `contao.security` or find a way to merge it with the `sanitizer` config? 😬

2021-10-26 08:21 UTC, ausi commented on core-bundle/src/DependencyInjection/Configuration.php
> +                ->arrayNode('allowed_tags')
`security` and `two_factor` also have only one option, so this should not be a problem I think.

2021-10-26 08:21 UTC, ausi commented on core-bundle/src/Resources/contao/library/Contao/InsertTags.php
> +				$strBuffer .= '{{' . $strTag . '}}';
No, see tests ☺️

2021-10-26 11:43 UTC, SeverinGloeckle commented on core-bundle/src/DependencyInjection/Configuration.php
> +                ->arrayNode('allowed_tags')
As long as only this one option is planned for the foreseeable future, I'd also prefer `contao.security.allowed_insert_tags` over `contao.insert_tags.allowed_tags` since limiting the available insert tags is most likely done for security reasons.

I could imagine options to configure the caching or maybe the delimiters for insert tags though. Then, the more general configuration group `contao.insert_tags` would be useful.

2021-10-28 09:04 UTC, ausi commented on core-bundle/src/DependencyInjection/Configuration.php
> +                ->arrayNode('allowed_tags')
I’m pretty sure that we will get more settings for the `contao.insert_tags.` category in the future.

2021-10-28 09:19 UTC, Toflar submitted a review, later dismissed

2021-10-28 10:29 UTC, fritzmg requested changes

2021-10-28 10:29 UTC, fritzmg commented on core-bundle/src/DependencyInjection/Configuration.php
> +                    ->example(['*_url', 'request_token'])
How do I disable the `insert_content` insert tag specifically for example? I'll have to write `['insert_content::*']`, correct? If yes, I think we should add that to the example.

2021-10-28 11:09 UTC, ausi commented on core-bundle/src/DependencyInjection/Configuration.php
> +                    ->example(['*_url', 'request_token'])
No, only the name is checked. So `'insert_content'` would be the correct setting to **allow** it.

2021-10-28 11:40 UTC, fritzmg commented on core-bundle/src/DependencyInjection/Configuration.php
> +                    ->example(['*_url', 'request_token'])
But it is checked against `$strTag`, and `$strTag` doesn't contain just the insert tag's name, but the whole string without any modifiers (e.g. "`insert_content::129`"). But according to the test it works. I am a little confused about it.

2021-10-28 12:53 UTC, ausi commented on core-bundle/src/DependencyInjection/Configuration.php
> +                    ->example(['*_url', 'request_token'])
It is checked against `$elements[0]` in line 141.

2021-10-28 13:14 UTC, fritzmg commented on core-bundle/src/DependencyInjection/Configuration.php
> +                    ->example(['*_url', 'request_token'])
Right, my bad :)

2021-10-28 13:14 UTC, fritzmg submitted a review, later dismissed

2021-10-29 07:54 UTC, aschempp commented on core-bundle/src/DependencyInjection/Configuration.php
> +                ->arrayNode('allowed_tags')
in your own words, that would be pretty easy to deprecate and move then, right? 😝

2021-10-29 07:59 UTC, ausi commented on core-bundle/src/DependencyInjection/Configuration.php
> +                ->arrayNode('allowed_tags')
Sure, I’m happy with both `contao.insert_tags.allowed_tags` as well as `contao.allowed_insert_tags` but this would create a new key under `contao.` too so I don’t see any benefit. Especially if we already know that we want to add more insert tags related things in the future.

2021-10-29 09:17 UTC, aschempp requested changes

2021-10-29 09:17 UTC, aschempp commented on core-bundle/src/Resources/contao/library/Contao/InsertTags.php
> +		$allowedTagsRegex = '(' . implode('|', array_map(static function ($allowedTag)
I wonder whether this is something we could actually do when storing the configuration in the container, so it only needs to be done once for cache warmup instead of every time tags are replaced (for every template!)?

2021-10-29 09:39 UTC, ausi commented on core-bundle/src/Resources/contao/library/Contao/InsertTags.php
> +		$allowedTagsRegex = '(' . implode('|', array_map(static function ($allowedTag)
Fixed in 5b3d2c68bc903460b71e921787e1582bda42d264

2021-10-30 09:38 UTC, m-vo approved these changes, later dismissed

2021-11-04 15:01 UTC, aschempp commented on core-bundle/src/Resources/contao/library/Contao/InsertTags.php
> +		$allowedTagsRegex = '(' . implode('|', array_map(static function ($allowedTag)
why build and reset something on every request instead of once if the container can never change? 🤷

2021-11-04 15:01 UTC, aschempp commented on core-bundle/src/DependencyInjection/Configuration.php
> +                ->arrayNode('allowed_tags')
I liked @SeverinGloeckle's idea of `contao.security.allowed_insert_tags`

2021-11-04 15:12 UTC, ausi commented on core-bundle/src/Resources/contao/library/Contao/InsertTags.php
> +		$allowedTagsRegex = '(' . implode('|', array_map(static function ($allowedTag)
So that compiler passes can change the parameter without having to deal with the regex.

2021-11-04 15:13 UTC, ausi commented on core-bundle/src/DependencyInjection/Configuration.php
> +                ->arrayNode('allowed_tags')
For me it does not belong to `contao.security`

2021-11-09 11:28 UTC, leofeyer commented
@ausi There is a conflict now that needs to be resolved. 🙈

2021-11-09 14:10 UTC, ausi commented
> There is a conflict now that needs to be resolved. 🙈

Done

2021-11-18 10:44 UTC, leofeyer approved these changes

2021-11-18 10:49 UTC, merged

2021-11-18 10:49 UTC, leofeyer commented
Thank you @ausi.