Do not set the server_version
contao/contao pull request #3623
Opened 2021-10-27 01:44 UTC by ausi

| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1696

For the record as described in https://github.com/contao/contao/pull/3623#issuecomment-952708988 the `CommandSchedulerListener` must only load the `Cron` service when it needs it. Otherwise the install tool would fail when terminating because the `Cron` service needs ORM metadata which itself needs to know the `server_version`.

2021-10-27 01:47 UTC, m-vo submitted a review, later dismissed
Awesomesauce!

2021-10-27 08:42 UTC, fritzmg commented
Very nice! What is the reason behind the `CommandSchedulerListener` changes though?

2021-10-27 09:14 UTC, m-vo commented
The class gets instantiated in the kernel terminate event. And because it gets an entity repository injected, this will trigger warming the doctrine proxy classes again...

2021-10-27 11:19 UTC, bytehead submitted a review, later dismissed

2021-10-27 12:42 UTC, Toflar requested changes

2021-10-27 12:42 UTC, Toflar commented on core-bundle/src/Resources/config/services.yml
> +    Contao\CoreBundle\Doctrine\ORM\FailTolerantProxyCacheWarmer:
This should not happen, if `server_version` was explicitly configured.

2021-10-27 12:47 UTC, m-vo commented on core-bundle/src/Resources/config/services.yml
> +    Contao\CoreBundle\Doctrine\ORM\FailTolerantProxyCacheWarmer:
Yes, we noted this as well, needs to be adjusted. :upside_down_face:

2021-10-27 13:20 UTC, ausi commented on core-bundle/src/Resources/config/services.yml
> +    Contao\CoreBundle\Doctrine\ORM\FailTolerantProxyCacheWarmer:
Done in 2236de4a5ef3d8a1199fa593cf85f811e6a340c0

2021-10-27 13:24 UTC, Toflar approved these changes

2021-10-27 13:59 UTC, m-vo approved these changes

2021-10-29 07:14 UTC, aschempp requested changes
great catch! How about making the `Cron` service `lazy: true` instead? That would solve the problem for anyone using the cron service, not just our command scheduler.

2021-10-29 07:46 UTC, ausi commented
I think using a service subscriber is more straight forward and doesn’t require to generate proxy classes that are not needed in 99 % of the cases.

2021-10-29 08:38 UTC, fritzmg approved these changes

2021-10-29 08:38 UTC, fritzmg commented
Would it make sense to rewrite the Cron service to not use entities? Or would that not actually help in this case anyway?

2021-10-29 08:43 UTC, ausi commented
> Would it make sense to rewrite the Cron service to not use entities?

IMO no. As we want to get rid of the install tool, this fix should be sufficient for now.

2021-10-29 09:25 UTC, aschempp commented
> I think using a service subscriber is more straight forward and doesn’t require to generate proxy classes that are not needed in 99 % of the cases.

Dunno... its all the changes in https://github.com/contao/contao/pull/3623/files?diff=unified&w=0#diff-301de337aef887f559d97bb8997b22086044dc3c2621b2a35e1a801802016e3b and its test vs. one `lazy: true`...  But yeah both works 🤷

2021-11-03 10:11 UTC, merged

2021-11-03 10:11 UTC, leofeyer commented
Thank you @ausi.