Make image width and height overwritable in the upload widget
contao/contao pull request #3628
Opened 2021-10-28 10:35 UTC by doishub

In addition to the upload size and file extensions, image widths and heights can also be overwritten within the upload field.

2021-10-28 10:36 UTC, fritzmg commented
The _Docs PR or issue_ is meant to be a link to a github.com/contao/docs Pull Request explaining the new features - or at least an issue that new features need to be explained :)

2021-10-28 10:38 UTC, fritzmg requested changes

2021-10-28 10:38 UTC, fritzmg commented on core-bundle/src/Resources/contao/forms/FormFileUpload.php
> +			$intImageWidth = $this->getMaximumImageWidth();
```suggestion
			$intImageWidth = $this->maxImageWidth ?: Config::get('imageWidth');
```

imho we do not need a separate method for that

2021-10-28 10:47 UTC, fritzmg submitted a review, later dismissed

2021-10-28 10:53 UTC, m-vo commented on core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
> +        <source>Here you can enter the maximum width for image uploads in pixels.</source>
Should there be an explanation that `0` means "use the value from the config"?

2021-10-28 11:02 UTC, fritzmg commented on core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
> +        <source>Here you can enter the maximum width for image uploads in pixels.</source>
The translation is exactly the same as in `tl_settings`: https://github.com/contao/contao/blob/f562af12895bbfaa9adb51107af6d4f18ba6af86/core-bundle/src/Resources/contao/languages/en/tl_settings.xlf#L110-L121

If we want to change this, it should be changed in both places.

2021-10-28 11:06 UTC, doishub commented on core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
> +        <source>Here you can enter the maximum width for image uploads in pixels.</source>
Yes makes sense, like so "Here you can enter the maximum width for image uploads in pixels. Set to 0 to use the default settings."?

2021-10-28 11:09 UTC, doishub commented on core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
> +        <source>Here you can enter the maximum width for image uploads in pixels.</source>
> If we want to change this, it should be changed in both places.

Only within the upload field the default settings are used as fallback. I think it would have to be changed only within the upload field.

2021-10-28 11:12 UTC, m-vo commented on core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
> +        <source>Here you can enter the maximum width for image uploads in pixels.</source>
Setting `0` in the config also has a special meaning, i.e.: no limit at all.

2021-10-28 11:22 UTC, doishub commented on core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
> +        <source>Here you can enter the maximum width for image uploads in pixels.</source>
Ah now I see it. We have three levels to make these settings:
1. config.yml
2. settings
3. upload field

When the values are set in config, the fields inside settings are disabled. Therefore I would almost say, no further explanation would have to follow here. However, in the field we should include this.

2021-10-29 07:24 UTC, aschempp commented on core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
> +        <source>Here you can enter the maximum width for image uploads in pixels.</source>
`config.yml` and settings are the same. If a config is set in the `config.yml`, you cannot override it in the back end, that's why the field is disabled. I don't think the form field should be disabled in that case though, and the global config still applies.

Regarding the labels, I would suggest to keep them the same in both places (= copy to the form field language file). This way [Transifex](https://www.transifex.com) should re-use all translations automatically for the form fields.

2021-10-29 08:54 UTC, fritzmg commented on core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
> +        <source>Here you can enter the maximum width for image uploads in pixels.</source>
Unless we want to be able to disable the max image width and height completely for a form field, while still having a max image width and height in the system setting. This is currently not possible, as the field will always be `0` and in that case it will fall back to the system setting.

2021-10-29 08:59 UTC, Toflar commented on core-bundle/src/Resources/contao/forms/FormFileUpload.php
> +			$intImageWidth = $this->maxImageWidth ?: Config::get('imageWidth');
```suggestion
			$intImageWidth = $this->maxImageWidth ? min($this->maxImageWidth, Config::get('imageWidth')) : Config::get('imageWidth');
```

I don't think as a user you should be able to increase the maximum of the system settings, only decrease. As a system admin, I want to be able to control maximum values.

2021-10-29 09:15 UTC, doishub commented on core-bundle/src/Resources/contao/forms/FormFileUpload.php
> +			$intImageWidth = $this->maxImageWidth ?: Config::get('imageWidth');
Basically I agree with you, but this is exactly the case I want to achieve with this PR. My customer wants to keep the limit (configuration settings) in all forms, only in this form it should be possible to upload bigger files (images). 🤔

2021-10-29 09:15 UTC, fritzmg commented on core-bundle/src/Resources/contao/forms/FormFileUpload.php
> +			$intImageWidth = $this->maxImageWidth ?: Config::get('imageWidth');
~~In that case you can remove/not add that field in the user rights.~~

2021-10-29 09:17 UTC, fritzmg commented on core-bundle/src/Resources/contao/forms/FormFileUpload.php
> +			$intImageWidth = $this->maxImageWidth ?: Config::get('imageWidth');
May be add a save callback, so that only admins can set it higher than the system limit? 🤔

2021-10-29 09:19 UTC, aschempp commented on core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
> +        <source>Here you can enter the maximum width for image uploads in pixels.</source>
good question. I don't think that would be sensible though. If I configure a system wide image limitation, shouldn't that apply to forms as well? Alternatively, if the system configuration is (mostly) meant for the back end uploads, we might consider migrating the configuration to all form widgets and not inherit system settings at all. Just maybe use the system setting as default for new form fields.

2021-10-29 09:20 UTC, aschempp commented on core-bundle/src/Resources/contao/forms/FormFileUpload.php
> +			$intImageWidth = $this->maxImageWidth ?: Config::get('imageWidth');
if that were useful the admin could simply hide the field for the back end user.

2021-12-16 11:54 UTC, eki89 commented on core-bundle/src/Resources/contao/forms/FormFileUpload.php
> +			$intImageWidth = $this->maxImageWidth ?: Config::get('imageWidth');
> I don't think as a user you should be able to increase the maximum of the system settings, only decrease. As a system admin, I want to be able to control maximum values.

I agree with you. However, it is a special case when the file size is set higher for an upload field. If you need to set the system-wide maximum value higher for this special case, it also follows that all default upload fields would have to be limited manually.

Splitting imageWidth into a default value and an absolute maximum value could help. In this case a checkbox to activate the limitation in upload fields could be a solution to handle all cases.

Using a special value for the backend could additionally be more flexible.

2021-12-16 15:54 UTC, ausi submitted a review, later dismissed

2021-12-16 15:55 UTC, leofeyer commented on core-bundle/src/Resources/contao/forms/FormFileUpload.php
> +			$intImageWidth = $this->maxImageWidth ?: Config::get('imageWidth');
As discussed in the Contao call, we explicitly want to allow exceeding the maximum dimensions.

2021-12-16 16:04 UTC, eki89 commented
As discussed in todays Contao Call, we should add the information that 0 means "use the value from the config".

2021-12-20 08:35 UTC, doishub commented
Unfortunately, I could not join the conversation this time. Thank you for discussing the issue. 

I have adjusted the text once again. 😉

2021-12-20 14:25 UTC, ausi submitted a review, later dismissed

2021-12-22 12:28 UTC, leofeyer approved these changes

2021-12-22 12:33 UTC, merged

2021-12-22 12:33 UTC, leofeyer commented
Thank you @doishub.