Set language of redirect page in global context
contao/contao pull request #3647
Opened 2021-11-05 11:24 UTC by rabauss

Currently the language of a redirect page is not set in global context. This is especially a problem if you use language dependent insert tags in the redirect.

Affected Version: 4.9+

I'm not sure if we need to add more lines from the `prepare` method of `PageRegular`. The supposed lines are sufficient for my problem with the missing language context.

https://github.com/contao/contao/blob/2a19b186afd59495e9fbd5174d0deb40543c5079/core-bundle/src/Resources/contao/pages/PageRegular.php#L63-L69

2021-11-05 11:47 UTC, fritzmg approved these changes

2021-11-12 10:13 UTC, leofeyer commented
> This is especially a problem if you use language dependent insert tags in the redirect.

What exactly does that mean?

2021-11-12 10:20 UTC, ausi commented
> > This is especially a problem if you use language dependent insert tags in the redirect.
> 
> What exactly does that mean?

I would guess something like this:  
`{{iflng::de}}{{link_url::1}}{{iflng}}{{iflng::en}}{{link_url::1}}{{iflng}}`

2021-11-12 15:28 UTC, rabauss commented
Well, the example from @ausi would be a matching one.
We have a custom entity with DCMultilingual which can be picked and we generate a inserttag with ID of the fallback language which is then replaced by the language model.

Of course I could also use the language from global `$objPage` but I thought with this PR we get a reusable solution ;-)

2021-11-16 09:58 UTC, leofeyer commented on core-bundle/src/Resources/contao/pages/PageRedirect.php
> +		$GLOBALS['TL_KEYWORDS'] = '';
```suggestion
```

2021-11-16 09:59 UTC, leofeyer commented on core-bundle/src/Resources/contao/pages/PageRedirect.php
> +		$GLOBALS['TL_LANGUAGE'] = $objPage->language;
```suggestion
		$GLOBALS['TL_LANGUAGE'] = $objPage->language;
```

2021-11-16 09:59 UTC, leofeyer requested changes

2021-11-16 09:59 UTC, leofeyer commented on core-bundle/src/Resources/contao/pages/PageRedirect.php
> +		$GLOBALS['TL_LANGUAGE'] = $objPage->language;
```suggestion
		$GLOBALS['TL_LANGUAGE'] = $objPage->language;
```

2021-11-17 08:43 UTC, leofeyer approved these changes

2021-11-17 12:25 UTC, ausi approved these changes

2021-11-18 08:20 UTC, merged

2021-11-18 08:20 UTC, leofeyer commented
Thank you @rabauss.