Add a new sorting option for featured news.
contao/contao pull request #371
Opened 2019-02-23 16:07 UTC by xchs

This implements a new sorting option for featured news. News items marked as "featured" are therefore always listed before all other items.

This could be handy in some situations when you can accomplish this kind of sorting with only one newslist module instead of two.

2019-04-04 09:59 UTC, jankout commented
Could we have this feature for events too, please? I think it would be fine to have the same features for the events too.

2019-05-09 10:25 UTC, leofeyer commented
@xchs Is there no need to sort featured news first but descending by date?

2019-05-09 10:28 UTC, fritzmg commented
I think it wouldn't hurt to add `order_featured_asc` as well.

2019-05-09 12:14 UTC, xchs commented
> Is there no need to sort featured news first but descending by date?

@leofeyer That should already be the case, shouldn't it?

2019-05-09 12:18 UTC, leofeyer commented
You are right. 😂

2019-05-09 12:59 UTC, xchs commented
> I think it wouldn't hurt to add `order_featured_asc` as well.

@fritzmg I have now implemented this as well.

2019-06-06 09:39 UTC, leofeyer commented
While reviewing this PR, I realized that the solution is wrong. We have to add the "show featured first" option to `tl_news.news_featured`, because people might also want to combine "order by headline and show featured first" or "order randomly but show featured first".

<img width="1183" alt="" src="https://user-images.githubusercontent.com/1192057/59023264-b27f6c80-884f-11e9-86b8-91c8ebf2b05b.png">

2019-06-06 09:40 UTC, leofeyer requested changes
While reviewing this PR, I realized that the solution is wrong. We have to add the "show featured first" option to `tl_news.news_featured`, because people might also want to combine "order by headline and show featured first" or "order randomly but show featured first".

<img width="1183" alt="" src="https://user-images.githubusercontent.com/1192057/59023264-b27f6c80-884f-11e9-86b8-91c8ebf2b05b.png">

2019-06-06 18:42 UTC, xchs reviewed
I cannot approve it myself but I agree.

2019-06-27 15:02 UTC, leofeyer commented
Implemented in f5748dbb0a0a891ee12fc63656c0d7ed6a4dcd8b.

2019-06-27 15:02 UTC, closed without merging