Check for specific commands in ApplicationTest
contao/contao pull request #3745
Opened 2021-11-29 21:11 UTC by fritzmg

WIP

2021-11-29 22:54 UTC, bytehead commented
PHPStan fixes are in 3746.

2021-11-29 23:01 UTC, bytehead approved these changes
I wonder why the unit tests are still failing, changes looking correct to me.

2021-11-30 06:53 UTC, leofeyer requested changes
Since the purpose of the test is to check if the `config:get` command has been added, we can simply drop the `$this->assertCount(4, $commands)` assertion.

2021-11-30 06:54 UTC, leofeyer commented
> I wonder why the unit tests still failing, changes looking correct to me.

It is due to the remaining self deprecations I think.

2021-11-30 07:27 UTC, aschempp commented
alternatively see https://github.com/contao/contao/pull/3748, especially regarding raising the minimum Symfony version to 5.4

2021-12-01 10:41 UTC, fritzmg commented
Closing as the changes from https://github.com/contao/contao/pull/3749 will be backported by @leofeyer.

2021-12-01 10:41 UTC, closed without merging