Added annotation that generating page URLs can throw an exception
contao/contao pull request #3791
Opened 2021-12-10 07:31 UTC by aschempp

Added this to 4.12 since we already have the new routing there with exceptions.

2021-12-10 07:35 UTC, Toflar approved these changes

2021-12-10 07:47 UTC, bytehead approved these changes

2021-12-10 09:33 UTC, leofeyer requested changes
I won't merge this until we have discussed #3724.

2021-12-12 20:36 UTC, aschempp commented
I understand, but this `@throws` exactly is relevant because we DO want people to catch it – contrary to most other exceptions as mentioned by @m-vo

2021-12-13 15:11 UTC, leofeyer commented
See #3816 for a new approach then.

2021-12-19 13:44 UTC, leofeyer approved these changes

2021-12-19 13:44 UTC, merged