Fix fragments in RSS feeds
contao/contao pull request #3857
Opened 2021-12-22 13:59 UTC by fritzmg

Fixes #3856

This PR now always pushes a new request to the request stack for each individual news article. I left the original `Environment::set('request', …)` bit for the legacy framework untouched though.

2021-12-27 09:05 UTC, Toflar submitted a review, later dismissed

2021-12-29 08:04 UTC, aschempp requested changes
I really don't like this solution. That's exactly why the RSS feed should be its own controller that actually handles a request. Since I don't think this can be changed in 4.9, we should only create one fake request per RSS feed file (with the path of that file) to somehow be forward-compatible?

2021-12-29 10:28 UTC, fritzmg commented
> That's exactly why the RSS feed should be its own controller that actually handles a request.

Of course, but that would be a new feature.

> I don't think this can be changed in 4.9, we should only create one fake request per RSS feed file (with the path of that file) to somehow be forward-compatible?

Currently we create a fake request per feed item, with the feed item's URL (but only for the legacy `Environment`). I don't think we should change that in a bugfix.

2022-01-06 08:45 UTC, aschempp commented
> Currently we create a fake request per feed item, with the feed item's URL (but only for the legacy `Environment`). I don't think we should change that in a bugfix.

Can you point where we do that? The only thing I can see in your PR is that we manipulate the scope, but not create a request.

2022-01-06 10:15 UTC, fritzmg commented
See the [original issue](https://github.com/contao/contao/issues/3856), I have referenced the code there.

https://github.com/contao/contao/blob/effd5447f8072607f7dffc94c33241d154971ee2/news-bundle/src/Resources/contao/classes/News.php#L205-L207

2022-01-06 10:21 UTC, aschempp commented
🤦  The original issue (https://github.com/contao/core/issues/7756) would also be solved by a front end controller 🙊

2022-01-06 10:22 UTC, fritzmg commented
Yes, but as I said, that's a new feature for Contao 5.0.

This PR fixes fragments for RSS feeds in Contao 4.9.

2022-01-06 21:14 UTC, aschempp reviewed
I'm unsure whether we should create one request for each article or one request for the RSS file. One per article is similar to the current behaviour, but the current behaviour is wrong and would change once we have a real front end controller. Since both solutions would solve the initial problem (not having a request at all) I feel like we should "do it right"® already here 🤔

2022-01-06 21:51 UTC, fritzmg commented
But the content of a news article depends on a correct request. If you have a download content element in your news article, the download link will be wrong, if the request does not contain the correct information. Even if we generate the RSS feed via a controller in the future, we need to accommodate that.

2022-01-07 06:14 UTC, aschempp commented
hmm, again not a problem the Controller would have, since the query parameter would re-render the content and actually output the file. But I agree that currently wouldn't work and we need that fix 😢

2022-01-07 06:14 UTC, aschempp approved these changes, later dismissed

2022-01-11 21:24 UTC, ausi submitted a review, later dismissed

2022-01-21 11:30 UTC, leofeyer commented
What about RSS feeds in the calendar module? Do they not have the same problem?

2022-01-21 11:31 UTC, fritzmg commented
True, I will adjust the PR accordingly.

2022-01-22 10:26 UTC, aschempp approved these changes, later dismissed

2022-02-01 14:56 UTC, merged

2022-02-01 14:56 UTC, leofeyer commented
Thank you @fritzmg.