Add contao:sendmail command
contao/contao pull request #3869
Opened 2021-12-26 19:11 UTC by fritzmg

A `mailer:send` command will be added to Symfony only in 6.1 (or higher), if at all (see https://github.com/symfony/symfony/pull/43687). In order to also have a console command for sending emails for our last `4.x` LTS, we should integrate the command into the `contao/core-bundle`. Later on we can deprecate and forward it to the Symfony command again.

The command largely works the same way as the `swiftmailer:email:send` command previously.

2021-12-27 09:04 UTC, Toflar reviewed
👍 on merging this, however I would rename the command to `contao:mailer:send`. It allows for possible new commands in the future and does not imply any connection to the `sendmail` binary.

2021-12-27 11:59 UTC, 94noni commented on core-bundle/src/Command/SendMailCommand.php
> +            ->setDescription('Sends an email message')
you can leverage https://symfony.com/blog/new-in-symfony-5-3-lazy-command-description

2021-12-29 11:29 UTC, Toflar approved these changes

2021-12-29 15:05 UTC, bytehead approved these changes

2022-01-05 16:09 UTC, leofeyer requested changes
I would like to wait and see if Symfony really merges the PR. Depending on that, we should consider providing an extension that backports the functionality to Contao.

2022-01-05 16:15 UTC, aschempp commented
> I would like to wait and see if Symfony really merges the PR. Depending on that, we should consider providing an extension that backports the functionality to Contao.

I agree with this. We should add a command with the same name and characteristic (if possible). Which makes me wonder if this should not be in Contao itself but a bundle that can be included if you want to command-line-send in Contao 4.13 🤷

2022-01-05 16:34 UTC, fritzmg commented
> I would like to wait and see if Symfony really merges the PR.

Symfony moved it to the `6.1` milestone.

2022-01-05 17:01 UTC, fritzmg commented
> Depending on that, we should consider providing an extension that backports the functionality to Contao.

I agree too though. I wanted to create a back-port extension anyway, if this didn't make it into Symfony or the Contao Core 🙃

2022-01-08 13:25 UTC, m-vo approved these changes
Very nice. :heart: 

Could we maybe add something like a `--test` option that takes the recipient and otherwise uses some opinionated defaults (or even uses the system admin email default for the recipient as well).

 I often find myself needing this kind of quick way to test a SMTP config and could not care less about the actual contents. I just want to verify mails can be send. :smile:

2022-01-09 10:25 UTC, aschempp commented
> Could we maybe add something like a `--test` option that takes the recipient and otherwise uses some opinionated defaults (or even uses the system admin email default for the recipient as well).
> 
> I often find myself needing this kind of quick way to test a SMTP config and could not care less about the actual contents. I just want to verify mails can be send. 😄

I understand that requirement, but I think it contradicts with the fact that we want to drop this again as soon as it is supported in Symfony?

2022-01-09 12:19 UTC, m-vo commented
> as soon as it is supported in Symfony

which could be anywhere between "in quite a while" and "never" :smile:

2022-01-11 21:07 UTC, ausi approved these changes

2022-01-12 07:41 UTC, aschempp commented
As discussed in Slack (and agreed to by most core devs), this might as well be an external bundle. The advantages would be that it can be installed in versions prior to 4.13, it could be kept up-to-date with the latest Symfony PR features (without being related to a Contao version) and we could still require it in a Contao Managed Edition by default (until if Symfony ships this feature).

2022-01-12 07:47 UTC, fritzmg commented
Do we want it to be part of `contao` (not the mono repo though)?

2022-01-12 13:17 UTC, aschempp commented
> Do we want it to be part of `contao` (not the mono repo though)?

I don't see a reason to. It could be @fritzmg same as we have bundles from @terminal42 and @ausi. Being in the `contao` organisation has no benefits except enforcing it to be maintained by the core team, possibly even after we drop it from Contao.

2022-05-13 08:53 UTC, fenepedia commented
@fritzmg Will this feature be shipped with Contao 5?

2022-05-13 08:58 UTC, fritzmg commented
@fenepedia see the discussion above - we decided to not ship it with Contao. We might create a `inspiredminds/symfony-mailer-send-command-bundle`.

2022-05-13 09:48 UTC, leofeyer commented
Maybe we should close the PR then?

2022-06-20 18:22 UTC, fritzmg commented
You can now install [`inspiredminds/contao-mailer-command`](https://github.com/inspiredminds/contao-mailer-command) in the Contao Managed Edition or [`inspiredminds/symfony-mailer-command-bundle`](https://github.com/inspiredminds/symfony-mailer-command-bundle) for standard Symfony projects in order to get a basic `mailer:send` command.

2022-06-20 18:22 UTC, closed without merging

2022-06-21 06:03 UTC, aschempp commented
Should we make [inspiredminds/contao-mailer-command](https://github.com/inspiredminds/contao-mailer-command) a default in Contao (5)? Would also allow to implement https://github.com/contao/contao-manager/issues/254

2022-06-21 16:57 UTC, leofeyer commented
We can use `mailer:send` from Symfony 6.1 in Contao 5.

2022-06-22 11:38 UTC, Toflar commented
Where did you read that Symfony 6.1 provides this command? @fritzmg's PR https://github.com/symfony/symfony/pull/43687 is still open.

2022-06-23 07:35 UTC, leofeyer commented
You are right, the PR is now targeted on Symfony 6.2.