Add the pagination info to the page title
contao/contao pull request #3886
Opened 2021-12-30 12:34 UTC by leofeyer

Implements #2523

@contao/developers To prevent that the pagination information is added multiple times (e.g. if there are multiple pagination menus on the same page), I am adding the menu with `sprintf()`. This also implies that people will have to add `%s` to the page title of the page to use the feature.

Is this a good approach or would you prefer to add the pagination info automatically?

2021-12-30 12:39 UTC, aschempp requested changes
How about just add an insert tag for the pagination info? Since one has to modify the page title anyway, this way I could actually add the info if and where I want to have it.
I think using `%s` is troublesome, we don't know if that placeholder is intended for the pagination.

2021-12-30 14:35 UTC, fritzmg commented
I find both using an insert tag and `%s` not a good idea. This means you basically have to add `%s` at the end of every page title in the back end where there could be a pagination. I find this rather confusing - and it would look weird in the back end. I think it should be appended automatically, but you should be able to configure it somehow (enable/disable it in the config or even as a page setting).

2021-12-30 16:19 UTC, Toflar commented
I'm not sure this is a good idea from a SEO persoective. I disagree with the author of the original issue.
Indexing a paginated list seems wrong to me in the first place because it changes all the time. Also, as of 4.13 we automatically set the `canonical` link of all `page=` links to the one without. So it wouldn't even be indexed.
If we want to adjust the title then imho it should only happen if the current response context also wants to keep `page` (or whatever) for the current canonical. Totally doable. So either don't do it at all or make it dependent on the canonical settings. The current state does not make sense though :)

2022-01-12 16:54 UTC, leofeyer commented
> Also, as of 4.13 we automatically set the canonical link of all page= links to the one without. So it wouldn't even be indexed.

That's true and it renders the PR redundant. 👍

2022-01-12 16:54 UTC, closed without merging