[WIP] allow to tag service as data container callback
contao/contao pull request #39
Opened 2018-08-30 14:36 UTC by aschempp

still work in progress and untested. Feel free to provide feedback 😊

2018-08-31 08:22 UTC, Toflar commented
This looks really nice!

2018-09-12 06:48 UTC, leofeyer commented on core-bundle/src/EventListener/DataContainerCallbackListener.php
> +    private function getFromDCA(string $table, array $keys)
`: array` can be added IMHO

2018-09-12 06:50 UTC, leofeyer commented
I like this one. Implementation looks good to me, so as soon as you have added the unit tests, this one is ready to merge IMHO.

2018-09-14 07:27 UTC, aschempp commented on core-bundle/src/EventListener/DataContainerCallbackListener.php
> +    private function getFromDCA(string $table, array $keys)
No, it can be `null`, `array` or `callable` (a closure)

2018-09-14 07:28 UTC, leofeyer commented on core-bundle/src/EventListener/DataContainerCallbackListener.php
> +    private function getFromDCA(string $table, array $keys)
Then you should add a phpDoc `@return`. 😉

2018-09-17 06:42 UTC, aschempp commented on core-bundle/src/EventListener/DataContainerCallbackListener.php
> +    private function getFromDCA(string $table, array $keys)
Added in 15bd74688c5c3c3ceb26f201f982159ffd99a458

2018-09-17 06:44 UTC, aschempp commented
Unit tests for the listener are still missing, but everything else added. I was unable to test the alias handling, I'm not sure how this works. An alias cannot have tags, so why is this method needed at all (I've copied it from the `RegisterHookListenersPass`)?

2018-09-20 11:13 UTC, aschempp commented
I've now added all remaining unit tests

2018-09-21 12:30 UTC, ausi requested changes
I proposed some changes to the `DataContainerCallbackListener` in aschempp/contao#1

2018-09-26 05:24 UTC, aschempp commented
I have merged the suggestions of @ausi, I think this is RTM now.

2018-09-26 05:54 UTC, ausi approved these changes

2018-10-09 08:46 UTC, merged

2018-10-09 08:46 UTC, leofeyer commented
Thank you @aschempp.