trigger deprecations when using certain contao.localconfig keys
contao/contao pull request #4006
Opened 2022-01-26 01:02 UTC by m-vo

This makes sure setting deprecated `localconfig` keys via the bundle configuration will actually trigger a deprecation.

see https://github.com/contao/contao/issues/3965#issuecomment-1021503954

2022-01-26 08:36 UTC, ausi commented on core-bundle/src/Resources/contao/library/Contao/Config.php
> +		self::checkForDeprecation($strKey, sprintf('Using "%s(\'%s\', …)"', __METHOD__, $strKey));
```suggestion
		self::checkForDeprecation($strKey, sprintf('Using "%s(\'%s\')"', __METHOD__, $strKey));
```

2022-01-26 08:37 UTC, ausi submitted a review, later dismissed

2022-01-26 09:43 UTC, Toflar submitted a review, later dismissed

2022-01-26 09:49 UTC, bytehead approved these changes, later dismissed

2022-01-26 13:04 UTC, ausi approved these changes

2022-01-30 17:11 UTC, aschempp approved these changes

2022-02-03 14:46 UTC, leofeyer requested changes
I think this is over-engineered. IMHO we should

* keep the deprecation check in the `Config::get()` method;
* not trigger a deprecation in the `Config::set()` method;
* maybe trigger a deprecation in the config tree builder but without adding another public static method to the `Config` class.

2022-02-03 15:10 UTC, ausi commented
> not trigger a deprecation in the `Config::set()` method;

But we already do that in the current version. I don’t think we should remove that, should we?
Related: #3056

2022-02-03 15:13 UTC, leofeyer commented
My bad. Of course we should keep it then.

If we already trigger a deprecation when setting or getting the key, why do we need another deprecation in the config tree at all?

2022-02-03 15:15 UTC, ausi commented
> why do we need another deprecation in the config tree at all?

I think because it would get triggered at container build time and should therefore be seen much more likley by a developer.

2022-02-03 15:20 UTC, leofeyer commented
I see. However, I do not like it very much. The configuration tree should not have to know about expired config keys. Maybe we should use `Config::set()` here instead?

https://github.com/contao/contao/blob/2ba558f74e0183ed2daec842f01198dd89e89b1b/core-bundle/src/DependencyInjection/ContaoCoreExtension.php#L82

2022-02-03 15:30 UTC, ausi commented
> Maybe we should use `Config::set()` here instead?

We could call `Config::get()` there, just to trigger the deprecation warning (without changing $GLOBALS).

2022-02-03 15:57 UTC, m-vo commented
> We could call Config::get() there, just to trigger the deprecation warning (without changing $GLOBALS).

I'm ok with that if you prefer, although I think not using the results of a non-void function and assuming some behavior is way less expressive than just using a function made for this scenario.

2022-02-03 16:00 UTC, leofeyer commented
Yes, if we really have to show the deprecations during the container build, this would be the least invasive change. I still don‘t see any added value though.

2022-02-03 16:03 UTC, m-vo commented
> I still don‘t see any added value though.

https://github.com/contao/contao/issues/3965#issuecomment-1021503954

You won't get any deprecation notices when setting deprecated config keys via the `contao.localconfig`, but IMHO you should. That we did not trigger deprecations like with the other config keys, is due to the fact we're using a variable node here. But that's only an implementation detail.

2022-02-03 16:12 UTC, m-vo commented
Just checked if we could use `Config::get()` but now I remember why I didn't use that. 

This will produce a message like so:

```
Since contao/core-bundle 4.12: Using "Contao\Config::get('enableSearch')" has been deprecated. Use the "contao.search.default_indexer.enable" parameter instead.
```

But it should rather contain the respective config key:
```
-Since contao/core-bundle 4.12: Setting "contao.localconfig.enableSearch" has been deprecated. Use the "contao.search.default_indexer.enable" parameter instead.
```

2022-02-07 17:25 UTC, leofeyer commented
I have created another PR with a different approach: #4076

2022-02-08 09:38 UTC, leofeyer commented
Closed in favor of #4076.

2022-02-08 09:38 UTC, closed without merging