Fixes "Warning: Undefined array key 1" at Inserttags
contao/contao pull request #4034
Opened 2022-02-01 07:15 UTC by xprojects-de

Fixes "Warning: Undefined array key 1" on PHP 8

2022-02-01 07:16 UTC, aschempp requested changes
This code does not do the same as before. The only necessary change should be to use `??` instead of `?:`

2022-02-01 07:26 UTC, xprojects-de commented
Changed and tested. Now i´ts working as expected...

2022-02-02 06:55 UTC, aschempp approved these changes

2022-02-02 16:07 UTC, merged

2022-02-02 16:07 UTC, leofeyer commented
Thank you @xprojects-de.