Fix order of parameters in AsContentElement and AsFrontendModule constructors
contao/contao pull request #4065
Opened 2022-02-03 17:13 UTC by m-vo

Fixes #4055

This PR swaps the first two parameters of the `AsContentElement` and `AsFrontendModule` constructors. This was not released yet, so no BC issue.

Background info: As of PHP8.0 having optional parameters before mandatory ones is deprecated. Here is an explanation why the current code did not trigger a deprecation warning and behaved just like two mandatory parameters: https://github.com/php/php-src/pull/5067#issuecomment-573872903

2022-02-03 17:26 UTC, fritzmg approved these changes, later dismissed

2022-02-04 08:14 UTC, ausi approved these changes, later dismissed

2022-02-04 08:34 UTC, aschempp commented
I would kinda prefer @ausi's solution in https://github.com/contao/contao/issues/4055#issuecomment-1028927805
If I ever write an attribute with a type, I would never write 
```
#AsContentElement("texts", "foobar")
```

The goal should be to work the same as annotatinos did, so to use named paramters (I know we can't enforce that). Either write
```
#AsContentElement(category: 'texts')
```
or write
```
#AsContentElement("foobar", category: 'texts')
```
if you have a type. Making category default null and throw an exception would solve that.

2022-02-04 11:01 UTC, leofeyer commented
@m-vo Will you update this PR accordingly?

2022-02-04 11:12 UTC, ausi commented
I’d prefer something that works so that my IDE shows me if something is missing or what will happen.

IMO only the following two possibilities accomplish that:

```
__construct(string $category, string $type = null, …
__construct(string $type = null, string $category = 'texts',…
```

With `string $category = null` my IDE would suggest that this parameter is nullable and not required (which it is not at runtime then 😕)

2022-02-04 12:41 UTC, leofeyer commented
I‘d be fine with `string $category = 'texts'` as well.

2022-02-04 21:06 UTC, m-vo commented
But then you could omit all parameters and the element would appear in the text category (why text?). I'm ok with that, but I think I would prefer a solution without adding magic.

2022-02-06 10:51 UTC, leofeyer commented
Why don‘t we just make `$type` a required parameter, too?

```php
__construct(string $type, string $category, …
```

The maker bundle will always set the type anyway:

https://github.com/contao/contao/blob/f577f1ebadebefd88eb44177ab4115a80fcad55a/maker-bundle/src/Resources/skeleton/content-element/ContentElement.tpl.php#L18-L20

2022-02-06 11:32 UTC, m-vo commented
> Why don‘t we just make $type a required parameter, too?

In my opinion it's a good thing, that the type is inferred by default, because it promotes a common naming scheme. And I don't want to type it when creating fragments myself. :slightly_smiling_face:

2022-02-06 11:34 UTC, m-vo commented
We should also discuss the usage of the variadic parameter.

2022-02-06 11:35 UTC, fritzmg commented
I usually always end up using

```php
/**
 * @ContentElement(MyContentElement::TYPE, category="texts")
 */
class MyContentElementextends AbstractFrontendModuleController
{
    public const TYPE = 'my_content_element';
}
```

so that I can reference the type in the DCA for example.

2022-02-06 14:32 UTC, m-vo commented
> I usually always end up using
> 
> /**
>  * @ContentElement(MyContentElement::TYPE, category="texts")
>  */

:+1: for constants, that can be automatically refactored. Maybe the FQCN should get the default type in the future? 

Other aspect: We currently use the type to identify templates, but with Twig there is no point in injecting a `Template` in `getResponse()`. So either we build a special render method that, again, uses the type to identify a template or you would explicitly reference a template in `$this->render()` anyways and not need the type at all. This is also coupled to the discussion about template selection in the back end. 

If we want to alter the behavior in Contao 5, we could maybe already prepare this in 4.13 when using attributes.

2022-02-10 16:05 UTC, leofeyer requested changes
As discussed in the Contao call, we want to use `miscellaneous` as default category for both (!) content elements and front end modules. Also, we want to change `array ...$attributes` to `mixed ...$attributes`.

2022-02-10 22:07 UTC, m-vo commented
The changes are now implemented as discussed.

Because we're now in a situation, where it's required to use named arguments to set arbitrary keys, I had to use some trickery in the tests, so that jobs < PHP8 would not result in a syntax error. If there is a better solution, let me know.

2022-02-11 04:06 UTC, ausi commented
> If there is a better solution, let me know.

```php
new AsContentElement(...[
    'type' => 'content_element/text',
    'template' => 'a_template',
    'method' => 'aMethod',
    'renderer' => 'inline',
    'foo' => 'bar',
    'baz' => 42,
]);
```

https://3v4l.org/3mVUg

2022-02-11 04:07 UTC, ausi commented on core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
> +        if (\PHP_VERSION_ID <= 80000) {
```suggestion
        if (\PHP_VERSION_ID < 80000) {
```

PHP 8.0.0 should be supported I guess?

2022-02-11 08:35 UTC, m-vo commented on core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
> +        if (\PHP_VERSION_ID <= 80000) {
Ah yes, my bad.

2022-02-11 09:48 UTC, ausi approved these changes

2022-02-11 11:20 UTC, leofeyer approved these changes

2022-02-11 11:21 UTC, merged

2022-02-11 11:21 UTC, leofeyer commented
Thank you @m-vo.