Do not add the element name to the PHP attribute in the maker bundle
contao/contao pull request #4117
Opened 2022-02-11 17:22 UTC by leofeyer

Fixes #4090

2022-02-11 17:53 UTC, m-vo commented
Looks, good. I think we should omit the type for the annotation as well, though.

And, one other thing I noticed when testing: Should we add `miscellaneous` here, too?
![image](https://user-images.githubusercontent.com/5305677/153643288-753aca10-92b0-40fd-8f8c-b91902895afa.png)

2022-02-14 07:29 UTC, aschempp requested changes
Just requesting changes for what @m-vo already said, the type should also be removed from annotations 😊

2022-02-14 16:09 UTC, leofeyer commented
Types removed in c60bda221faadbc943e340a30f17ea7c46ceed25. The suggested categories are taken from the `$GLOBALS['TL_CTE']` array, so as long as there are no elements in the `miscellaneous` category, it will not show up here.

2022-02-14 16:15 UTC, aschempp approved these changes

2022-02-14 16:18 UTC, merged