Check return type of generateLabelRecord method
contao/contao pull request #4126
Opened 2022-02-14 07:57 UTC by bezin

Fixes #4125

2022-02-14 08:12 UTC, fritzmg requested changes
Before we merge this, I'll check what exactly happens in `generateRecordLabel` with the given DCA.

2022-02-14 08:20 UTC, bezin commented
The registered [label_callback returns an array](https://github.com/oveleon/contao-component-style-manager/blob/2aaec7be9aaafce5b9e13cdfe83505c79213f2c4/src/Resources/contao/dca/tl_style_manager_archive.php#L216-L224) and `showColumns` is not set. 

A l[abel_callback that returns an array is not handled](https://github.com/contao/contao/blob/6d8af7b525f85e790b9edb2b6627354f70019040/core-bundle/src/Resources/contao/classes/DataContainer.php#L1773-L1776) in `generateRecordLabel`. It only depends on `showColumns` being true or not.

2022-02-14 08:24 UTC, fritzmg commented on core-bundle/src/EventListener/DataContainer/RecordPreviewListener.php
> +        $preview = $dc->generateRecordLabel($row, $dc->table);
```suggestion
        $preview = $dc->generateRecordLabel($row, $dc->table);

```

2022-02-14 08:24 UTC, fritzmg approved these changes, later dismissed
`DC_Table::listView` automatically handles labels that are arrays if `showColumns` is not set:

https://github.com/contao/contao/blob/90ea2319099c44862d1607c22cd79a7cc762ffab/core-bundle/src/Resources/contao/drivers/DC_Table.php#L4985-L4989

Therefore the listener must not check for `showColumns` itself.

2022-02-14 08:32 UTC, fritzmg commented on core-bundle/src/EventListener/DataContainer/RecordPreviewListener.php
> +        return (is_array($preview)) ? serialize($preview) : $preview;
```suggestion
        return (\is_array($preview)) ? serialize($preview) : $preview;
```

2022-02-14 08:39 UTC, fritzmg commented
You should run

```
tools/ecs/vendor/bin/ecs check *-bundle/src/Resources/contao --config tools/ecs/config/legacy.php --fix --ansi
```

locally first, before committing ;)

2022-02-14 08:49 UTC, bezin commented
I usually do ;-) All set now.

2022-02-14 08:52 UTC, fritzmg submitted a review, later dismissed

2022-02-14 12:20 UTC, aschempp requested changes
This can't be right. Label callbacks and others are expected to return an array if the data is displayed in a column view. How do we support that now?

2022-02-14 12:49 UTC, bezin commented
> This can't be right. Label callbacks and others are expected to return an array if the data is displayed in a column view. How do we support that now?

We still do? I simply do not check for `showColumns = true` specifically as one may return an array from the label callback without setting `showColumns` to `true`. I use whatever the  generateRecordLabel` method returns now.

2022-02-14 13:18 UTC, fritzmg commented
@aschempp see https://github.com/contao/contao/pull/4126#pullrequestreview-881286439

2022-02-14 15:06 UTC, aschempp reviewed
Ah sorry I somehow thought `generateRecordLabel` would have a string return type 🤦 

However, shouldn't we implode the value like DC_Table does instead of serializing? Or how do we unserialize and correctly handle array values when displaying our undo view?

2022-02-14 15:18 UTC, bezin commented
> However, shouldn't we implode the value like DC_Table does instead of serializing? Or how do we unserialize and correctly handle array values when displaying our undo view?

You have point here: Before this PR, the presence of a label as array values equaled `showColumns = true`, so I [rendered that in a table, as it would be in the listing](https://github.com/contao/contao/blob/6d8af7b525f85e790b9edb2b6627354f70019040/core-bundle/src/Resources/views/Backend/be_undo_label.html.twig#L23-L31). 

However, now this does not apply anymore – hence I would suggest to do check for `showColumns = true` after all and 
1. store a serialized array and display it as tabular data, when `showColumns = true`;
2. implode array data and store as string if `generateRecordLabel` returns an array and `showColumns = false`; or
3. store label as string and render as string if `generateRecordLabel` returns a string.

2022-02-14 16:36 UTC, fritzmg approved these changes, later dismissed

2022-02-15 07:23 UTC, aschempp commented
I would think we should always store the array and render depending on `showColumns` (implode or render columns)?

2022-02-16 13:02 UTC, bezin commented
> I would think we should always store the array and render depending on `showColumns` (implode or render columns)?

I implemented it that way in [947cbff](https://github.com/contao/contao/pull/4126/commits/947cbffdc7381523a59741e688d7862f23106d7f) @aschempp

2022-02-16 14:43 UTC, leofeyer approved these changes

2022-02-16 16:36 UTC, merged

2022-02-16 16:37 UTC, leofeyer commented
Thank you @bezin.