Improve version diff of recursive array data
contao/contao pull request #4296
Opened 2022-03-17 13:20 UTC by aschempp

I'm using https://github.com/m-vo/contao-group-widget here but I think it applies to any recursive array.

**Before:**
<img width="891" alt="Bildschirmfoto 2022-03-17 um 14 15 14" src="https://user-images.githubusercontent.com/1073273/158816568-b423d41d-bb6c-4423-bd04-3d9733498881.png">

**After:**
<img width="889" alt="Bildschirmfoto 2022-03-17 um 14 11 36" src="https://user-images.githubusercontent.com/1073273/158816627-128d3caf-fd5c-4cad-8f1f-f4363a4e7ab6.png">

_Screenshots are not exactly the same content but the same markup_ 😉

2022-03-17 13:25 UTC, Toflar approved these changes

2022-03-17 13:53 UTC, m-vo approved these changes

2022-03-18 15:04 UTC, leofeyer requested changes
You did not test this, did you?

<img width="900" alt="" src="https://user-images.githubusercontent.com/1192057/159028232-4cbd3149-0acb-4ddb-b1cf-6858c40b16c4.png">

2022-03-18 15:16 UTC, leofeyer commented
Also, the change has some strange side-effects:

<img width="901" alt="" src="https://user-images.githubusercontent.com/1192057/159030210-1124cebd-4b55-4942-a37e-82912477cce4.png">

This version diff of a table element looks like this with the changes:

<img width="902" alt="" src="https://user-images.githubusercontent.com/1192057/159030307-c156acb4-a328-4af4-9dd5-8bb5a5bb3c55.png">

2022-10-15 19:06 UTC, closed without merging