Deprecated Cache lib
contao/contao pull request #4329
Opened 2022-03-21 17:17 UTC by Toflar

Marking `Contao/Cache` as deprecated. It's a very simple in-memory cache which is better implemented in your own classes. Persistence was never supported so there's no real point in maintaining this class.
If you need persistence, use `symfony/cache` instead.

2022-03-21 17:19 UTC, aschempp commented
I think we should rewrite the usage of Cache (from https://github.com/contao/contao/pull/4330) in 4.13 to already deprecated it.

2022-03-21 17:20 UTC, Toflar commented
Yeah, I didn't bother because 🤷‍♂️

2022-03-21 22:04 UTC, ausi approved these changes, later dismissed

2022-03-21 22:57 UTC, leofeyer commented on comments-bundle/src/Resources/contao/dca/tl_comments.php
> +		static $cache = array();
This is considered bad practice (see https://twitter.com/s_bergmann/status/1182282457011363842). If we go this way, it should be a static class property. However, I am not convinced about the change.

2022-03-21 22:57 UTC, leofeyer requested changes

2022-03-21 22:57 UTC, leofeyer commented on comments-bundle/src/Resources/contao/dca/tl_comments.php
> +		static $cache = array();
This is considered bad practice (see https://twitter.com/s_bergmann/status/1182282457011363842). If we go this way, it should be a static class property. However, I am not convinced about the change.

2022-03-21 23:12 UTC, leofeyer requested changes
I don‘t see any advantage in removing the class.

2022-03-22 09:18 UTC, aschempp submitted a review, later dismissed

2022-03-22 09:40 UTC, fritzmg approved these changes, later dismissed

2022-04-20 10:00 UTC, leofeyer approved these changes

2022-04-20 10:05 UTC, merged

2022-04-20 10:05 UTC, leofeyer commented
Thank you @Toflar.