Remove useAutoItem and TL_AUTO_ITEM usage
contao/contao pull request #4340
Opened 2022-03-21 22:40 UTC by fritzmg

Removes the option to disable the `auto_item` and also removes the `TL_AUTO_ITEM` usage.

2022-03-21 22:44 UTC, Toflar approved these changes, later dismissed

2022-03-22 16:19 UTC, leofeyer requested changes

2022-03-22 16:19 UTC, leofeyer commented on calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
> +		if ($this->cal_readerModule > 0  && null !== Input::get('auto_item', false, true))
```suggestion
		if ($this->cal_readerModule > 0 && isset($_GET['auto_item']))
```

2022-03-22 16:19 UTC, leofeyer commented on core-bundle/src/Resources/contao/controllers/FrontendIndex.php
> +		if ($objPage->requireItem && null === Input::get('auto_item', false, true))
```suggestion
		if ($objPage->requireItem &&  !isset($_GET['auto_item']))
```

2022-03-22 16:19 UTC, leofeyer commented on faq-bundle/src/Resources/contao/modules/ModuleFaqList.php
> +		if ($this->faq_readerModule > 0 && null !== Input::get('auto_item', false, true))
```suggestion
		if ($this->faq_readerModule > 0 &&  isset($_GET['auto_item']))
```

2022-03-22 16:19 UTC, leofeyer commented on news-bundle/src/Resources/contao/modules/ModuleNewsArchive.php
> +		if ($this->news_readerModule > 0 && null !== Input::get('auto_item', false, true))
```suggestion
		if ($this->news_readerModule > 0 &&  isset($_GET['auto_item']))
```

2022-03-22 16:19 UTC, leofeyer commented on news-bundle/src/Resources/contao/modules/ModuleNewsList.php
> +		if ($this->news_readerModule > 0 && null !== Input::get('auto_item', false, true))
```suggestion
		if ($this->news_readerModule > 0 &&  isset($_GET['auto_item']))
```

2022-03-22 22:16 UTC, aschempp submitted a review, later dismissed

2022-03-22 22:16 UTC, aschempp commented on core-bundle/src/Resources/contao/controllers/FrontendIndex.php
> +		if ($objPage->requireItem && !isset($_GET['auto_item']))
I would revert these changes, they become obsolete (and will cause a merge conflict) with https://github.com/contao/contao/pull/4304

2022-03-27 11:51 UTC, ausi submitted a review, later dismissed
We could make `Config::get('useAutoItem')` to always return `true`. This might make it easier for extension developers to be compatible with 4.13 and 5.0.

2022-03-28 07:22 UTC, fritzmg commented
You could also use `Config::get('useAutoItem') ?? true` in your extension.

2022-04-06 08:38 UTC, leofeyer approved these changes

2022-04-06 08:42 UTC, merged

2022-04-06 08:42 UTC, leofeyer commented
Thank you @fritzmg.