Replace Chosen.js with Choices.js
contao/contao pull request #4363
Opened 2022-03-22 17:03 UTC by aschempp

2022-03-22 17:14 UTC, Toflar approved these changes, later dismissed

2022-04-21 13:52 UTC, Toflar approved these changes, later dismissed

2022-04-21 14:04 UTC, leofeyer requested changes
There are some minor issues left that need to be resolved.

### Box shadow

<img width="247" alt="" src="https://user-images.githubusercontent.com/1192057/164474421-bed18616-796e-4d61-9aaa-9ae7189fe4ea.png">

In Safari 15.4 on macOS 12.3.1, a visible box shadow remains after using the select menu.

### Visible separator

![](https://user-images.githubusercontent.com/1192057/164475132-13a0e821-0cc9-4905-898d-82d37f4cc04e.jpg)

If there is no search field, a visual separator is missing between the currently selected option and the options dropdown. This is how it looked with Chosen:

2023-01-10 12:28 UTC, leofeyer commented
I was able to fix the two issues myself, however, I have found more issues while doing so. 😢 

<img width="463" alt="" src="https://user-images.githubusercontent.com/1192057/211551611-79da6507-91c8-4212-8450-b8218a6db954.png">

And the tab outline does not work.

2023-10-23 06:37 UTC, doishub commented
As mentioned at the conference, this library may be able to help:
https://tom-select.js.org/

2023-10-23 15:56 UTC, leofeyer commented
Yes, it is. I‘m going to take a look at it. 👍

2023-11-24 12:48 UTC, doishub commented
Cool, we've had very good experiences with it so far. In one of our extensions, for example, we were able to display the page tree in a structured way in the select or similar. 

If you still have questions, I can perhaps help you with the answer 😉

2024-12-20 00:02 UTC, zoglo commented
I've stumbled across https://www.npmjs.com/package/slim-select which is an active repository and may have the the same if not more possibilities as the current implementation :smile:

2024-12-20 23:27 UTC, zoglo commented
Going to continue this PR with:

* https://github.com/aschempp/contao/pull/13 
which will need to be tested with
* https://github.com/contao-components/choices/pull/1

to migrate to v11 of [Choices-js](https://github.com/Choices-js/Choices).

Should I open a new PR or just ping @aschempp (cause it's his work, me just migrating and working in the background :D)

2024-12-21 18:44 UTC, zoglo commented
The mentioned two PRs are ready to review.

There is only the english translations missing that need to be added as data-attributes to the body I guess?
It's about how to add these values and read them for i18n:

```
    loadingText: 'Loading...',
    noResultsText: 'No results found',
    noChoicesText: 'No choices to choose from',
    itemSelectText: 'Press to select',
    uniqueItemText: 'Only unique values can be added',
    customAddItemText: 'Only values matching specific conditions can be added',
```

Should we place these as data-attributes in the body somewhere? @leofeyer @aschempp ?

2024-12-23 12:33 UTC, zoglo commented
Continuing this in #7824

2025-01-13 15:50 UTC, zoglo commented
Superseded by #7824

2025-01-13 15:50 UTC, closed without merging