Remove countries.php and getCountries hook
contao/contao pull request #4563
Opened 2022-04-28 13:47 UTC by ausi

2022-04-28 15:57 UTC, Toflar requested changes
I think this one is worth mentioning in the UPGRADE.md

2022-04-29 07:18 UTC, ausi commented
> I think this one is worth mentioning in the UPGRADE.md

Done in 86976aa410d52c084c311584823bed00e1c36d42

2022-04-29 07:51 UTC, m-vo approved these changes, later dismissed

2022-04-29 13:34 UTC, Toflar approved these changes, later dismissed

2022-04-29 14:04 UTC, leofeyer approved these changes

2022-04-29 14:09 UTC, merged

2022-04-29 14:09 UTC, leofeyer commented
Thank you @ausi.