Remove TL_CRON usage from comments-bundle
contao/contao pull request #4635
Opened 2022-05-09 15:03 UTC by fritzmg

See https://github.com/contao/contao/issues/4513

2022-05-10 06:37 UTC, ausi commented on comments-bundle/src/Cron/PurgeSubscriptionsCron.php
> +        }
```suggestion
        $this->logger?->info('Purged the unactivated comment subscriptions');
```

2022-05-10 06:37 UTC, ausi commented on comments-bundle/src/Resources/contao/classes/Comments.php
> +		trigger_deprecation('contao/comments-bundle', '5.0', 'Calling "%s::%s()" has been deprecated and will no longer work in Contao 6.0.', __CLASS__, __METHOD__);
```suggestion
		trigger_deprecation('contao/comments-bundle', '5.0', 'Calling "%s()" has been deprecated and will no longer work in Contao 6.0.', __METHOD__);
```

2022-05-10 14:50 UTC, ausi approved these changes, later dismissed

2022-05-11 07:50 UTC, m-vo approved these changes, later dismissed

2022-05-11 08:00 UTC, Toflar submitted a review, later dismissed

2022-05-11 09:47 UTC, ausi approved these changes, later dismissed

2022-05-13 06:40 UTC, aschempp approved these changes, later dismissed

2022-05-13 14:19 UTC, leofeyer requested changes
The changes are OK but the comments bundle does not have unit tests set up, so either you set them up or you remove the test class again.

2022-05-13 15:35 UTC, leofeyer commented
You will also have to add a `phpunit.xml.dist` file in the bundle folder, adjust the workflow file and add the bundle to the list of split bundles that are tested in the CI. Just adding it in the root `phpunit.xml.dist` file is not enough, I‘m afraid.

2022-05-19 12:08 UTC, fritzmg commented
@leofeyer should be RTM.

2022-05-19 18:02 UTC, m-vo submitted a review, later dismissed

2022-05-19 22:26 UTC, ausi submitted a review, later dismissed

2022-05-20 08:05 UTC, leofeyer requested changes

2022-05-20 08:05 UTC, leofeyer commented on comments-bundle/tests/Cron/PurgeSubscriptionsCronTest.php
> +namespace Contao\CommentsBundle\Tests\EventListener;
```suggestion
namespace Contao\CommentsBundle\Tests\Cron;
```

The namespace seems to be wrong.

2022-05-20 09:11 UTC, ausi approved these changes

2022-05-20 09:45 UTC, leofeyer approved these changes

2022-05-20 09:45 UTC, merged

2022-05-20 09:45 UTC, leofeyer commented
Thank you @fritzmg.