Make individual template more flexible
contao/contao pull request #4665
Opened 2022-05-12 14:35 UTC by doishub

Currently, the defined values must always be traversed with a foreach or similar. For more flexibility I would rather pass the data array in the following structure. This way I would have direct access to my keys and could use a more complex dom structure in my template if needed.

We could also consider passing the flattened array in addition and keeping the old structure as well?

2022-05-12 14:39 UTC, doishub commented
👀 https://community.contao.org/de/showthread.php?82955-Individuelles-Template-%E2%80%93-Werte-ausgeben

2022-05-12 17:44 UTC, m-vo commented
@ausi Is this intentional or should we consider this a bug? :see_no_evil: 

I would have expected the key value pairs from the back end to end up in the template like `['key1' => 'value2', 'key2' => 'value2']` but maybe I'm missing something.

2022-05-12 17:46 UTC, m-vo commented on core-bundle/src/Controller/ContentElement/TemplateController.php
> +        );
```suggestion
        $data = StringUtil::deserialize($model->data, true);

        $template->data = array_combine(
            array_column($data, 'key'),
            array_column($data, 'value'),
        );
```

2022-05-12 18:08 UTC, fritzmg commented
> I would have expected the key value pairs from the back end to end up in the template like ['key1' => 'value2', 'key2' => 'value2'] but maybe I'm missing something.

Same here. I assumed this was the case (never really looked at the implementation 🙈) until I saw the thread on the forum.

2022-05-13 05:59 UTC, aschempp commented
I would actually expect it to be `$this->key` like any other template property? 😬

2022-05-13 06:06 UTC, doishub commented
> I would actually expect it to be $this->key like any other template property? 😬

I could imagine that the idea of the key was intended more as a label. This would explain the initial foreach 😁

`Name` -> `Kevin`
`Nachname` -> `Jones`

2022-05-13 07:01 UTC, ausi commented
> Is this intentional or should we consider this a bug? 🙈

I think it was intentional, as the key/value wizard can be used with duplicate keys I thought passing the data as it is made most sense.

Because of backwards compatibility I don’t think we can change the structure of how `->data` looks like. 
But we could additionally set the values on the template data itself like so:

```php
foreach ($template->data as ['key' => $key, 'value' => $value]) {
    $template->$key = $value;
}
```

This would then work with `$this->key` as @aschempp expected it and it would be backwards compatible.
Not sure if I like that though.

2022-05-13 07:23 UTC, m-vo commented
> This would then work with $this->key as @aschempp expected it and it would be backwards compatible.
Not sure if I like that though.

I'm very :-1: on this one. In the new controllers it was a major goal to remove all possible variable collisions from the context. If someone would for instance set a key `attributes` or `headline`, there won't be a `HtmlAttributes` instance or a headline array in the context anymore and the content element base template would probably break.

I think I'd favor having a second variable set like so and would introduce this change as a bugfix in 4.13:
```php
$data = StringUtil::deserialize($model->data, true);

$template->data = $data;
$template->keys = array_combine(array_column($data, 'key'), array_column($data, 'value'));
```
This way you can access all duplicates as well as a simplified output:

```twig
{% for datum in data|filter(d.key == 'foo') % }
    {{ data.value }}
{% endfor %}

{{ keys.foo }}
```

2022-05-13 07:35 UTC, m-vo commented
By the way: another reason why collections must always be scoped is that you otherwise cannot iterate them. :upside_down_face:

2022-05-17 08:55 UTC, doishub commented
I have adopted @m-vo `s  suggestion for now.

2022-05-17 08:57 UTC, fritzmg commented
One question remains: should we backport this to ~~4.9~~ 4.13?

2022-05-17 08:58 UTC, doishub commented
+1 Should not cause any problems from my point of view.

2022-05-17 09:08 UTC, m-vo commented
> One question remains: should we backport this to 4.9?

IMHO yes. But 4.13, because this element doesn't exist in 4.9 yet. :slightly_smiling_face:

2022-05-17 09:47 UTC, leofeyer commented
We can adjust the `ce_template.html5` template if we make sure that custom versions of it still work, which is the case IIRC. Therefore I vote for applying the initial changes again:

```php
  <?php foreach ($this->keys as $key => $value): ?>
    <dl>
      <dt><?= $key ?></dt>
      <dd><?= $value ?></dd>
    </dl>
  <?php endforeach; ?>
```

2022-05-17 09:51 UTC, m-vo commented
Good idea to also adjust the default template. :+1:

2022-05-17 09:53 UTC, doishub commented
Makes sense. Done. 🙃

2022-05-17 10:01 UTC, leofeyer commented on core-bundle/src/Controller/ContentElement/TemplateController.php
> +        );
```suggestion
        $data = StringUtil::deserialize($model->data, true);

        $template->keys = array_combine(
            array_column($data, 'key'),
            array_column($data, 'value')
        );

        // Backwards compatibililty
        $template->data = $data;
```

2022-05-17 10:07 UTC, leofeyer approved these changes, later dismissed

2022-05-17 10:08 UTC, m-vo requested changes
This should go into 4.13.

2022-05-17 10:08 UTC, leofeyer commented
I‘ve just realized that this is a PR for Contao 5. We do not need a BC layer at all then. Or is the PR supposed to be rebased on the `4.13` branch?

2022-05-17 10:30 UTC, m-vo approved these changes

2022-05-17 10:32 UTC, ausi approved these changes

2022-05-17 14:18 UTC, merged

2022-05-17 14:18 UTC, leofeyer commented
Thank you @doishub.