Remove the deprecated FORM_FIELDS feature
contao/contao pull request #4740
Opened 2022-05-26 08:54 UTC by leofeyer

We should probably merge this before we merge #4734.

2022-05-26 08:56 UTC, Toflar submitted a review, later dismissed

2022-05-27 11:34 UTC, ausi requested changes

2022-05-27 11:34 UTC, ausi commented on core-bundle/src/Resources/contao/classes/DataContainer.php
>  			if ($objWidget->submitInput() && (\in_array($this->strInputName, $paletteFields) || Input::get('act') == 'overrideAll'))
I tested the current state of this PR and it changes behavior and creates errors like `must be of type array|object, null given`.

The `\in_array($this->strInputName, $paletteFields)` check doesn’t make any sense now with these changes, does it? `row()` will anyways be called only for fields that are in the current palette, so I’m pretty sure this check returns `true` every time.

The old deprecation noted: _“Make sure to always submit at least an empty string in your widget.”_ this to me implies that we wanted to switch to a null check here like so:

```suggestion
			if ($objWidget->submitInput() && Input::post($this->strInputName) !== null)
```

With this change everything works again in my test.

2022-05-30 10:56 UTC, leofeyer commented
@ausi I have merged your suggestion in c9a8e7192ae96c7a7d50966b355f2b553cd11c69 and removed the leftover `$paletteFields` variable in 7781e2ddd0cc90a73a92ff81283ccaf60e10c86b.

2022-05-30 10:58 UTC, ausi commented on core-bundle/src/Resources/contao/classes/DataContainer.php
> +		if ((Input::post('FORM_SUBMIT') == $this->strTable) && $objWidget->submitInput() && Input::post($this->strInputName) !== null)
```suggestion
		if (Input::post('FORM_SUBMIT') == $this->strTable && $objWidget->submitInput() && Input::post($this->strInputName) !== null)
```

2022-05-30 10:59 UTC, ausi approved these changes, later dismissed

2022-05-30 11:00 UTC, ausi approved these changes

2022-05-30 11:03 UTC, merged