Make sure `eval.rte` is a string
contao/contao pull request #4878
Opened 2022-06-27 09:25 UTC by fritzmg

If some DCA erroneously defined something like

```php
'eval' => ['rte' => true]  
```

the `RelLightboxMigration` will currently fail with 

```
TypeError:
substr() expects parameter 1 to be string, bool given

  at vendor/contao/core-bundle/src/Migration/Version413/RelLightboxMigration.php:96
```

This PR makes the migration more robust by checking whether the value is actually a string.

2022-06-27 09:30 UTC, ausi submitted a review, later dismissed

2022-06-27 10:57 UTC, leofeyer commented
I don‘t understand why we have to make up for configuration errors? If you misconfigure the app, it will trigger an error. And that is a good thing, otherwise you wouldn‘t know that you did something wrong. 🤷‍♂️

2022-06-27 13:07 UTC, m-vo commented
I also think we should not fix this. The [docs](https://docs.contao.org/dev/reference/dca/fields/#evaluation) state it should be a `string` - why should this ever be a boolean?

2022-06-27 13:24 UTC, fritzmg commented
> I don‘t understand why we have to make up for configuration errors?

We want migrations to be as robust as possible.

> And that is a good thing, otherwise you wouldn‘t know that you did something wrong. 🤷‍♂️

In this particular instance the Contao user was not able to figure out the source of the problem, as the error message won't help you find the the DCA adjustment.

> why should this ever be a boolean?

As mentioned in the description of this PR, this can happen if you (or an extension) erroneously set `eval.rte` to something other than a string.

2022-06-27 16:42 UTC, ausi commented
> > I don‘t understand why we have to make up for configuration errors?
> 
> We want migrations to be as robust as possible.

Agree. Migrations should be as defensive as possible IMO. They might run in very odd environments and should not fail for things like a wrong type somewhere in a DCA config.

2022-06-28 13:47 UTC, leofeyer requested changes

2022-06-28 13:47 UTC, leofeyer commented on core-bundle/src/Migration/Version413/RelLightboxMigration.php
> +                $rte = $fieldConfig['eval']['rte'] ?? '';
```suggestion
                $rte = $fieldConfig['eval']['rte'] ?? null;
```

This way the `is_string()` check will already return false and `strpos()` will never be called for non-string values.

2022-06-28 14:03 UTC, leofeyer approved these changes

2022-06-28 14:03 UTC, merged

2022-06-28 14:03 UTC, leofeyer commented
Thank you @fritzmg.