Use response object in Ajax::executePostActions
contao/contao pull request #4933
Opened 2022-07-01 14:37 UTC by fritzmg

This gets rid of the last remaining `header()` call (after #4930 is merged upstream), apart from the maintenance mode in the entry points and in `NativeHeaderStorage`. This should allow us to deprecate and disable the `MergeHttpHeadersListener` (we can probably only remove it in Contao 6.0).

2022-07-01 14:38 UTC, fritzmg commented
On second thought: should these changes may be go into 4.13 instead?

2022-07-05 11:40 UTC, aschempp requested changes

2022-07-05 11:40 UTC, aschempp commented on core-bundle/src/Resources/contao/classes/Ajax.php
> +		;
this is unnecessary because it is already the default for all responses. I think we can just drop this line and not change anything else...

2022-07-05 11:58 UTC, fritzmg commented
Changed to just removing the `header` (see https://github.com/contao/contao/pull/4933#discussion_r913699214) and rebased to 4.13. I did not rebase to 4.9 as we fetch the character set from `Config::get('characterSet')` there and that could in theory really be different from the default response character set.

2022-07-05 22:16 UTC, ausi approved these changes

2022-07-06 06:35 UTC, aschempp approved these changes

2022-07-06 07:03 UTC, Toflar approved these changes

2022-07-06 07:54 UTC, leofeyer commented
Thank you @fritzmg.

2022-07-06 07:59 UTC, merged