Fix default callback order
contao/contao pull request #4940
Opened 2022-07-03 09:57 UTC by fritzmg

Fixes #1795

With this change tagged callbacks with a priority of `0` will be inserted _after_ pre-existing callbacks of the same priority.

2022-07-03 10:24 UTC, m-vo submitted a review, later dismissed

2022-07-03 13:06 UTC, ausi submitted a review, later dismissed

2022-07-04 13:51 UTC, leofeyer requested changes
Changes look good, however, you forgot to document the BC breaks in the `UPGRADE.md` file.

2022-07-05 06:58 UTC, aschempp approved these changes, later dismissed

2022-07-06 09:31 UTC, leofeyer approved these changes, later dismissed

2022-07-06 09:31 UTC, leofeyer commented
Thank you @fritzmg.

2022-07-06 09:31 UTC, leofeyer approved these changes

2022-07-06 09:34 UTC, merged