Stop using utf8_decode() and utf8_encode()
contao/contao pull request #5011
Opened 2022-07-20 07:53 UTC by fritzmg

Backport of https://github.com/contao/contao/pull/4829 to 4.9 to fix the CI. See also https://github.com/contao/contao/pull/4841

2022-07-20 09:08 UTC, fritzmg commented
I am at a loss here - why is the result of `StringUtil::convertEncoding` in 4.9 different than in 4.13 - even though they are exactly the same (now)?

2022-07-27 11:50 UTC, m-vo commented
> I am at a loss here - why is the result of `StringUtil::convertEncoding` in 4.9 different than in 4.13 - even though they are exactly the same (now)?

The issue happens because the "substitute character" gets set to `none` before running this test - it is `0x63` in the upstream version.

This happens in `Patchwork\Utf8\Bootup::initMbstring()` where for some reason this default is hardcoded:

```php
if (extension_loaded('mbstring')) {
    // […]

    if ('none' !== strtolower(mb_substitute_character())) {
        mb_substitute_character('none');
    }
}
```

To fix the issue we could add a `mb_substitute_character(0x3F);` before the test to make sure the output is the same everywhere. (Then there will be another test case failing, but this just needs to be adjusted to match the upstream version as well).

2022-07-27 12:51 UTC, fritzmg commented
@m-vo thank you for the analysis, PR updated accordingly :)

2022-07-27 13:03 UTC, m-vo approved these changes, later dismissed

2022-08-10 15:16 UTC, ausi submitted a review, later dismissed

2022-08-11 10:02 UTC, leofeyer requested changes
Why is it necessary to add a class property that is set and reset for every test? The `mb_substitute_character()` function is only called in one single method.

2022-08-11 10:18 UTC, leofeyer approved these changes

2022-08-11 10:18 UTC, merged

2022-08-11 10:18 UTC, leofeyer commented
Thank you @fritzmg.