Allow null for PaletteManipulator parent
contao/contao pull request #5032
Opened 2022-07-24 09:03 UTC by fritzmg

There are palettes that do not contain any legends, e.g. `tl_files`. If you want to add a field to that legend via the `PaletteManipulator` you currently have to do either of these methods:

```php
// The parent is null but PaletteManipulator::applyFallback will add the field to the end
PaletteManipulator::create()
    ->addField('groups', null)
    ->applyToPalette('default', 'tl_files')
;
```

```php
// The palette "foobar" does not exist but PaletteManipulator::applyFallback will add the field to the end
PaletteManipulator::create()
    ->addField('groups', 'foobar')
    ->applyToPalette('default', 'tl_files')
;
```

Since it is possible (and necessary) to define the `$parent` as `null`, this PR fixes the type hint in the doc. And since it is not necessary to define a parent the argument can be omitted altogether.

It's important to merge this upstream to `5.0` as there you _must_ define a not null `$parent`, otherwise you get the following error:

```
TypeError:
Contao\CoreBundle\DataContainer\PaletteManipulator::addField(): Argument #2 ($parent) must be of type array|string, null given, called in vendor\fritzmg\contao-file-access\src\DataContainer\FilesCallbacks.php on line 34

  at vendor\contao\contao\core-bundle\src\DataContainer\PaletteManipulator.php:57
  at Contao\CoreBundle\DataContainer\PaletteManipulator->addField('groups', null)
```

To circumvent this you would have to apply option no. 2 from above - but having to pass a legend that does not exist only to force the fallback (since there is no valid legend to begin with) makes no sense.

2022-07-25 07:35 UTC, bytehead submitted a review, later dismissed

2022-07-27 10:21 UTC, m-vo submitted a review, later dismissed

2022-08-03 05:21 UTC, aschempp requested changes
I don't think we should have a default value of `null` since the would lead people to not add the value. Also I'm unsure this is even necessary, since you probably should use a field as parent to place the item, instead of a palette?

2022-08-03 06:33 UTC, fritzmg commented
> I don't think we should have a default value of null since the would lead people to not add the value.

If I don't care about the position of a legend or field or I always want to add the legend or field at the end of the palette then I do not need to provide a value.

> Also I'm unsure this is even necessary, since you probably should use a field as parent to place the item, instead of a palette?

You mean in case of `tl_files` I should choose `meta` for example? But that would put the field not at the end of the palette anymore if another palette manipulation added another field after `meta` as well.

2022-08-10 06:18 UTC, aschempp commented
> If I don't care about the position of a legend or field or I always want to add the legend or field at the end of the palette then I do not need to provide a value.

Yes, but if you want to append then you need to provide the third argument anyway, because the default is "after". We could allow null value (instead of anything or empty string, since the value is ignored in append mode), but it sure must not be a default value.


> You mean in case of `tl_files` I should choose `meta` for example? But that would put the field not at the end of the palette anymore if another palette manipulation added another field after `meta` as well.

That is true. But it would not be at the end either if another field is added to the end. So you can't really control that anyway 😉

2022-08-10 07:11 UTC, fritzmg commented
> Yes, but if you want to append then you need to provide the third argument anyway, because the default is "after".

No, the third parameter is (currently at least) irrelevant, if the second parameter is `null` or a non-existent field or legend. The output will always be the same (it's appended to the last legend or at the end).

2022-08-10 08:17 UTC, ausi approved these changes, later dismissed

2022-08-10 14:45 UTC, leofeyer commented
> It's important to merge this upstream to `5.0` as there you _must_ define a not null `$parent`, otherwise you get the following error:

Please create a separate PR for Contao 5 then.

2022-08-10 15:02 UTC, fritzmg commented
> Please create a separate PR for Contao 5 then.

Done: https://github.com/contao/contao/pull/5111

2022-08-10 15:18 UTC, ausi approved these changes

2022-08-11 10:04 UTC, leofeyer commented
Thank you @fritzmg.

2022-08-11 10:05 UTC, merged