Add group_callback and label_callback to DC_Folder
contao/contao pull request #511
Opened 2019-06-07 20:13 UTC by markotodic

Invoke defined callbacks on folder label creation (group_callback)
Invoke defined callbacks on file label/thumbnail creation (label_callback)

2019-06-08 09:53 UTC, ausi commented on core-bundle/src/Resources/contao/drivers/DC_Folder.php
> +            if (\is_array($GLOBALS['TL_DCA']['tl_files']['list']['label']['group_callback']))
`tl_files` should not be hardcoded here.

```suggestion
            if (\is_array($GLOBALS['TL_DCA'][$this->strTable]['list']['label']['group_callback']))
```

2019-06-10 09:20 UTC, ausi commented on core-bundle/src/Resources/contao/drivers/DC_Folder.php
> +            $objFolder = FilesModel::findByPath($currentFolder);
We should probably check for `$this->blnIsDbAssisted` here.

```suggestion
            $objFolder = $this->blnIsDbAssisted ? FilesModel::findByPath($currentFolder) : null;
```

2019-06-14 15:41 UTC, markotodic commented
@leofeyer do I do something about AppVeyor fail or it is up to you to resolve? As you can see I just commited change @ausi suggested.

2020-06-19 13:57 UTC, leofeyer requested changes

2020-06-19 13:57 UTC, leofeyer commented on core-bundle/src/Resources/contao/drivers/DC_Folder.php
> +                list($strFileNameEncoded, $thumbnail) = $this->$strClass->$strMethod($strFileNameEncoded, $thumbnail, $objFile, $protected, $this);
I would prefer not to return anything here and modify the values via reference instead.

2020-06-19 13:57 UTC, leofeyer commented on core-bundle/src/Resources/contao/drivers/DC_Folder.php
> +            $strFolderLabel = "<strong>$strFolderNameEncoded</strong>";
```suggestion
			$strFolderLabel = '<strong>' . $strFolderNameEncoded . '</strong>';
```

2020-06-19 13:57 UTC, leofeyer commented on core-bundle/src/Resources/contao/drivers/DC_Folder.php
> +            $objFolder = $this->blnIsDbAssisted ? FilesModel::findByPath($currentFolder) : null;
It seems you are never using `$objFolder` in this method?

2020-10-05 11:01 UTC, aschempp commented
@markotodic can you finish this pull request?

2021-11-17 06:45 UTC, closed without merging