Allow null for PaletteManipulator parent
contao/contao pull request #5111
Opened 2022-08-10 15:01 UTC by fritzmg

#5032 for Contao 5.0.

2022-08-14 17:52 UTC, ausi submitted a review, later dismissed

2022-08-15 05:41 UTC, leofeyer requested changes

2022-08-15 05:41 UTC, leofeyer commented on core-bundle/src/DataContainer/PaletteManipulator.php
> +    public function addLegend(string $name, array|string $parent = null, string $position = self::POSITION_AFTER, bool $hide = false): self
```suggestion
    public function addLegend(string $name, array|string|null $parent = null, string $position = self::POSITION_AFTER, bool $hide = false): self
```

2022-08-15 05:41 UTC, leofeyer commented on core-bundle/src/DataContainer/PaletteManipulator.php
> +    public function addField(array|string $name, array|string $parent = null, string $position = self::POSITION_AFTER, \Closure|array|string|null $fallback = null, string $fallbackPosition = self::PO
```suggestion
    public function addField(array|string $name, array|string|null $parent = null, string $position = self::POSITION_AFTER, \Closure|array|string|null $fallback = null, string $fallbackPosition = self::POSITION_APPEND): self
```

2022-08-15 11:21 UTC, ausi approved these changes

2022-08-17 12:22 UTC, leofeyer commented
<img width="333" alt="" src="https://user-images.githubusercontent.com/1192057/185117287-1143d5f7-ca74-4672-a858-b002896fcb35.png">

What am I supposed to review? 😄 I guess the changes have already been merged upstream on Monday.

2022-08-17 12:26 UTC, fritzmg commented
Ah yes, did not realise. Also did not know these changes were able to be merged upstream :) (that's why I did the separate PR for 5.0 in the first place). Closing then.

2022-08-17 12:26 UTC, closed without merging