Introduce MemberActivationMailEvent
contao/contao pull request #5116
Opened 2022-08-10 21:36 UTC by fritzmg

Within `ModuleRegistration` of the `contao/core-bundle` we still have implementations specific to `contao/newsletter-bundle`. This is because we want to provide an additional `##channels##` simple token for the activation email text when newsletter subscriptions are enabled in the registration module. And currently there is no way to manipulate the email message or the provided simple tokens for the email message.

This PR introduces a `MemberActivationMailEvent` with which you can add additional simple tokens for the activation email. You can also change the subject of the email or the whole text - or even prevent sending the activation mail (through `OptInToken::send`) altogether. 

The latter would be useful for `terminal42/notification_center` for example which allows you to send the activation link separately - and currently the Notification Center disables `reg_enable` of the module as a work around, so that the activation email is not sent. With this new event the Notification Center can extract the already provided tokens from the event and provide them in their own notification while also preventing the default email from being sent.

2022-08-12 10:06 UTC, aschempp reviewed
shouldn't we rather not send the email if the event (propagation) is stopped (instead of sendOptInToken)?

2022-08-12 10:45 UTC, fritzmg commented
> shouldn't we rather not send the email if the event (propagation) is stopped (instead of sendOptInToken)?

Hmm, you might still want to be able to collect all simple tokens from all registered event listeners. Imagine if the Notification Center stops propagation - but is executed before the Newsletter's listener. Then the `channels` simple token would be missing. Of course the Notification Center will set a very low priority on its own listener so it is more likely to be the last decider. However I still feel like the decision to send or not should be independent from the event's propagation.

2022-10-26 13:08 UTC, fritzmg commented
/cc @Toflar (regarding new NC implementation)

2022-10-26 13:11 UTC, Toflar commented
Will be 4.13 compatible so this isn't of great use for me just yet 😓

2022-10-26 13:15 UTC, fritzmg commented
Yes, but I meant in principle. It's not just for the NC anyway - see also the issue with the newsletter-bundle.

2022-10-28 09:08 UTC, Toflar requested changes
I think the event can be improved :)

2022-10-28 09:08 UTC, Toflar commented on core-bundle/src/Event/MemberActivationMailEvent.php
> +    public function setSendOptInToken(bool $sendOptInToken): self
Can we not use setters and getters here but be more speaking?

* disableSendingTheOptInToken(): self
* enableSendingTheOptInToken(): self
* shouldSendOptInToken(): bool

2022-10-28 09:08 UTC, Toflar commented on core-bundle/src/Event/MemberActivationMailEvent.php
> +    public function setSimpleToken(string $token, string $value): self
Can we have an `addSimpleToken(string $key, string $value)`?

2022-10-28 09:08 UTC, Toflar commented on newsletter-bundle/src/EventListener/MemberActivationMailListener.php
> +        $event->setSimpleToken('channels', implode("\n", $channels));
This place is where you'd use `addSimpleToken()`.

2022-10-28 09:08 UTC, Toflar commented on core-bundle/src/Event/MemberActivationMailEvent.php
> +    public function setSimpleToken(string $token, string $value): self
And a `removeSimpleToken(string $key)`?

2022-10-31 08:24 UTC, Toflar submitted a review, later dismissed
❤️

2023-01-03 11:19 UTC, leofeyer approved these changes

2023-01-03 11:19 UTC, leofeyer commented
Thank you @fritzmg.

2023-01-03 11:22 UTC, merged