Fixed filter options with options callback
contao/contao pull request #5265
Opened 2022-09-12 07:25 UTC by aschempp

This line in DC_Table has two problems:
 1. sorting the options by callback makes no sense, because the list it later sorted by label (I guess that was added later)
 2. this line causes options to be removed if they are not returned by the options callback. For example if you have some "leftover" values you can never filter for them even though they exist in the database.

2022-09-12 08:06 UTC, leofeyer commented
How can we reproduce the issue before the fix?

2022-09-12 13:55 UTC, aschempp commented
have a table with select options filter, and an options_callback that returns nothing (or not all options from the DB)

2022-09-12 15:39 UTC, leofeyer requested changes
I‘m sorry, but just as in #4776, I don‘t think we should remove things that have been in the code for more than 11 years just because "you guess that something has been added later" or you are "pretty sure that something does not work".

If you want to remove things like that, please provide a detailed reproduction case and explain how your change fixed the issue and how you made sure that your change does not have unintended side-effects. Otherwise I cannot merge PRs like this one. 🤷‍♂️

2022-09-13 07:33 UTC, aschempp commented
I don't understand your problem. The code has a description that says "sort by options_callback". However, a few lines below, the options are sorted **again** for the label. I'm pretty sure this label sorting has been added later, otherwise the now removed line never made sense. Also, you can clearly see the line will remove any option that does not exist in the options_callback, which obviously is a problem?

2022-12-13 06:58 UTC, aschempp commented
@leofeyer just as https://github.com/contao/contao/pull/4776 could you please look into this again? 😜

2022-12-15 15:35 UTC, ausi submitted a review, later dismissed

2022-12-15 15:38 UTC, m-vo approved these changes, later dismissed

2022-12-15 15:50 UTC, ausi approved these changes

2022-12-15 15:51 UTC, fritzmg approved these changes

2022-12-15 15:57 UTC, leofeyer approved these changes

2022-12-15 15:57 UTC, merged