Fix a potential error when trying to log the deleted record
contao/contao pull request #5336
Opened 2022-10-04 09:32 UTC by qzminski

I've caught this error in Sentry. It's likely a total edge case and I'm not sure why it happens, but it does 🤷🏻‍♂️

<img width="936" alt="CleanShot 2022-10-04 at 11 30 16" src="https://user-images.githubusercontent.com/193483/193785506-40dbc499-6f77-4f47-93d5-7f12ba10b9ea.png">

URL:

```
https://domain.tld/contao?act=delete&do=page&id=4207&ref=He8_lyIa&rt=45b4feffc1d2a078e9d8.E2v8sFdgGEra2j-JKeapLXi2ZA4xtK3BIQn5DSvAsdU.dymL-TlWfRqNrHWwGLP9FT3nKlpr_szzYni0bkGm2-xiKJXFJC5vJquedg
```

Stack trace:

```
ErrorException: Warning: Trying to access array offset on value of type null
#15 /vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php(1525): Contao\DC_Table::delete
#14 /vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php(667): Contao\Backend::getBackendModule
#13 /vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php(168): Contao\BackendMain::run
#12 /vendor/contao/core-bundle/src/Controller/BackendController.php(49): Contao\CoreBundle\Controller\BackendController::mainAction
#11 /vendor/symfony/http-kernel/HttpKernel.php(152): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#10 /vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel::handle
#9 /vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\Kernel::handle
#8 /vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(86): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle
#7 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(479): Symfony\Component\HttpKernel\HttpCache\HttpCache::forward
#6 /vendor/symfony/framework-bundle/HttpCache/HttpCache.php(73): Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache::forward
#5 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(452): Symfony\Component\HttpKernel\HttpCache\HttpCache::fetch
#4 /vendor/contao/manager-bundle/src/HttpKernel/ContaoCache.php(66): Contao\ManagerBundle\HttpKernel\ContaoCache::fetch
#3 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(346): Symfony\Component\HttpKernel\HttpCache\HttpCache::lookup
#2 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(224): Symfony\Component\HttpKernel\HttpCache\HttpCache::handle
#1 /vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(98): Contao\ManagerBundle\HttpKernel\ContaoCache::handle
#0 /web/index.php(44): null
```

2022-10-06 12:39 UTC, leofeyer commented
Which value exactly is `null` in your case? `$data[$this->strTable]` or `$data[$this->strTable][0]`?

2022-10-07 06:45 UTC, qzminski commented
Funny, the `$data` is totally empty `[]`. The system logs are still stored:

<img width="655" alt="CleanShot 2022-10-07 at 08 43 16" src="https://user-images.githubusercontent.com/193483/194484344-15769caf-7cef-4d31-a1dc-76408923bc82.png">

The delete URL refers to the records that no longer exist, it seems.

2022-10-07 08:11 UTC, fritzmg requested changes
This is reproducible by manipulating the `id` parameter in the delete URL to an `id` that does not exist in the table. Or in other words: this error can occur if the record to be deleted has already been deleted (e.g. by another back end user). `$data` can in fact be empty:

https://github.com/contao/contao/blob/1fb8f1d92c6874e791c84fe53f446f0cb4808ce4/core-bundle/src/Resources/contao/drivers/DC_Table.php#L1492-L1516

That being said, this fix is wrong as unnecessary `tl_undo` entries are still created. Instead I think we should instead add an early return like

```php
// There is no actual data to be deleted (see #5336)
if (0 === $affected)
{
    if (!$blnDoNotRedirect)
    {
        $this->redirect($this->getReferer());
    }

    return;
}
```

after line 1516.

2022-10-07 08:15 UTC, qzminski commented
Good catch @fritzmg ! The undo records with incomplete data would also throw exceptions if you try to enter the `Restore` backend module.

I have updated the pull request according to your suggestions.

2022-10-07 08:16 UTC, fritzmg commented
Mind you I haven't tested this though ;)

2022-10-07 08:18 UTC, qzminski commented
Don't you think we should check against `empty($data)` rather than `$affected` then?

2022-10-07 08:24 UTC, fritzmg commented
Yes, I thought `$affected++` was within the condition, but that's not the case.

2022-10-07 08:26 UTC, qzminski commented
Great, I have updated the PR again.

2022-10-07 08:57 UTC, fritzmg approved these changes

2022-10-07 09:13 UTC, ausi approved these changes

2022-10-10 09:49 UTC, m-vo approved these changes

2022-10-10 13:05 UTC, Toflar approved these changes

2022-10-11 07:43 UTC, merged

2022-10-11 07:43 UTC, leofeyer commented
Thank you @qzminski.