Handle errors with important parts
contao/contao pull request #5421
Opened 2022-10-25 05:38 UTC by aschempp

I still occasionally get the _The Y coordinate plus the height must not be greater than 1_ error in my client project, possibly due to old image resize configurations.

This PR fixes two issues:
 1. it adds the file information to the `CoordinatesOutOfBoundsException` so one knows which file is actually affected
 2. it then allows to edit the file in the back end, since it currently would throw the same error again when editing in the file manager. The file manager now looks like this and I can easily fix the errors.
 
<img width="1069" alt="Bildschirmfoto 2022-10-25 um 07 33 28" src="https://user-images.githubusercontent.com/1073273/197691422-65c161a7-8770-47f0-81d4-7d368df434ab.png">

2022-10-25 07:13 UTC, fritzmg commented
Since this is a bugfix, it should be based against Contao 4.9.

2022-10-25 07:33 UTC, leofeyer commented on core-bundle/src/Image/ImageFactory.php
> +                    throw new CoordinatesOutOfBoundsException($exception->getMessage()." for file \"$path\"", $exception->getCode(), $exception);
```suggestion
                    throw new CoordinatesOutOfBoundsException(sprintf('%s for file "%s"', $exception->getMessage(), $path), $exception->getCode(), $exception);
```

2022-10-25 07:36 UTC, leofeyer commented
The error message in the screen could be shortened by omitting the file path, which is already mentioned in the headline and below the "Name" field. Do we really need it a third time?

2022-10-25 08:05 UTC, fritzmg commented
But then the full path would be missing when the error is shown in the front end (via debug mode) or via sentry for example.

2022-10-25 08:39 UTC, ausi approved these changes, later dismissed
Should be backported to 4.9

2022-10-25 09:12 UTC, aschempp commented
> Should be backported to 4.9

I don't think Contao 4.9 has an `ImageFactory` right? So it would be a different solution?

2022-10-25 09:25 UTC, fritzmg commented
Contao 4.9 has an `ImageFactory` and its implementation is identical to Contao 4.13 (disregarding code style and a few other details).

2022-10-25 09:46 UTC, ausi commented
> I don't think Contao 4.9 has an `ImageFactory` right?

The `ImageFactory` is there since Contao 4.3.0 😅

2022-10-25 15:27 UTC, leofeyer commented
> But then the full path would be missing when the error is shown in the front end (via debug mode) or via sentry for example.

The call is wrapped in a try-catch block, so the exception will never be caught by the debugger or by Sentry, will it?

2022-10-25 15:46 UTC, fritzmg commented
Which call do you mean? [this](https://github.com/contao/contao/blob/e7d26741707d00e806c6eff2388e8335de1db823/core-bundle/src/Image/ImageFactory.php#L128) isn't wrapped in a try catch block. The error will be shown (and logged by sentry) in the `ImageController` for example.

2022-10-26 11:35 UTC, leofeyer requested changes
As stated above, this PR needs to be rebased to the `4.9` branch.

2022-10-27 07:23 UTC, aschempp commented
> As stated above, this PR needs to be rebased to the `4.9` branch.

done


> The call is wrapped in a try-catch block, so the exception will never be caught by the debugger or by Sentry, will it?

The try-catch block is only applied in the back end file view! The exception will also be triggered e.g. in the front end if an image with invalid important part is rendered.

2022-10-27 07:41 UTC, ausi approved these changes, later dismissed

2022-10-27 07:43 UTC, Toflar approved these changes, later dismissed
LGTM

2022-10-27 08:59 UTC, leofeyer approved these changes

2022-10-27 09:02 UTC, merged