Fix bug with cache in Database::listTables()
contao/contao pull request #5474
Opened 2022-11-02 16:49 UTC by ausi

`Database::listFields()` and `Database::listTables()` currently use the same array to cache its values. This results in incorrect data if you have a table with the same name as your database.

2022-11-03 08:48 UTC, Toflar approved these changes

2022-11-06 09:19 UTC, aschempp requested changes
Since this is an "instance" cache, I don't think we need a database name cache key at all? Each different instance to a different database would get its own cache?

2022-11-07 09:13 UTC, m-vo commented
> Since this is an "instance" cache, I don't think we need a database name cache key at all? 

You can probably not even select a different database because it gets read by `Config::get('dbDatabase')`. :wink:. 

I think using two caches is still correct but the table cache could be of `list<string>` instead of `array<string, list<string>>`.

2022-11-07 09:28 UTC, fritzmg commented
> You can probably not even select a different database because it gets read by `Config::get('dbDatabase')`. 😉.

You can override that with

```php
$db = Database::getInstance(['host' => '…', 'database' => '…', …]);
```

2022-11-07 09:35 UTC, m-vo commented
> You can override that with

Sure you could, but it would still only be a single db per instance.

2022-11-07 14:37 UTC, ausi commented
> Since this is an "instance" cache, I don't think we need a database name cache key at all?

But the results are different, so we have to have a cache array per database, not per instance IMO. Calling `->listTables('foo')` and `->listTables('bar')` returns different results that still need to be cached.

> Each different instance to a different database would get its own cache?

Yes, of course. One `Database` instance represents one connection, and connections to different servers should definitely not share a cache.

***

This PR only splits up `$arrCache` into `$arrCache` and `$arrTablesCache` to fix the naming collision bug, everything else is the same as it always was.

2022-11-07 14:39 UTC, aschempp approved these changes
ah I didn't see there's a database argument on the `listTables` method 👍

2022-11-07 14:41 UTC, merged

2022-11-07 14:41 UTC, leofeyer commented
Thank you @ausi.