Make sure text content is always a string
contao/contao pull request #5532
Opened 2022-11-25 08:30 UTC by aschempp

2022-11-25 08:55 UTC, Toflar submitted a review, later dismissed

2022-11-25 08:58 UTC, bytehead submitted a review, later dismissed

2022-11-28 09:30 UTC, leofeyer requested changes
Please also adjust the `@property` annotation to `string|null`.

https://github.com/contao/contao/blob/f12775f117d6e770005dba54010de84ee1f29481/core-bundle/src/Resources/contao/elements/ContentElement.php#L25

2022-11-28 10:02 UTC, leofeyer approved these changes

2022-11-28 10:04 UTC, merged