Fixed SitemapController not working for protected pages
contao/contao pull request #5556
Opened 2022-12-07 17:45 UTC by Toflar

`$pageModel->groups` is a serialized string of groups so it never returned `true`. Or in other words, the `sitemap.xml` did not return protected pages even when logged in for 1.5 years without anybody noticing...

The tests were pretty nonsense because they tested only that a page is not added when protected which of course was always green since the check never worked. The inverse (check whether a protected is added if access is given) was not checked. This is fixed now.

2022-12-07 18:32 UTC, aschempp requested changes
This can't really be true, because PageModel::loadDetails() does deserialize the data already: https://github.com/contao/contao/blob/5.x/core-bundle/contao/models/PageModel.php#L881

Maybe the controller does not load page details?

2022-12-07 18:51 UTC, Toflar commented
Yes, it doesn't that's why it needs a fix.

2022-12-07 19:36 UTC, aschempp commented
the fix should be to call `PageModel::loadDetails()` in the loop, your code would not apply inherited access permissions.

2022-12-08 10:30 UTC, Toflar commented
This is ready. Failing tests unrelated.

2022-12-08 10:31 UTC, fritzmg submitted a review, later dismissed

2022-12-12 17:00 UTC, leofeyer approved these changes

2022-12-12 17:01 UTC, merged

2022-12-12 17:01 UTC, leofeyer commented
Thank you @Toflar.