Use request language for iflng matching
contao/contao pull request #5606
Opened 2022-12-23 07:51 UTC by aschempp

If insert tags are replaced in the back end, the language cannot be matched on the page model. In my case this happens in the Isotope order details template, but it could also happen for our new Twig templates if I'm right.

2022-12-23 08:45 UTC, Toflar approved these changes, later dismissed

2022-12-23 09:15 UTC, Toflar approved these changes

2022-12-28 20:30 UTC, ausi reviewed
Does `$request->getLocale()` always match the `$objPage->language`? 
Or should we rather use the request as a fallback if `objPage` is not available?

2023-01-05 21:48 UTC, aschempp commented
> Does `$request->getLocale()` always match the `$objPage->language`?

it does because we set it in https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/pages/PageRegular.php#L88

2023-01-05 22:12 UTC, ausi approved these changes, later dismissed

2023-01-05 22:17 UTC, Toflar submitted a review, later dismissed

2023-01-11 10:37 UTC, leofeyer requested changes
Please also adjust the tests.

2023-01-17 11:05 UTC, Toflar approved these changes, later dismissed

2023-01-25 12:45 UTC, leofeyer approved these changes

2023-01-25 12:46 UTC, leofeyer commented
Thank you @aschempp.

2023-01-25 12:49 UTC, merged