Fix target decoding in figurebuilder
contao/contao pull request #5763
Opened 2023-02-07 22:37 UTC by agonyz

I think there might be an issue with the target decoding in the figurebuilder: https://github.com/contao/contao/blob/4.13/core-bundle/src/Image/Studio/FigureBuilder.php#L669

By using urldecode() a plus symbol ("+") gets decoded to a space (" ").
This leads to an error where images with a plus symbol in the filename eg. "myfile+name.jpg" would not be able to be opened in the lightbox even though the option would be set in a gallery.

By using rawurldecode() the plus symbols are not decoded into spaces and the images work in the lightbox.  

Is there a special reason to use urldecode() in this case? I could not find any documentation on that part.

### Reproduce the error
- Create a gallery content-element.
- Upload an image and use a plus symbol in the filename eg. "myfile+name.jpg".
- Enable the lightbox option in the gallery content-element.
- Check the frontend (lightbox-element should not work for this image)

Fix:
- Rename the image (remove plus symbol from filename eg. "myfilename.jpg")
- Check the frontend (lightbox-element should work now)

2023-02-09 08:05 UTC, m-vo approved these changes
Can we add or adjust an existing test case for this?

2023-02-09 13:36 UTC, ausi commented
I don’t think this needs to be fixed here. It seems that the gallery somewhere calls `setLightboxResourceOrUrl()` without properly URL-encoding the path.

2023-02-16 09:20 UTC, ausi requested changes
https://github.com/contao/contao/pull/5763#issuecomment-1424203377

2023-02-16 09:46 UTC, ausi commented
Created an alternative pull request to this one that fixes the issue by not urldecoding file paths at all: #5777

2023-02-16 17:17 UTC, leofeyer commented
I‘m closing this in favor of #5777. @agonyz Thank you for your contribution. 🙏

2023-02-16 17:17 UTC, closed without merging