get picker url parameters via own method
contao/contao pull request #579
Opened 2019-07-14 19:52 UTC by rabauss

Get the picker url parameters via own method, to get the possibility to overwrite/extend it in own extensions.

2019-07-24 07:34 UTC, aschempp commented
Can you explain why you want to override the `FileTree`? And can you not just set these properties on the object?

2019-07-24 15:12 UTC, rabauss commented
We want to transfer more context data (table, field, id, providers) to the picker url, so that we can use it for calls to our external asset managment system. The extension is still in progress - but kind of similar to https://github.com/terminal42/contao-bynder/

2019-07-24 21:01 UTC, Toflar commented
Maybe you should have your completely own picker instead of extending the core one then?😊

2019-07-28 06:09 UTC, aschempp commented
I guess https://github.com/contao/core-bundle/pull/1171 is what you need. Until then you should create your own widget and not extend the core widget.

2019-08-21 22:20 UTC, rabauss commented
Well, yes we could use our own picker but we wanted to replace the filepicker with custom asset picker from external system - and so we thought this could be achived best by replacing/extending the core filetree without too much duplicate code for similar widget.

2019-08-22 05:57 UTC, aschempp commented
You should probably not replace the file widget, but add a new picker to the popup? We did something similar in https://github.com/terminal42/contao-bynder

2019-08-22 06:17 UTC, rabauss commented
I know your extension. But we want to support the core filemanager and external DAm just for the first insert. After picking a file from the external DAM we want to disable the core filepicker. I think this is only possible via overwriting the core filetree, isn't it?

2019-08-22 06:24 UTC, aschempp commented
There are picker configuration options to limit the available tabs in the back end. Not sure if you can specify them for the filePicker though.

2019-08-22 06:50 UTC, rabauss commented
At the moment we set `$extras['providers'] = 'ourPicker'` in the fileTreeWidget if the FileModel has an ID of the external DAM - therefor among other variables for the pickerUrl (like fieldname, table), we added this PR!
Of course we could write an own widget (like we did at the moment), but the only difference to the fileTree would be the extra picker url variables.

2019-08-22 09:44 UTC, aschempp commented
I understand now. In the regular `extra => dcawizard => []` field you can add unlimited props for the pickers. Maybe we should introduce something similar for this case?

Or rather have a universal picker and use it everywhere 😇

2019-08-22 09:56 UTC, rabauss commented
Yes, an universal picker in the core would be the best :-)
We have an internal package adapted to the https://github.com/contao/core-bundle/pull/1171 but there is too much legacy code inside to reuse.

2020-01-02 14:48 UTC, leofeyer commented
@rabauss @aschempp What is the status of this PR now that we have added a universal picker in #714?

2020-01-03 11:39 UTC, rabauss commented
The main problem remains in the widget and also in the new picker widget.
https://github.com/contao/contao/blob/2aeda7f9c41eb8725c0c9b47e3ed3303c9daf7a8/core-bundle/src/Resources/contao/widgets/Picker.php#L150

The url parameters (`$extras`) for the picker cannot be overwritten/extended, if someone `extends` the class! I think I should rebase this PR and I will open another one for `widgets/Picker.php`

2020-01-07 10:38 UTC, leofeyer requested changes

2020-01-07 10:38 UTC, leofeyer commented on core-bundle/src/Resources/contao/widgets/FileTree.php
> +	 * Return the extra parameters for picker url
```suggestion
	 * Return the extra parameters for the picker URL
```

2020-01-09 08:56 UTC, aschempp approved these changes

2020-01-09 09:55 UTC, leofeyer approved these changes

2020-01-09 09:56 UTC, merged

2020-01-09 09:56 UTC, leofeyer commented
Thank you @rabauss.