get picker url parameters via own method
contao/contao pull request #580
Opened 2019-07-14 20:08 UTC by rabauss

Get the picker url parameters via own method, to get the possibility to overwrite/extend it in own extensions.

Sorry for the second PR, just didn't want to use my feature for filetree.
After https://github.com/contao/contao/pull/579 I just realized, that in pagetree is similar logic.

2020-01-02 14:48 UTC, leofeyer commented
@rabauss @aschempp What is the status of this PR now that we have added a universal picker in #714?

2020-01-07 10:37 UTC, leofeyer requested changes

2020-01-07 10:37 UTC, leofeyer commented on core-bundle/src/Resources/contao/widgets/PageTree.php
> +	 * Return the extra parameters for picker url
```suggestion
	 * Return the extra parameters for the picker URL
```

2020-01-09 08:54 UTC, aschempp approved these changes

2020-01-09 09:56 UTC, leofeyer approved these changes

2020-01-09 09:56 UTC, merged