Render modules and elements from templates
contao/contao pull request #5808
Opened 2023-02-21 17:30 UTC by aschempp

This is a very simple approach that allows to render any module or content element directly in Twig templates without having a database record.

This works perfectly in `fe_page.html.twig`:

```twig
{{ insert_module('navigation', { levelOffset: 1 }) }}
```

2023-02-21 17:30 UTC, m-vo commented
Related https://github.com/contao/contao/pull/3942

2023-02-21 22:44 UTC, ausi approved these changes, later dismissed

2023-02-21 22:47 UTC, Toflar requested changes
Tests...

2023-02-21 23:26 UTC, m-vo commented
I think I would prefer if the method would return a controller reference and I could use it analogous to the (upcoming) nested content elements with something like `{{ render(content_element(…)) }}`. 

(I would not care about legacy elements/modules.)

2023-02-21 23:43 UTC, aschempp commented
> I think I would prefer if the method would return a controller reference and I could use it analogous to the (upcoming) nested content elements with something like `{{ render(content_element(…)) }}`.

This would have at least two major negative implications which would make this PR useless to me
 1. you cannot use any existing module (almost all core modules) and same goes for any extension that is not updated to fragments (I would guess thats > 80%)
 2. permissions or visibility would not be checked when including (contrary to what the insert tag does)

2023-02-22 00:23 UTC, m-vo commented
> permissions or visibility

Which permissions do you mean? Visibility also doesn't make any sense for on-the-fly generated things, no?

2023-02-22 07:18 UTC, ausi commented
> 1. you cannot use any existing module

Could we create a proxy that is the other way round? Meaning a proxy fragment controller that renders legacy elements? In this case we could then always return a controller reference.

2023-02-25 15:43 UTC, aschempp commented
I don't think that is worth the effort or makes sense. It also would not solve the permission/publishing checks etc.

2023-04-13 15:25 UTC, ausi commented on core-bundle/src/Twig/Extension/ContaoExtension.php
> +                'insert_content',
```suggestion
                'frontend_module',
                [FragmentRuntime::class, 'renderModule'],
                ['is_safe' => ['html']]
            ),
            new TwigFunction(
                'content_element',
```

2023-04-14 13:19 UTC, leofeyer submitted a review, later dismissed
The changes look good to me now. I haven't tested them though, so I will wait for another approval from @ausi or @Toflar.

2023-04-14 13:45 UTC, m-vo submitted a review, later dismissed
Reviewed & manually tested. Works fine! :+1:

2023-04-14 13:54 UTC, m-vo commented
One thing, that I found out when testing, is, that providing normally serialized values as an object currently already works:

```twig
{{ content_element('text', {
    headline: {'unit': 'h1', value: 'Inline content element example'},
    text: '<p>Here you go!</p>'
}) }}
```

But this is because the value just gets set in the model (as an associative array) and `StringUtil::deserialize()` in the controller then skips and returns the value (that is already an array). If the model would have a type check, this would fail. I wonder if we should handle the case by either never allowing objects/arrays (and adding a `|serialize` filter) or by automatically serializing everything that's not a scalar. :thinking:

2023-04-14 19:12 UTC, aschempp commented
I think that's perfectly good to work like that. Why would I want to pass serialized data if I don't need to?

2023-04-14 19:33 UTC, m-vo commented
> Why would I want to pass serialized data if I don't need to?

Because `$contentModel->headline` is supposed to be a string, not an array:
https://github.com/contao/contao/blob/03bdd806220338a2be1f3f019f9bf81d6dc0467d/core-bundle/contao/models/ContentModel.php#L25

If there would be a setter, it would have the signature `setHeadline(string $headline)` and would break, same with a getter.

2023-04-15 22:10 UTC, ausi commented
> I wonder if we should handle the case by either never allowing objects/arrays (and adding a `|serialize` filter) or by automatically serializing everything that's not a scalar.

I think the latter makes most sense, this way your example code would work as expected 👍

> Why would I want to pass serialized data if I don't need to?

I think there should be no difference (or as little as possible) between the data coming from the database and the data coming from the template directly.

2023-05-04 14:10 UTC, Toflar submitted a review, later dismissed

2023-05-05 15:10 UTC, leofeyer commented
> > I wonder if we should handle the case by either never allowing objects/arrays (and adding a `|serialize` filter) or by automatically serializing everything that's not a scalar.
> 
> I think the latter makes most sense, this way your example code would work as expected 👍

So this means that the pull request needs to be adjusted again?

2023-05-05 21:00 UTC, ausi commented on core-bundle/src/Twig/Runtime/FragmentRuntime.php
> +            $model->$k = $v;
```suggestion
            if (null !== $v && !\is_scalar($v)) {
                $v = serialize($v);
            }

            $model->$k = $v;
```

2023-05-05 21:04 UTC, ausi commented on core-bundle/tests/Twig/Runtime/FragmentRuntimeTest.php
> +        $result = $runtime->renderContent('text', ['foo' => 'bar']);
```suggestion
        $result = $runtime->renderContent('text', ['foo' => 'bar', 'headline' => ['unit' => 'h2', 'value' => 'Test']]);
```

2023-05-05 21:04 UTC, ausi commented on core-bundle/tests/Twig/Runtime/FragmentRuntimeTest.php
> +                    $this->assertSame(['type' => 'text', 'foo' => 'bar'], $model->row());
```suggestion
                    $this->assertSame(['type' => 'text', 'foo' => 'bar', 'headline' => serialize(['unit' => 'h2', 'value' => 'Test'])], $model->row());
```

2023-05-08 21:54 UTC, ausi approved these changes

2023-05-09 10:40 UTC, merged

2023-05-09 10:40 UTC, leofeyer commented
Thank you @aschempp.