Fix delete multiple
contao/contao pull request #5840
Opened 2023-03-06 10:04 UTC by Toflar

Fixes https://github.com/contao/contao/issues/5839

In `deleteAll()` we delete all the IDs that have been selected. If you select a parent and it's child, you will get a `NotFoundException` for the child record. This is, because the parent already deleted the child during the first `delete()` and its respective `deleteChilds()` call. So by the time the second ID wants to be deleted in `deleteAll()`, it's already gone.

Fix is simple: We don't need to throw a `NotFoundException` at all. If a record is already gone then that's good, why would there be any error? :)

2023-03-06 10:09 UTC, qzminski submitted a review, later dismissed

2023-03-06 12:49 UTC, leofeyer approved these changes, later dismissed

2023-03-06 13:17 UTC, aschempp requested changes
just returning here seems wrong to me, because the method by default redirects back to the referrer. Can you please also explain how `deleteChild()` could already been executed? The `delete()` method is executed from `act=delete` and never recursively as far as I know?

2023-03-06 16:20 UTC, Toflar commented
> Can you please also explain how `deleteChild()` could already been executed? The `delete()` method is executed from `act=delete` and never recursively as far as I know?

We're talking about `deleteAll()` which contains an array of multiple IDs that have been selected in the back end. We loop over those and call `delete()` for them all. `delete()` itself calls `deleteChilds()`. Which means that if the IDs you selected initially are in aparent->child relelation, the second call of `delete()` within `deleteAll()` will run on the child already deleted by the previous call.

2023-03-07 22:15 UTC, aschempp requested changes
I see. I would suggest to handle that case explicitly then.

2023-03-07 22:15 UTC, aschempp commented on core-bundle/contao/drivers/DC_Table.php
> +			return;
```suggestion
            if ($blnDoNotRedirect)
            {
			    return;
			}
			
			throw new NotFoundException('Cannot load record "' . $this->strTable . '.id=' . $this->intId . '".');
```

2023-03-08 10:39 UTC, aschempp approved these changes

2023-03-08 11:27 UTC, merged

2023-03-08 11:27 UTC, leofeyer commented
Thank you @Toflar.