Correctly check the mounted pages in the `hasAccess()` method
contao/contao pull request #5893
Opened 2023-03-21 11:28 UTC by leofeyer

Fixes #5707

The previous discussion is here: #2895

2023-03-21 12:39 UTC, aschempp commented
what happened to my comment? https://github.com/contao/contao/issues/2895#issuecomment-1038744528

2023-03-21 13:10 UTC, leofeyer commented
I would like the voter behave the same as the `hasAccess()` method, but we have to discuss the whole issue again anyway.

2023-04-13 14:27 UTC, leofeyer commented
As discussed in the call, we want to fix the `hasAccess()` method now. 😄

2023-04-13 14:29 UTC, ausi submitted a review, later dismissed

2023-04-13 14:35 UTC, aschempp requested changes
The `getChildRecords` accepts a list of parent page IDs, so one DB request to fetch the children should be quicker than iterate.

2023-04-13 14:35 UTC, aschempp commented on core-bundle/src/Resources/contao/classes/BackendUser.php
> +			}
```suggestion
			// Check the mounted pages
			$childIds = $this->Database->getChildRecords($this->pagemounts, 'tl_page');

			if (!empty($childIds) && array_intersect($field, $childIds))
			{
				return true;
			}
```

2023-04-14 19:13 UTC, aschempp approved these changes

2023-04-14 19:24 UTC, Toflar approved these changes

2023-04-17 08:25 UTC, merged