Only return actual languages in Locales::getLanguages()
contao/contao pull request #5907
Opened 2023-03-23 11:08 UTC by aschempp

When I call `Locales::getLanguages()` on my system, I get "strange" results for `English (POSIX)` as well as some languages with script tags (_Chinese (Simplified)_ and _Chinese (Traditional)_ ). Since these are not languages, these should not be returned in my opinion.

2023-03-23 12:55 UTC, ausi commented on core-bundle/src/Intl/Locales.php
> +                return \Locale::composeLocale([\Locale::LANG_TAG => $locale[\Locale::LANG_TAG]]);
```suggestion
                return \Locale::composeLocale(
                    array_intersect_key(
                        \Locale::parseLocale($localeId),
                        [\Locale::LANG_TAG => null, \Locale::SCRIPT_TAG => null],
                    )
                );
```

2023-03-23 12:56 UTC, ausi commented
In most cases you want to have different entries for languages with different scripts, like:

```
sr_Cyrl: Serbian (Cyrillic) - српски (ћирилица)
sr_Latn: Serbian (Latin) - srpski (latinica)
```

Because “српски” and “srpski” is not the same for most people.

But I agree that the other tags are probably not needed (like `variant0: POSIX`).

2023-03-23 14:03 UTC, aschempp commented
But `Serbian (Cyrillic)` is not a language, its a script of a language. Chinese can be written in simplified or traditional characters, but its both Chinese. Same applies to german written in Latin or Cyrillic 😅

2023-03-23 14:42 UTC, ausi commented
> But `Serbian (Cyrillic)` is not a language, its a script of a language.

Yes, but in order to show a user translated texts based on the selected language you need to differentiate between the two. And as this is the usual use case for the `Locales::getLanguages()` method they need to be in the list.

What is your specific use case for `Locales::getLanguages()` where you don’t need `Serbian (Latin)`?
Maybe we could create a method that matches your use case better?

2023-03-23 21:07 UTC, aschempp commented
My DCA shows a list of languages to select. If I would select `cn_Hant` I don't think the Contao translator would be able to handle that anyway? What use case is there for selecting `cn_Hant`?

2023-03-23 21:40 UTC, bytehead commented
I use it this way (as I know which languages are supported): 

```
'options_callback' => static fn () => System::getContainer()->get('contao.intl.locales')->getDisplayNames(['de', 'fr', 'it', 'rm', 'en'], null, true),
```

I don't know, if this supports your use case as well?

2023-03-24 07:53 UTC, aschempp commented
@bytehead that would give you the labels for the given list of languages, right? I don't think that's my use case, since I want to select _any_ official language.

2023-03-24 08:58 UTC, ausi requested changes
> My DCA shows a list of languages to select.

And what is this selected language then used for?

> If I would select `cn_Hant` I don't think the Contao translator would be able to handle that anyway?

The Contao translator can handle that perfectly fine since Contao 4.12.

> I want to select _any_ official language.

Both, српски and srpski are official languages. MacOS also lists both languages:
![Bildschirm­foto 2023-03-24 um 09 43 43](https://user-images.githubusercontent.com/367169/227469156-602a61b1-07c1-44c4-956b-81523f7c4eef.png)

So unless you tell us your use case, I’m against merging this.

2023-03-24 10:25 UTC, fritzmg commented
@ausi but these are display languages for an operating system where the use case is clear. I think there is definitely a difference between display languages and spoken languages. Depending on your use case the language selection for a member for example (or in the registration module respectively) does not need to include all display languages, if you only care about which primary language the member speaks.

So far I haven't yet had a use case for one or the other, but I can definitely see why you sometimes do not want to offer all possible display languages.

2023-03-24 15:16 UTC, ausi commented
> but these are display languages for an operating system where the use case is clear. I think there is definitely a difference between display languages and spoken languages.

There is, but `Locales::getLanguages()` is also meant for a display language context as its main use case IMO. These are the languages that we can use with the `Intl` extension to display dates like `new IntlDateFormatter('sr_Latn')` or currencies and so on.

For a list of spoken languages you should not use the `Locales` service IMO.

2023-04-03 07:22 UTC, aschempp commented
> For a list of spoken languages you should not use the Locales service IMO.

What source would I use instead? My system was previously based on the Contao languages file, which did not include scripts etc.

2023-04-03 08:49 UTC, ausi commented
> What source would I use instead?

That depends on your use case.

2023-04-03 14:12 UTC, ausi commented
If you look for something “official” maybe the ISO 639-1 fits what you need? It currently contains 183 two-letter codes that are “officially assigned” and are not deprecated.

```php
'options_callback' => static fn () => System::getContainer()->get('contao.intl.locales')->getDisplayNames(['aa', 'ab', 'ae', 'af', 'ak', 'am', 'an', 'ar', 'as', 'av', 'ay', 'az', 'ba', 'be', 'bg', 'bi', 'bm', 'bn', 'bo', 'br', 'bs', 'ca', 'ce', 'ch', 'co', 'cr', 'cs', 'cu', 'cv', 'cy', 'da', 'de', 'dv', 'dz', 'ee', 'el', 'en', 'eo', 'es', 'et', 'eu', 'fa', 'ff', 'fi', 'fj', 'fo', 'fr', 'fy', 'ga', 'gd', 'gl', 'gn', 'gu', 'gv', 'ha', 'he', 'hi', 'ho', 'hr', 'ht', 'hu', 'hy', 'hz', 'ia', 'id', 'ie', 'ig', 'ii', 'ik', 'io', 'is', 'it', 'iu', 'ja', 'jv', 'ka', 'kg', 'ki', 'kj', 'kk', 'kl', 'km', 'kn', 'ko', 'kr', 'ks', 'ku', 'kv', 'kw', 'ky', 'la', 'lb', 'lg', 'li', 'ln', 'lo', 'lt', 'lu', 'lv', 'mg', 'mh', 'mi', 'mk', 'ml', 'mn', 'mr', 'ms', 'mt', 'my', 'na', 'nb', 'nd', 'ne', 'ng', 'nl', 'nn', 'no', 'nr', 'nv', 'ny', 'oc', 'oj', 'om', 'or', 'os', 'pa', 'pi', 'pl', 'ps', 'pt', 'qu', 'rm', 'rn', 'ro', 'ru', 'rw', 'sa', 'sc', 'sd', 'se', 'sg', 'si', 'sk', 'sl', 'sm', 'sn', 'so', 'sq', 'sr', 'ss', 'st', 'su', 'sv', 'sw', 'ta', 'te', 'tg', 'th', 'ti', 'tk', 'tl', 'tn', 'to', 'tr', 'ts', 'tt', 'tw', 'ty', 'ug', 'uk', 'ur', 'uz', 've', 'vi', 'vo', 'wa', 'wo', 'xh', 'yi', 'yo', 'za', 'zh', 'zu'], null, true),
```

The `getDisplayNames` handles them correctly but probably cannot show the native names for some of them as this list includes around 50 languages the intl extension has no data for.

2023-04-13 15:10 UTC, aschempp commented
As discussed in the Contao call today, Intl only provides a list of _supported_ locales, which means Intl e.g. has number or date formatting information for. There can be a bazzillion more languages on the planet than Intl knows about. To solve my problem, I probably just need to remove all options with dash in name.

2023-04-13 15:10 UTC, closed without merging