Add channel id to subject for List-Unsubscribe
contao/contao pull request #5933
Opened 2023-04-05 13:48 UTC by de-es

Aktuell kann man bei der Benutzung von List-Unsubscribe nicht erkennen, welcher Channel im Detail abgemeldet werden soll.

Wir verwenden für alle Channels die exakt gleichen Transports und Maileinstellungen. Da sich die Abonennten pro Channel teilweise überschneiden, lässt es sich auch nicht an seiner Mailadresse beim Unsubscribe festmachen.

Durch die Ergänzung der Channel-ID wäre eine eindeutige Zuordnung möglich.

2023-04-06 10:48 UTC, leofeyer commented
Doesn‘t this introduce the issue from #4412 again?

2023-04-06 11:29 UTC, de-es commented
Das Ticket / Den Aspekt hatte ich in der Tat nicht gesehen. Aber: Die dort erwähnte SpamAssassin Regex schlägt bei codierten Leerzeichen alleine nicht an. Problematisch waren die Umlaute. Im Zweifel könnte man die Leerzeichen durch `-` ersetzen.

2023-04-14 19:18 UTC, aschempp approved these changes

2023-04-16 12:18 UTC, ausi commented
But shouldn’t using the `List-Unsubscribe` header unsubscribe you from all channels anyway?

2023-04-16 12:49 UTC, fritzmg commented
If you have a multidomain setup for example where domain A uses newsletter channel A and domain B uses newsletter channel B, the `List-Unsubscribe` header from the newsletter from domain A should not unsubscribe you from the newsletter form domain B I think.

2023-04-16 12:53 UTC, ausi commented
In this case the `$objNewsletter->sender` should be an email addresses from the corresponding domain.

2023-04-16 15:15 UTC, de-es commented
> But shouldn’t using the `List-Unsubscribe` header unsubscribe you from all channels anyway?

Das würde zumindest in unserem Usecase auf jeden Fall für große Irritationen bei den Abonnenten sorgen.

> In this case the `$objNewsletter->sender` should be an email addresses from the corresponding domain.

`$objNewsletter->sender`  ist ja aktuell auch gleichzeitig `From:` . Ich würde ungern verschiedene Absenderadressen nutzen, da die Nutzung derselben über alle Kanäle aktuell für eine hohe technische Empfangsrate und Empfängerakzeptanz sorgt.

Eine Alternative wäre dann evtl. eine zusätzliche kanalspezifische, optionale Mailadresse explizit für `List-Unsubscribe`, was aber vermutlich ein neues Feature wäre.

2023-04-17 06:50 UTC, fritzmg commented
I think ultimately this can only be solved with proper unsubscribe URLs.

2023-04-17 08:56 UTC, leofeyer commented
If we are sure that the change will not trigger the problem of https://github.com/contao/contao/issues/4412 again, I would vote to merge the PR.

2023-04-17 09:15 UTC, de-es commented
> I think ultimately this can only be solved with proper unsubscribe URLs.

Keine Frage. Ich war nur auf der Suche nach einer schnellen Lösung für ein akutes Problem. :grin: 

> If we are sure that the change will not trigger the problem of #4412 again, I would vote to merge the PR.

Ich habe es mit SpamAssassin (dF), Rspamd (Mailcow) und https://www.mail-tester.com getestet. Es wurde keine Flag für den Header gerissen.

2023-04-17 15:38 UTC, ausi commented
If we want to merge this, I think instead of the channel ID, we could use the ID of the recipient, this way we’d also solve the case where the email address of the user is different from their unsubscribe-email. WDYT?

2023-04-27 14:39 UTC, leofeyer commented
But how will the admin known which channel to unsubscribe the recipient from?

2023-04-27 18:54 UTC, ausi commented
AFAIK every recipient can only have one channel (pid). Multiple channels for one e-mail address means multiple entries in the `tl_newsletter_recipients`.

So to get the channel you’d query `SELECT * FROM tl_newsletter_channel WHERE id = (SELECT pid FROM tl_newsletter_recipients WHERE id = ?)`

2023-04-28 08:12 UTC, leofeyer commented
@de-es Can you please change the PR accordingly?

2023-05-05 14:45 UTC, leofeyer requested changes
@de-es Can you please change the PR accordingly?

2023-05-09 14:33 UTC, de-es commented
Auch wenn die von ausi vorgeschlagene Lösung die technisch schönere ist, ist es für den unversierten Redakteur aktuell die ungleich schwerere/aufwendigere. Den kann ich ja nicht mit SQL auf die Suche schicken. :laughing: 

Channel-ID:
- Suche den Channel mit der entsprechenden ID mit Hover über (i)
- Filtere nach der Mailadresse
- Löschen

Recipient-ID:
- Gehe in einen Channel
- Filtere nach der Mailadresse
- Überprüfe, ob die es die gesuchte Recipient-ID ist mit Hover über (i)
- Falls nicht, gehe zurück und zum nächsten Channel

Man hat natürlich jetzt nicht unzählige Channels, aber es sollte für die Redakteure nachvollziehbar sein, zumal der Vorgang insgesamt eher selten vorkommt.

Wenn es dennoch der Konsens sein sollte, die Recipient-ID zu nehmen, kann ich den PR entsprechend anpassen. Aber das wird leider noch etwas dauern.

> this way we’d also solve the case where the email address of the user is different from their unsubscribe-email.

Ich bin mir nicht sicher, ob man diesen Fall überhaupt abdecken will. Dann könnte man ja - vorbehaltlich der manuellen Nachprüfung - einfach darüber andere Personen abmelden. Im Zweifel packt man dafür immer noch einen Abmeldelink in den Mailcontent.

2023-05-11 06:18 UTC, aschempp commented
ich gebe @de-es recht (und habe mir das auch schon gedacht). Die Channel-ID ist für einen Redakteur sehr viel hilfreicher also die User-ID.

2023-05-11 09:13 UTC, ausi commented
Das verstehe ich nicht ganz. Die Absender-Adresse ist ja häuft nicht die, an die der Newsletter geschickt wurde. Wie findet der Redakteur den richtigen Eintrag wenn die Absender-E-Mail-Adresse nicht zu finden ist?

Vorschlag: „Unsubscribe ID 456 Channel 123“

2023-05-20 11:39 UTC, de-es commented
> Das verstehe ich nicht ganz. Die Absender-Adresse ist ja häuft nicht die, an die der Newsletter geschickt wurde. Wie findet der Redakteur den richtigen Eintrag wenn die Absender-E-Mail-Adresse nicht zu finden ist?

Ist das allgemein so? Zumindest in meinem Usecase könnte ich das nicht bestätigen. Ich würde auch so agumentieren, dass derjenige, der Alias-/Catchall-Adressen & Co. einrichten kann, in soweit auch versteht, dass man sich nur mit der Mailadresse abmelden kann, mit der auch die Anmeldung erfolgt ist.

> Vorschlag: „Unsubscribe ID 456 Channel 123“

Für mich wäre das ein guter Kompromiss, wenn ihr alle damit einverstanden seid. Ich würde sicherheitshalber aber auch nochmal ein paar Tests machen, ob eine andere Filterregeln dabei anschlagen würde.

2023-06-01 14:25 UTC, leofeyer commented
@de-es Hattest Du schon Zeit, um den gefundenen Kompromiss zu testen?

2023-06-01 20:43 UTC, de-es commented
Closed this in favor of 6113.

2023-06-01 20:43 UTC, closed without merging