Support readonly in TinyMCE and ACE editor
contao/contao pull request #5985
Opened 2023-04-25 07:45 UTC by zonky2

Add readonly at tinyMCE and ACE editor if set in DCA

2023-04-25 07:50 UTC, ausi commented on core-bundle/src/Resources/contao/classes/DataContainer.php
> +			$objTemplate->readonly = (bool) $arrData['eval']['readonly'];
```suggestion
			$objTemplate->readonly = (bool) ($arrData['eval']['readonly'] ?? false);
```

2023-05-02 08:07 UTC, aschempp approved these changes, later dismissed

2023-05-08 14:08 UTC, leofeyer requested changes

2023-05-08 14:08 UTC, leofeyer commented on core-bundle/src/Resources/contao/templates/backend/be_ace.html5
> +  <?php if ($this->readonly): ?>editor.setOptions({readOnly, true,});<?php endif; ?>
This looks weird to me. Do you mean `{readOnly: true}`?

2023-05-19 10:01 UTC, leofeyer requested changes

2023-05-19 10:01 UTC, leofeyer commented on core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
> +  <?php if ($this->readonly): ?>readonly: 1,<?php endif; ?>
According to the documentation, possible values are `true` and `false` but not `1`.

<img width="790" alt="" src="https://github.com/contao/contao/assets/1192057/c39c2404-9188-42c6-8907-d01a5947a0ce">

See https://www.tiny.cloud/docs/tinymce/6/editor-important-options/#starting-the-editor-in-a-read-only-state

2023-05-19 14:49 UTC, leofeyer approved these changes

2023-05-19 14:50 UTC, leofeyer commented
Thank you @zonky2.

2023-05-19 14:54 UTC, merged