Added abstract controller for common service tasks
contao/contao pull request #603
Opened 2019-07-23 11:51 UTC by aschempp

The Symfony `AbstractController` combines several useful features into simple method calls. We could do the same for Controllers that usually need the same Contao stuff. There's more that I can imagine, like

 - getting the front end or back end user (across firewall scopes)
 - checking if front end preview is enabled
 - generating a response from a Contao template

2019-07-23 12:09 UTC, leofeyer commented
I like the `getSubscribedServices()` method but I don't see any added value in the `initializeContao()` method.

2019-12-03 13:20 UTC, aschempp commented
> but I don't see any added value in the `initializeContao()` method.

It's the same as all other methods in Symfonys `AbstractController`. They are shortcuts and provide autocomplete support for regular calls. Theres not _added value_ in `AbstractController::isGranted()`, but it moves the logic to the abstract class instead of re-implementing it over and over again.

2019-12-03 13:51 UTC, leofeyer commented
Ok, agreed. But the method is not initializing Contao but the Contao framework, therefore it should be called `initializeContaoFramework()`, shouldn't it?

2019-12-06 13:08 UTC, Toflar submitted a review, later dismissed
LGTM!

2019-12-06 14:41 UTC, leofeyer requested changes
Besides the minor CS fix, this PR looks RTM to me. 👍

2019-12-06 14:41 UTC, leofeyer commented on core-bundle/src/Controller/AbstractController.php
> +     */
This phpDoc provides no additional information and can therefore be removed.

2019-12-10 13:10 UTC, bytehead approved these changes

2019-12-10 15:29 UTC, leofeyer approved these changes

2019-12-10 15:29 UTC, merged

2019-12-10 15:29 UTC, leofeyer commented
Thank you @aschempp.