Fix a potential error if the URL has percentage in it
contao/contao pull request #619
Opened 2019-08-02 12:43 UTC by qzminski

With @Toflar we have discovered by accident that if a URL is double-encoded (for some reason, doesn't matter) the Contao's `RouteProvider` will eventually throw an error trying to query a database.

```
URL original: drachenlochmuseum-v%25c3%25a4ttis.html
URL decoded: drachenlochmuseum-v%c3%a4ttis.html
URL decoded 2nd time: drachenlochmuseum-vättis.html
```

The decoded URL is used in the database query and that fails because the database driver would like to replace wildcards `%c` with parameters that were not provided.

Stack trace:

```
Exception: Too few arguments to build the query string
#27 vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php(304): replaceWildcards
#26 vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php(249): execute
#25 vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php(1102): find
#24 vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php(973): findBy
#23 vendor/contao/core-bundle/src/Framework/Adapter.php(38): __call
#22 vendor/contao/core-bundle/src/Routing/RouteProvider.php(493): findPages
#21 vendor/contao/core-bundle/src/Routing/RouteProvider.php(88): getRouteCollectionForRequest
#20 vendor/contao/core-bundle/src/Routing/LegacyRouteProvider.php(43): getRouteCollectionForRequest
#19 vendor/symfony-cmf/routing/src/NestedMatcher/NestedMatcher.php(141): matchRequest
#18 vendor/contao/core-bundle/src/Routing/Matcher/LegacyMatcher.php(69): matchRequest
#17 vendor/symfony-cmf/routing/src/DynamicRouter.php(271): matchRequest
#16 vendor/symfony-cmf/routing/src/ChainRouter.php(188): doMatch
#15 vendor/symfony-cmf/routing/src/ChainRouter.php(158): matchRequest
#14 vendor/symfony/http-kernel/EventListener/RouterListener.php(115): onKernelRequest
#13 vendor/symfony/event-dispatcher/EventDispatcher.php(212): doDispatch
#12 vendor/symfony/event-dispatcher/EventDispatcher.php(44): dispatch
#11 vendor/symfony/http-kernel/HttpKernel.php(126): handleRaw
#10 vendor/symfony/http-kernel/HttpKernel.php(67): handle
#9 vendor/symfony/http-kernel/Kernel.php(198): handle
#8 vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): handle
#7 vendor/symfony/http-kernel/HttpCache/HttpCache.php(448): forward
#6 vendor/symfony/framework-bundle/HttpCache/HttpCache.php(57): forward
#5 vendor/symfony/http-kernel/HttpCache/HttpCache.php(420): fetch
#4 vendor/contao/manager-bundle/src/HttpKernel/ContaoCache.php(46): fetch
#3 vendor/symfony/http-kernel/HttpCache/HttpCache.php(317): lookup
#2 vendor/symfony/http-kernel/HttpCache/HttpCache.php(192): handle
#1 vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(98): handle
#0 web/app.php(58): null
```

2019-08-02 12:52 UTC, Toflar requested changes
I've added a comment and tests are failing ;)

2019-08-02 12:52 UTC, Toflar commented on core-bundle/src/Routing/RouteProvider.php
> +        // The request string must not contain "auto_item" (see #4012) or a percentage character
```suggestion
        // The request string must not contain "auto_item" (see #4012) or a percentage character (which means it was double encoded (see #619))
```

2019-08-02 17:42 UTC, qzminski commented
Tests still fail but I think they are not related to my PR… see https://travis-ci.com/contao/contao/jobs/222071371

2019-08-03 08:05 UTC, Toflar submitted a review, later dismissed
Yeah, failing tests unrelated. LGTM👍

2019-08-05 07:17 UTC, aschempp requested changes
This looks very strange to me. 

Your problem:

> The decoded URL is used in the database query and that fails because the database driver would like to replace wildcards %c with parameters that were not provided.

Your solution:

> Disallow % in the URL

That can't be right? What if I enter a `%` in the alias field in the back end? Shouldn't we make sure the database query does correctly handle `%` characters?

Also, there are functional tests for the routing, we should update them for this case. A unit test is not sufficient here.

2019-08-05 07:35 UTC, qzminski commented
I am a bit confused here because `%` sign has an extra meaning in the URLs because it is used to encode special characters. On the other hand you might be right that we should maybe improve the query handling itself to avoid errors like that.

2019-08-05 14:36 UTC, aschempp commented
Well can't I encode a `%` in the URL so it "correctly" arrives in the request path to Contao?

2019-08-05 14:57 UTC, qzminski commented
You can encode `%` with the following sequence of characters: `%25`.

2019-08-12 13:50 UTC, leofeyer commented
@aschempp What is the status of this PR?

2019-08-13 07:27 UTC, aschempp commented
🤷‍♂ it is not my PR, I hoped @qzminski would continue to work on it?

2019-08-13 07:30 UTC, qzminski commented
@aschempp I have already presented my solution to this problem. If you would like me to approach it in a different way, just tell me how to proceed.

2019-08-13 07:38 UTC, aschempp commented
My previous comment:

> What if I enter a % in the alias field in the back end? Shouldn't we make sure the database query does correctly handle % characters?

> Also, there are functional tests for the routing, we should update them for this case. A unit test is not sufficient here.

You're obviously free to disagree with any of it, but until now you didn't so I assumed that would be the next attempt 😊

2019-08-26 12:22 UTC, qzminski commented
I am not convinced to what you're saying and I would like to hear feedback from others.

2020-07-30 15:25 UTC, leofeyer commented
We have discussed this in Mumble on July 30th and we share Andy's view that the fix cannot be correct. Can you set up a functional test to reproduce this? A unit test is not suited here.

2020-07-30 15:36 UTC, fritzmg commented
This can be reproduced in any Contao installation without any pre-requisites: https://contao.org/en/drachenlochmuseum-v%25c3%25a4ttis.html

2020-07-30 15:56 UTC, ausi commented
The issue is because of the following lines:
https://github.com/contao/contao/blob/025e2f58f31b9c2738c16713fb9deac4acc3342b/core-bundle/src/Routing/RouteProvider.php#L485
https://github.com/contao/contao/blob/025e2f58f31b9c2738c16713fb9deac4acc3342b/core-bundle/src/Routing/RouteProvider.php#L496

The `quote()`ing has to be removed and the parameters have to be passed via `?` placeholders.

2020-08-03 19:38 UTC, aschempp commented
I have updated the pull request according to our discussion on Mumble. Be careful when merging this into 4.10, because the `RouteProvider` might have changed significantly…

2020-08-03 19:41 UTC, aschempp approved these changes

2020-08-04 06:55 UTC, merged

2020-08-04 06:55 UTC, leofeyer commented
Thank you @qzminski.