Correctly generate the file tree for admin users
contao/contao pull request #6238
Opened 2023-07-24 14:54 UTC by leofeyer

Fixes #6211

2023-07-24 15:40 UTC, aschempp requested changes

2023-07-24 15:40 UTC, aschempp commented on core-bundle/contao/drivers/DC_Folder.php
> +		elseif (BackendUser::getInstance()->isAdmin)
```suggestion
		elseif (System::getContainer()->get('security.helper')->isGranted('ROLE_ADMIN')
```

// untested code! 😉

2023-07-25 12:01 UTC, leofeyer commented on core-bundle/contao/drivers/DC_Folder.php
> +		}
FYI, this is the exact same code as before. It was removed in https://github.com/contao/contao/pull/6124/files#diff-7343995af85db55c2af9e4328df59608eb269260447eea2aa1f1492da27466c2L425-L428 but it should not have.

2023-07-25 12:07 UTC, ausi approved these changes

2023-07-25 14:55 UTC, merged