Do not inline preview images
contao/contao pull request #6299
Opened 2023-08-15 11:11 UTC by leofeyer

Fixes #6270

2023-08-15 11:38 UTC, fritzmg submitted a review, later dismissed

2023-08-15 11:39 UTC, Toflar submitted a review, later dismissed

2023-08-16 06:09 UTC, aschempp approved these changes

2023-08-16 06:11 UTC, aschempp requested changes
Sorry about the approval... how do we fix https://github.com/contao/core-bundle/issues/636 then?

If a file is in a protected folder, it would not be visible in the file manager if it does not need resizing. Or can we force-resize an image?

2023-08-16 07:21 UTC, fritzmg commented
@aschempp see https://github.com/contao/contao/issues/6270#issuecomment-1669450744

2023-08-16 15:21 UTC, ausi submitted a review, later dismissed

2023-08-17 06:03 UTC, leofeyer commented
After merging #6302, there are no more changes in this pull request, so I will close it now.

2023-08-17 06:03 UTC, closed without merging