Fix warnings when using `Image::get`
contao/contao pull request #6309
Opened 2023-08-17 11:10 UTC by fritzmg

If you use `Image::get` with a predefined image size, the following warning may occur:

```
ErrorException:
Warning: Undefined array key "height"

  at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Image.php:847
  at Contao\Image::getImageSizeConfig('_test')
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\Image.php:790)
  at Contao\Image::create(object(File), '_test')
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\Image.php:880)
  at Contao\Image::get('files/content/test.jpg', '', '', '_test')
```

This warning is only logged to the system log.

#### Reproduction

```yaml
contao:
    image:
        sizes:
            test:
                width: 100
```
```php

<img src="<?= Contao\Image::get('files/content/test.jpg', 0, 0, '_test') ?>">
```

2023-08-17 13:14 UTC, ausi commented
Should we maybe use proper defaults in the container configuration instead? https://github.com/contao/contao/blob/c2757f14f48da02bd43d3230478c3c099689b43f/core-bundle/src/DependencyInjection/Configuration.php#L240-L243

2023-08-17 13:36 UTC, fritzmg commented
May be, but I think the same would need to be applied to `tl_image_size` and `tl_image_size_item` because the default for `width`, `height` and `zoom` is currently `null` there.

2023-08-17 13:44 UTC, ausi commented
If `tl_image_size` and `tl_image_size_item` also default to null then this fix is probably right :+1:

2023-08-17 13:44 UTC, ausi approved these changes

2023-08-17 13:45 UTC, ausi requested changes

2023-08-17 13:45 UTC, ausi commented on core-bundle/src/Resources/contao/library/Contao/Image.php
> +		$imageSize->resizeMode = $predefinedSizes[$size]['resizeMode'] ?? 'proportional';
```suggestion
		$imageSize->resizeMode = $predefinedSizes[$size]['resizeMode'] ?? 'crop';
```
The default is `crop` I think.

2023-08-17 17:16 UTC, ausi approved these changes

2023-08-21 08:41 UTC, merged

2023-08-21 08:41 UTC, leofeyer commented
Thank you @fritzmg.