Fix the news URL cache when archive is added
contao/contao pull request #6460
Opened 2023-10-23 19:31 UTC by aschempp

Without this, the archive query parameter could be included or not in the URL depending on a previous call that was cached.

2023-10-23 19:34 UTC, fritzmg reviewed
This puts the value of `Input::get('month')` into the cache as well, which could, in theory, also be different (through `Input::setGet`). I think the original intention was to not cache the `?month=` query parameter at all. We could change line 460 to

```php
return self::$arrUrlCache[$strCacheKey] . '?month=' . Input::get('month');
```

instead.

2023-10-24 15:19 UTC, aschempp commented
That would not work because the cache can contain a URL that does not support `month`. It is only added for the default redirect page, not for any other …

2023-10-24 15:20 UTC, aschempp commented
I think it is **very** unlikely the `month` will change during a page request, but you're right it's technically possible.

2023-11-03 15:28 UTC, leofeyer requested changes
I don‘t think that this is the right solution. Shouldn‘t we add the `if ($blnAddArchive && Input::get('month'))` logic to the early return condition instead?

2023-11-17 14:09 UTC, aschempp commented
see https://github.com/contao/contao/pull/6460#issuecomment-1777465280

2023-11-17 14:11 UTC, aschempp commented
The cache key now contains the actual month, so two separate months would generate correct cache URLs

2023-11-17 14:15 UTC, fritzmg approved these changes

2023-11-17 16:44 UTC, leofeyer commented
The cache exists in the object only, right? Because if we would write actual cache files, adding the user input parameter would be a security vulnerability. @ausi /cc

2023-11-21 06:08 UTC, aschempp commented
the cache is only for the current request, nothing else (`self::$arrUrlCache`).

2023-11-27 16:14 UTC, ausi approved these changes

2023-11-28 08:47 UTC, leofeyer approved these changes

2023-11-28 08:49 UTC, merged

2023-11-28 08:49 UTC, leofeyer commented
Thank you @aschempp.