Add more security voters
contao/contao pull request #6469
Opened 2023-10-27 11:04 UTC by leofeyer

This applies the changes from #4648 to all similar cases.

2023-10-30 09:06 UTC, aschempp requested changes
Looks good so far! Two things I notice:

1. all the voters look very similar. I think we should have an abstract that only provides the supported table name and expects an action to vote on.
2. if we have full permissions implemented, we can also remove all the button callbacks in the DCA 🎉

2023-10-30 10:41 UTC, leofeyer commented
Regarding 1: What about `AbstractListViewAccessVoter`, `AbstractParentViewAccessVoter` and `AbstractTreeViewAccessVoter`?

Regarding 2: Do I have to change anything in this PR?

2023-10-30 11:02 UTC, aschempp commented
1: What's the difference betwee these abstract? To me the abstract should simple always return the same `supports` and have an `hasAccess` that is called in the `vote` method for the actual attribute. And the abstract would automatically make sure it only returns `ACCESS_DENIED`. I can do a PR on your branch if you'd like that.

2: I think these DCAs only have the default operations, so you can simply remove the `list.sorting.operations` completely and they will be auto-generated.

2023-11-12 22:09 UTC, aschempp commented
see https://github.com/leofeyer/contao/pull/7 for an example for calendars.

2023-11-24 16:37 UTC, aschempp commented
can we get this into 5.3? 🙃

2023-12-06 16:33 UTC, aschempp reviewed
As discussed I have updated the PR and merged my abstract. Also added more voters for the child tables because their permissions are also pretty simple to test.

I wonder why the voters are all names `...AccessVoter`, the `Access` part does not make much sense to me. I would suggest to remove this everywhere, but for now I added it because it was already there. WDYT @contao/developers ?

2023-12-14 14:04 UTC, aschempp requested changes

2023-12-14 14:04 UTC, aschempp commented on core-bundle/src/Security/Voter/DataContainer/FavoritesVoter.php
> +            default => false,
this should also be removed

2023-12-14 14:04 UTC, aschempp commented on news-bundle/src/Security/Voter/NewsArchiveAccessVoter.php
> +            default => false,
this should also be removed

2023-12-15 08:01 UTC, aschempp approved these changes

2023-12-15 08:20 UTC, merged