Fix insert tags being replaced in the back end (again)
contao/contao pull request #6479
Opened 2023-11-01 11:19 UTC by fritzmg

Via #6478 I noticed that insert tags are being replaced in the back end again, at least for certain content elements. This PR adds the missing `as_editor_view` checks to the affected templates.

2023-11-01 15:10 UTC, ausi commented
Would it make sense to add a parameter to the `insert_tag` filters so that we can just pass `as_editor_view`?
So instead of:
```twig
{% if as_editor_view %}{{ headline }}{% else %}{{ headline.text|insert_tag_raw }}{% endif %}
{% if as_editor_view %}{{- item|raw -}}{% else %}{{- item|insert_tag|raw -}}{% endif %}
```
we could just write:
```twig
{{ headline.text|insert_tag_raw(as_editor_view) }}
{{- item|insert_tag(as_editor_view)|raw -}}
```
Thinking this further, would it be possible setting the default value of this parameter automatically to the value of `as_editor_view`? So that it can be used like:
```twig
{{ foo|insert_tag }} {# Would automatically adhere to as_editor_view #}
{{ foo|insert_tag(true) }} {# Would ALWAYS replace insert tags #}
{{ foo|insert_tag(bar) }} {# Would replace insert tags only if bar is set to true #}
```

2023-11-02 07:42 UTC, m-vo commented
> Thinking this further, would it be possible setting the default value of this parameter automatically to the value of as_editor_view? So that it can be used like:

Yes, filtets/functions can be marked as context sensitive and then receive the context as an input parameter.

2023-11-02 08:07 UTC, fritzmg commented
Makes sense for sure - but would be a new feature for 5.x

2023-11-02 08:31 UTC, m-vo commented
We could also implement this as a bugfix IMHO. I'm not sure we should add more complexity to the templates. But I also don't like too much magic... 🙃

Maybe something to discuss?

2023-11-02 08:33 UTC, fritzmg commented
Well, for 5.2 it should definitely fixed with this PR in any case as it's the same as we currently have in all the other templates that do check for `as_editor_view`.

2023-11-02 10:42 UTC, ausi approved these changes

2023-11-02 10:45 UTC, ausi requested changes
Whitespace needs to be fixed (see failing tests)

2023-11-02 10:45 UTC, ausi commented on core-bundle/contao/templates/_new/content_element/list.html.twig
> +    {% if as_editor_view %}{{- item|raw -}}{% else %}{{- item|insert_tag|raw -}}{% endif %}
```suggestion
    {%- if as_editor_view %}{{ item|raw }}{% else %}{{ item|insert_tag|raw }}{% endif -%}
```

2023-11-02 10:45 UTC, ausi commented on core-bundle/contao/templates/_new/content_element/table.html.twig
> +    {% if as_editor_view %}{{- cell|trim|replace({'\n': '<br>\n'})|raw -}}{% else %}{{- cell|trim|replace({'\n': '<br>\n'})|insert_tag|raw -}}{% endif %}
```suggestion
    {%- if as_editor_view %}{{ cell|trim|replace({'\n': '<br>\n'})|raw }}{% else %}{{ cell|trim|replace({'\n': '<br>\n'})|insert_tag|raw }}{% endif -%}
```

2023-11-02 10:48 UTC, ausi commented
> Makes sense for sure - but would be a new feature for 5.x

Moved to its own ticket: https://github.com/contao/contao/issues/6482

2023-11-02 11:15 UTC, ausi requested changes

2023-11-02 11:15 UTC, ausi commented on core-bundle/contao/templates/_new/component/_headline.html.twig
> +        {% if as_editor_view %}{{ headline }}{% else %}{{ headline.text|insert_tag_raw }}{% endif %}
```suggestion
        {% if as_editor_view %}{{ headline.text }}{% else %}{{ headline.text|insert_tag_raw }}{% endif %}
```

2023-11-02 11:25 UTC, fritzmg commented on core-bundle/contao/templates/_new/component/_headline.html.twig
> +        {% if as_editor_view %}{{ headline }}{% else %}{{ headline.text|insert_tag_raw }}{% endif %}
woops :)

2023-11-02 12:59 UTC, ausi approved these changes, later dismissed

2023-11-03 17:40 UTC, leofeyer requested changes
Please review https://github.com/fritzmg/contao/pull/4 before we merge this.

2023-11-05 10:00 UTC, m-vo approved these changes, later dismissed
LGTM. Regarding whitespaces I think the one-liners would also be fine. We want to shorten them to a neater looking variant (still a one-liner) anyway and then there will be less changed lines.

2023-11-06 11:16 UTC, leofeyer approved these changes, later dismissed

2023-11-06 11:29 UTC, leofeyer approved these changes

2023-11-06 11:33 UTC, merged

2023-11-06 11:34 UTC, leofeyer commented
Thank you @fritzmg.