Automatically translate the default maintenance template
contao/contao pull request #6494
Opened 2023-11-07 16:34 UTC by Toflar

Here's a solution that covers the 99% case. Most people won't adjust the maintenance template and so we can use JS to translate it according to the user's browser language if we have translations available.

So for German, this now looks like this automatically:

<img width="850" alt="Bildschirmfoto 2023-11-07 um 17 24 20" src="https://github.com/contao/contao/assets/481937/f586f6f4-9158-4b6f-a0c4-d69e1831964e">

We might improve this even more in the future by using the upcoming Symfony translation support for JS but this is still experimental and I don't know if this is really a good fit anyway. The reason for that is that it would tie the maintenance mode to require a running system again.
I know that we are already sort of relying on the fact that the container still works as we're using Twig when using `contao:maintenance enable`. So I guess this is kind of meant to work like "in case the System does work, we can use your template, if not, then you have to copy something to `var/maintenance.html` yourself".

So Twig should be fine. But using dynamic translations would probably be a bit too much.

2023-11-12 12:08 UTC, ausi requested changes
LGTM apart from the two small changes 👍

2023-11-12 12:08 UTC, ausi commented on core-bundle/templates/Error/service_unavailable.html.twig
> +                    el.innerHTML = trans;
```suggestion
                    el.textContent = trans;
```

If I’m right, the messages get encoded in the twig template, so we should not allow HTML here I think.

2023-11-12 12:08 UTC, ausi commented on manager-bundle/src/Command/MaintenanceModeCommand.php
> +        foreach (array_keys($this->locales->getEnabledLocales()) as $locale) {
```suggestion
        foreach ($this->locales->getEnabledLocaleIds() as $locale) {
```

2023-11-13 17:26 UTC, ausi submitted a review, later dismissed

2023-11-14 10:32 UTC, leofeyer approved these changes

2023-11-14 10:32 UTC, merged

2023-11-14 10:32 UTC, leofeyer commented
Thank you @Toflar.