Extended docs for the Crawler in the back end
contao/contao pull request #6503
Opened 2023-11-09 13:09 UTC by Toflar

2023-11-09 13:15 UTC, bytehead approved these changes, later dismissed

2023-11-10 12:51 UTC, Toflar commented
This is ready now.

2023-11-10 16:05 UTC, leofeyer requested changes
Just requesting changes so we don‘t accidentally merge this one before #6507 has been resolved.

2023-12-11 15:23 UTC, leofeyer commented
The translation file should have a `%s` wildcard and the URL should be added using `sprintf()`.

https://github.com/contao/contao/blob/d50e67901a36692f57f1a27680dced916ce6ddd6/core-bundle/contao/languages/en/default.xlf#L1205-L1207

https://github.com/contao/contao/blob/d50e67901a36692f57f1a27680dced916ce6ddd6/core-bundle/contao/controllers/BackendMain.php#L187

2023-12-11 16:11 UTC, Toflar commented
Ah right, that's why it was blocked. Updated - while doing that I also migrated to the translator because we had to do this anyway at some point.

2023-12-13 11:03 UTC, leofeyer commented
I would have preferred it if you had just changed the language string. 🙈

2024-01-08 09:03 UTC, bytehead approved these changes

2024-01-08 16:27 UTC, fritzmg approved these changes

2024-01-19 16:59 UTC, leofeyer commented
> Moreover, make sure you analyze the debug log to see which URLs are crawled exactly. You can ask Contao to skip links from being crawled. Please refer to the [Contao docs](https://to.contao.org/docs/crawler) for more information.

What are you trying to tell the user? Is it _the crawler might crawl fewer URLs than you expect, so check the debug log_ or is it _you can exclude links from crawling_? I don‘t quite understand the intention here.

2024-01-26 14:01 UTC, Toflar commented
> you can exclude links from crawling

This one. If the log contains URLs you don't want to have crawled (aka it takes too long), you can exclude them.

2025-06-06 15:36 UTC, closed without merging