Fix table picker provider with parents
contao/contao pull request #6523
Opened 2023-11-14 11:12 UTC by ausi

Followup to #6504, #6510 and #6517

2023-11-14 11:14 UTC, ausi commented
We should wait for @aschempp s approval

2023-11-14 16:44 UTC, aschempp requested changes

2023-11-14 16:44 UTC, aschempp commented on core-bundle/src/Picker/AbstractTablePickerProvider.php
> +        [$ptable, $pid, $id] = $this->getPtableAndPid($table, $config->getValue());
this should early-return if `$config->getValue()` is empty in the first place. Maybe in the method or maybe here?

2023-11-14 16:51 UTC, ausi commented on core-bundle/src/Picker/AbstractTablePickerProvider.php
> +        [$ptable, $pid, $id] = $this->getPtableAndPid($table, $config->getValue());
it does not execute a DB query if the value is empty.

2023-11-14 22:40 UTC, aschempp approved these changes

2023-11-21 11:54 UTC, merged

2023-11-21 11:54 UTC, leofeyer commented
Thank you @ausi.