Allow HEIC image format
contao/contao pull request #6540
Opened 2023-11-16 12:15 UTC by fritzmg

In `tl_image_size::getSupportedFormats()` we specifically check for `heic` (amongst others).

https://github.com/contao/contao/blob/0435a23d21a1c22fbc7e595fe5b3f56b91a42a2b/core-bundle/src/Resources/contao/dca/tl_image_size.php#L455-L463

However, in `tl_image_size::getFormats()` (the `options_callback` for `tl_image_size.formats`) we then filter these options according to `contao.image.valid_extensions`.

https://github.com/contao/contao/blob/0435a23d21a1c22fbc7e595fe5b3f56b91a42a2b/core-bundle/src/Resources/contao/dca/tl_image_size.php#L405-L410

I think we should add `heic` to the `contao.image.valid_extensions` by default as dealing with that image format is more common now (due to Apple devices). Also Instagram's API provides the images in HEIC (although allegedly these are just JPEGs with the wrong file extension; I haven't validated this). Thus there is a need to convert these images to `jpg` and `webp` for displaying them on a web page.

@ausi wdyt?

2023-11-16 13:11 UTC, ausi commented
I don’t think we can add this to 4.13 as a bugfix as it would generate exceptions here: https://github.com/contao/contao/blob/0435a23d21a1c22fbc7e595fe5b3f56b91a42a2b/core-bundle/src/Image/LegacyResizer.php#L163

AFAIK we only wanted to add formats by default that are supported by the default GD extension, which is not the case for heif/heic yet: https://bugs.php.net/bug.php?id=80828

2023-11-16 13:39 UTC, fritzmg commented
I see. Should we implement the `+`/`-` syntax for the config for appending additional image formats instead?

2023-11-17 08:10 UTC, ausi requested changes
https://github.com/contao/contao/pull/6540#issuecomment-1814410895

2024-09-09 16:18 UTC, fritzmg commented
Superseded by #7478

2024-09-09 16:18 UTC, closed without merging