Remove unnecessary wrapping of the exception when used in a TWIG tempate
contao/contao pull request #6579
Opened 2023-11-29 10:40 UTC by md-netdesign

Fixes #6548

This fix remove the wrapping of the thrown exception, when a variable is used in a TWIG template.

Also, this will allow the ResponseException from the download content element in a news/calendar event TWIG template to bubble up so Contao can correctly handle it and initiate the file download.

With this fix, one can directly use `{{ text|raw }}` in a news/calendar event TWIG template instead of the work-around with `{{ text.invoke()|raw }}`.

2023-11-29 12:35 UTC, ausi approved these changes

2023-11-29 12:38 UTC, ausi requested changes
We need to adapt the unit test `Contao\CoreBundle\Tests\Twig\Interop\ContextFactoryTest::testEnhancesErrorMessageInCallableWrappersIfStringAccessFails` too.

2023-11-29 12:39 UTC, md-netdesign commented
Forgot about that. Sorry, I will do so. 🙂

2023-11-29 12:45 UTC, md-netdesign commented
The test completes locally now.

2023-11-29 12:55 UTC, ausi approved these changes
Failing CI is unrelated, see https://github.com/contao/contao/pull/6582

2023-11-29 16:47 UTC, merged

2023-11-29 16:47 UTC, leofeyer commented
Thank you @md-netdesign.

2023-11-30 10:46 UTC, leofeyer commented
Turns out the failing `--prefer-lowest` tests were not unrelated. 🙈 

<img width="952" alt="" src="https://github.com/contao/contao/assets/1192057/11b5c4eb-5548-4547-aadc-42ba1b7c127b">

The changes from this PR are only compatible with Twig 3.8, so we either have to raise the minimum version or to address this issue.

2023-11-30 10:54 UTC, md-netdesign commented
Okay, I'll look into it and report back!

2023-11-30 11:22 UTC, ausi commented
The related change seems to be this one: https://github.com/twigphp/Twig/pull/3830

I think requiring `^3.8.0` is probably the right way here.

2023-11-30 11:55 UTC, md-netdesign commented
That's correct.

If we would want to support older TWIG versions, we could catch the error in the `__toString` method, convert it to a `RuntimeException` so TWIG will wrap it into the desired `RuntimeError`. The test case would not need to be adjusted.

```php
/**
 * Called when evaluating "{{ var }}" in a Twig template.
 */
public function __toString(): string
{
    try {
        return (string) $this();
    } catch (\Error $e) {
        throw new \RuntimeException($e->getMessage(), 0, $e);
    }
}
```

Otherwise requiring TWIG `^3.8.0` is necessary.

Which version do you prefer?

2023-11-30 12:25 UTC, leofeyer commented
I‘d say let‘s wait and see if `^3.8` causes any problems. WDYT?

2023-11-30 13:26 UTC, md-netdesign commented
PR for TWIG version is in #6588.