Enable PHPStan bleeding edge
contao/contao pull request #6580
Opened 2023-11-29 10:42 UTC by leofeyer

I deliberately did not include the `bleedingEdge.neon` file in case you wonder.

2023-11-29 10:55 UTC, bytehead approved these changes

2023-11-29 11:07 UTC, aschempp requested changes

2023-11-29 11:07 UTC, aschempp commented on core-bundle/src/Cache/EntityCacheTags.php
> -        if ($this->isModel($target)) {
this is not the same. The previous check allowed for `$target` to be a string of a class, the new check does not

2023-11-29 11:51 UTC, leofeyer commented on core-bundle/src/Cache/EntityCacheTags.php
> -        if ($this->isModel($target)) {
The previous code was wrong. The `getTagForModelInstance()` expects a `Model` instance, so we must never pass a string. Also, the string case is already handled in line 126.

2023-11-29 12:31 UTC, ausi approved these changes

2023-11-29 12:51 UTC, merged

2023-12-03 17:57 UTC, m-vo commented on core-bundle/src/Cache/EntityCacheTags.php
> -        if ($this->isModel($target)) {
Just for the record: I do not think the previous code was wrong, this change is just CS (or maybe an optimization?). For the non-string case, which is made sure in L126,  `is_subclass_of` is identical to `instanceof` here (`Model` is abstract and all instances are always of true subclasses).

Or did I miss something? Then we should also adjust the unit tests.