Update cal_mini.html5
contao/contao pull request #6640
Opened 2023-12-19 22:01 UTC by kroerig

Vorschlag aus https://community.contao.org/de/showthread.php?86096-CONTAO-4-13-35-Minikalender-nicht-barrierefrei

2023-12-19 22:41 UTC, Toflar requested changes
Thanks for the proposal! ❤️  This wouldn't work when placed multiple times on the same page. You would end up with multiple identical `id` attributes -> invalid HTML. You would need to generate some dynamic ID here. See `mod_navigation.html5` for example 😊

2023-12-19 23:12 UTC, fritzmg commented
Also I think the `<td>` should also be assigned to each day header, not just the current month.

2023-12-19 23:21 UTC, ausi commented on calendar-bundle/contao/templates/calendar/cal_mini.html5
> +          <td<?php if (!empty($day['class'])): ?> class="<?= $day['class'] ?>"<?php endif; ?> headers="month"><a href="<?= $day['href'] ?>" title="<?= $day['title'] ?>"><?= $day['label'] ?></a></td>
This should point to both, the `month` and the `<?= $day['name'] ?>` header I thinnk.

2024-03-07 16:45 UTC, leofeyer commented on calendar-bundle/contao/templates/calendar/cal_mini.html5
> +    <th id="previous" class="head previous"><?php if ($this->prevHref): ?><a href="<?= $this->prevHref ?>" title="<?= $this->prevTitle ?>" data-skip-search-index><?= $this->prevLabel ?></a><?php else
This will create problems if there are multiple mini calendars on the same page. You should add the module ID as suffix.

2024-03-07 16:45 UTC, ausi commented on calendar-bundle/contao/templates/calendar/cal_mini.html5
> +    <th id="next" class="head next"><?php if ($this->nextHref): ?><a href="<?= $this->nextHref ?>" title="<?= $this->nextTitle ?>" data-skip-search-index><?= $this->nextLabel ?></a><?php else: ?>&nbs
```suggestion
    <th id="next_<?= $this->id ?>" class="head next"><?php if ($this->nextHref): ?><a href="<?= $this->nextHref ?>" title="<?= $this->nextTitle ?>" data-skip-search-index><?= $this->nextLabel ?></a><?php else: ?>&nbsp;<?php endif; ?></th>
```
All ID’s should be unique

2024-06-25 12:43 UTC, closed without merging