Move ptable logic from tl_content to DC_Table
contao/contao pull request #6645
Opened 2023-12-20 11:46 UTC by ausi

This removes the need to check for `Input::get('ptable')` in the tl_content DCA. Not sure if this is the right approach though.

2023-12-20 11:49 UTC, aschempp commented
Looks like we should have a permission voter before we can make this improvement? 🤔

2023-12-20 14:45 UTC, ausi commented
> Looks like we should have an access voter before we can make this improvement? 🤔

Why?

2023-12-20 15:42 UTC, leofeyer requested changes
The changes do not work, I‘m afraid. I added them to #6648 but I was not able to edit the new element as a non-admin user. (I was able to edit the child elements, though.)

2023-12-20 17:34 UTC, ausi commented
> The changes do not work, I‘m afraid.

Should be fixed in e7002e192d2c869c9561d097741c977623aceae4

2023-12-21 10:54 UTC, leofeyer approved these changes

2023-12-21 10:54 UTC, merged

2023-12-21 10:54 UTC, leofeyer commented
Thank you @ausi.