Always allow ReadAction in FrontendModulesVoter
contao/contao pull request #6890
Opened 2024-02-13 12:53 UTC by bezin

Fixes #6887

Following a comment in the test case I was aware that I always have to allow `ReadAction` for any type, but the implementation was not quite there yet …

2024-02-13 16:33 UTC, aschempp requested changes
I think this should be moved above all other calls, also not to check for the back end user etc.

2024-02-14 07:54 UTC, aschempp approved these changes

2024-02-14 08:07 UTC, Toflar approved these changes

2024-02-14 08:33 UTC, merged

2024-02-14 08:33 UTC, leofeyer commented
Thank you @bezin.