Correctly generate the URLs to subscribe to comments
contao/contao pull request #6943
Opened 2024-02-27 11:10 UTC by leofeyer

This prevents double slashes in URLs when subscribing to comments now that we use absolute paths everywhere. We did the same here already:

https://github.com/contao/contao/blob/0eac53c903c296d0b2fb7725c4eda8bf1b418e25/newsletter-bundle/contao/classes/Newsletter.php#L245

2024-02-27 11:17 UTC, aschempp commented
Shoulnd't this use the ContentUrlGenerator on CommentsModel instead? I could give that a try if you like.

2024-02-27 11:24 UTC, leofeyer commented
Not necessary IMHO. But if you want to do it, maybe you can also adjust the newsletter bundle?

2024-02-27 13:11 UTC, aschempp commented
> maybe you can also adjust the newsletter bundle?

What's with the newsletter bundle? It already has a route provider?

2024-02-27 13:42 UTC, aschempp requested changes
I did look into adding a content URL generator, but I don't think it makes sense here.

However, this should use `UrlUtil::makeAbsolute()` instead of manually combining the URL and base imho.

2024-02-27 14:54 UTC, leofeyer commented
Of course this could be improved in several ways, but the goal of this PR is to fix the issue, not to refactor the code.

2024-02-27 15:17 UTC, leofeyer commented
Also, please note that the string concatenation is done inside a `while` loop and calling `UrlUtil::makeAbsolute()` instead would negatively impact the performance.

2024-02-27 16:08 UTC, aschempp commented
I disagree. Would we have used the existing helpers, we wouldn't have had the problem we're facing now.

2024-02-27 16:44 UTC, leofeyer commented
I have no idea what you are talking about. The code I changed was already in Contao 3.0.0 and probably even Contao 2 (see [Comments.php#L614](https://github.com/contao/core/blob/3.0.0/system/modules/comments/classes/Comments.php#L614)). The `UrlUtil` class, however, was only added in Contao 4.13.25, so no idea how we _should have used the existing helpers_ back then. 🤷‍♂️ 

The problem is caused by switching to absolute paths in Contao 5 and `ltrim()` fixes this without the performance overhead that `UrlUtil::makeAbsolute()` would add inside a `while` loop.

2024-02-28 07:16 UTC, aschempp commented
>  `ltrim()` fixes this without the performance overhead that `UrlUtil::makeAbsolute()` would add inside a `while` loop.

It will fix it until the URLs change. If the URLs are e.g. absolute at some point for some reason, this code will break. Using the utility will not break, because it is supposed to handle **all** cases. That's why we have utilities, no?

/cc @contao/developers

2024-02-28 10:48 UTC, ausi approved these changes

2024-02-28 12:47 UTC, merged