Fixed frontend module permissions
contao/contao pull request #6993
Opened 2024-03-11 09:42 UTC by aschempp

I have found several issues in the current frontend module permissions.

1. it did not check access to the module itself
2. I could not find that `USER_CAN_DELETE_FRONTEND_MODULE` would be for, I don't think that actually worked
3. Voters should not vote on the user object themselves, they all currently forward to the `BackendPermissionVoter`

/cc @bezin

2024-03-11 22:27 UTC, aschempp commented
I also noticed that the permission voter currently allows access to all modules if no module permissions are given. This is contrary to how any other permissions work, and does not really make much sense because we also have a migration that enables all front end modules for all existing user groups 🤔

2024-03-11 23:37 UTC, aschempp commented
Next issue found:
 1. should a user be able to select a module in the module content element, if no access to that module was given (i.e. see it in the dropdown)?
 2. if yes (and that's the current state), it always renders an edit button, but that will result in an error if access to that module is not given.

2024-03-12 07:08 UTC, bezin commented
> I also noticed that the permission voter currently allows access to all modules if no module permissions are given. This is contrary to how any other permissions work, and does not really make much sense because we also have a migration that enables all front end modules for all existing user groups 🤔

Yes, I agree. My intention was to imitate the behaviour of content element permissions, so I checked how it was implemented there, but I was mistaken, I guess. 

Front-end modules must be explicitly allowed, otherwise no access is permitted (like content elements).

2024-03-12 11:01 UTC, leofeyer requested changes
Something seems to be wrong, because now a regular user can delete all front end modules and not just the types that are allowed for them.

2024-03-12 13:02 UTC, aschempp commented
> Something seems to be wrong, because now a regular user can delete all front end modules and not just the types that are allowed for them.

Fixed, the service was not correctly registered because I renamed the class 🙈

2024-03-12 14:21 UTC, leofeyer approved these changes

2024-03-12 14:21 UTC, leofeyer commented
Thank you @aschempp.

2024-03-12 14:23 UTC, merged