Add basic support for hotwired/turbo in the backend
contao/contao pull request #7011
Opened 2024-03-12 14:44 UTC by m-vo

This is the first attempt to add Turbo in the backend. This does not yet enable frames or uses streams at any place but enables drive by default. We will likely need to disable it by default and then enable it again for specific scenarios but this is a good starting point to see what would actually break.

For now these are the things we are doing:

* Disable prefetch for all URLs that contain a `rt` query parameter, so that things like GET requests to delete resources won't be triggered.
* Change the returned status code to 422 in the `BackendController` if a widget was rendered with an error, so that forms still work.
* t.b.c.

2024-03-12 14:52 UTC, fritzmg commented on core-bundle/assets/backend.js
> +})
```suggestion
});
```

2024-03-12 15:27 UTC, ausi commented on package.json
>          "@hotwired/stimulus-webpack-helpers": "^1.0.1",
```suggestion
        "@hotwired/stimulus": "^3.2.2",
        "@hotwired/stimulus-webpack-helpers": "^1.0.1",
        "@hotwired/turbo": "^8.0.4",
```

2024-03-12 15:27 UTC, ausi commented on package.json
> +    },
```suggestion
```

2024-03-12 21:54 UTC, ausi commented on core-bundle/assets/backend.js
> +    window.fireEvent('domready');
```suggestion
    if (!document.body.mooDomreadyFired) {
        document.body.mooDomreadyFired = true;
        window.fireEvent('domready');
    }
```

2024-03-12 22:23 UTC, fritzmg requested changes
There are two issues that I noticed:

* When going from any page to the file manager, there will be a JS error regarding DropZone. This is because the DropZone JavaScript is only added there - which is ignored by Turbo by default (without `data-turbo-track="reload"`).
* For some reason the navigation panes in the main nav are getting toggled randomly sometimes, when navigating with Turbo Drive.

2024-03-12 23:04 UTC, fritzmg commented
We also need to change all `form.submit()` calls with `form.requestSubmit()` in order for these form submits to be turböd.

2024-06-27 17:48 UTC, m-vo commented on core-bundle/assets/backend.js
> +    if ((new URLSearchParams(e.target.href)).has('rt')) {
```suggestion
    if ((new URLSearchParams(e.target.href)).has('rt') || e.target.closest('.sf-toolbar') !== null) {
```

2024-06-28 09:44 UTC, m-vo commented
> We also need to change all form.submit() calls with form.requestSubmit() in order for these form submits to be turböd.

Can we do this in a second step? A quick search found two occurrences (one in `DC_Table`, one in `core.js`), but if we replace the call we also slightly change the behavior as `form.requestSubmit()` does not submit a form that does not validate.

2024-06-28 10:09 UTC, fritzmg commented
That should be fine, yes. The form will then just be submitted without Turbo's functionality (i.e. full regular request).

2024-06-28 10:10 UTC, m-vo commented
This should be ready for a first review. I updated the description to reflect the changes.

2024-06-29 13:48 UTC, fritzmg reviewed
Looks good 👍 

I noticed one issue though: the _Debug mode_ button in the back end also prefetches. We should probably disable prefetch for that menu item (otherwises the debug mode is enabled before you even actually clicked on the button).

Also I noticed that we still have some URLs with request tokens that likely don't actually need one, e.g. the child view.

2024-06-29 17:55 UTC, m-vo commented
> I noticed one issue though: the Debug mode button in the back end also prefetches. We should probably disable prefetch for that menu item (otherwises the debug mode is enabled before you even actually clicked on the button).

Good catch! Fixed in dee9c3f951401f3b527371b7960d89656f2c95a3

2024-07-04 10:12 UTC, fritzmg submitted a review, later dismissed

2024-07-04 10:36 UTC, leofeyer commented
I found two minor issues:

---

Go to the template editor and edit the source of a custom template. Do not save but click on the back button instead. The following error occurs in the browser console:

<img width="454" alt="" src="https://github.com/contao/contao/assets/1192057/2ba75b47-bfba-41e6-a1fa-fca65d6c8424">

---

Edit a regular page in the site structure. Do not save but click on the back button instead. The following error occurs in the browser console:

<img width="517" alt="" src="https://github.com/contao/contao/assets/1192057/4441ffd0-6236-4008-9bb9-b7ab94657fa6">

---

Any idea how to fix these?

2024-07-04 10:38 UTC, leofeyer commented
And when I try to save the template, the following error occurs:

<img width="486" alt="" src="https://github.com/contao/contao/assets/1192057/0bb017c9-1b43-4d17-98a7-7daa0b5dc71b">

2024-07-04 19:13 UTC, m-vo commented
I have the feeling this happens, because we use `document.write()` to load the `ace` scripts. :thinking:  I'll have to investigate.

2024-07-04 19:20 UTC, fritzmg commented
If the fix (regarding the template editor) requires too much effort we could add

```php
$GLOBALS['TL_HEAD'][] = '<meta name="turbo-visit-control" content="reload">';
```

here

https://github.com/contao/contao/blob/38c088203098c60ae30b36832e6ec78c8e4ecb17/core-bundle/contao/classes/DataContainer.php#L682-L708

 in the meantime.

2024-07-04 19:26 UTC, m-vo commented
I added two early returns in 02fddd940738122be74159fb0567e84144cb69ee. This is probably not the nicest, but by far the easiest solution I can think of right now.

IMHO the issue can resolve itself when we stop using global JS objects or dynamic script loading with document write.

2024-07-05 10:16 UTC, leofeyer approved these changes

2024-07-05 10:22 UTC, merged

2024-07-05 10:22 UTC, leofeyer commented
Thank you @m-vo.