Fix/page permission
contao/contao pull request #7055
Opened 2024-03-25 06:55 UTC by aschempp

Re-implements https://github.com/contao/contao/pull/7007

DC_Table needs to check for the clipboard content instead of `act = paste` now, to correctly render paste buttons etc.

2024-03-27 09:42 UTC, aschempp commented
also need to check if https://github.com/contao/contao/issues/7043 still works

2024-04-09 08:58 UTC, leofeyer requested changes
> also need to check if https://github.com/contao/contao/issues/7043 still works

It does not for me.

2024-05-07 10:59 UTC, aschempp commented
PR updated, the return URL is now generated by removing the `act` and `mode` parameters that are used to activate paste mode.

2024-05-08 09:42 UTC, leofeyer requested changes
It still does not work, I‘m afraid.

https://github.com/contao/contao/assets/1192057/b63b3468-b761-4eec-ac4a-88220c88878f

2024-06-06 11:53 UTC, aschempp commented
Finally got around to fix this! 🎉

2024-06-18 14:07 UTC, leofeyer approved these changes
Now it works. 🎉

2024-06-18 14:08 UTC, merged

2024-06-18 14:08 UTC, leofeyer commented
Thank you @aschempp.