Render the Contao login page even if the current route is not a Contao page
contao/contao pull request #7077
Opened 2024-04-03 10:15 UTC by aschempp

Fixed point 1 of https://github.com/contao/contao/pull/6805 for Contao 4.13

2024-04-09 12:07 UTC, fritzmg commented
I am not quite sure what to test here. Do you mean a custom controller that has a route starting with `%contao.backend.route_prefix%` but has no `backend` `_scope`?

2024-04-09 12:26 UTC, fritzmg commented
I tried with 

```php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route(path: '%contao.backend.route_prefix%/test')]
class TestController
{
    public function __invoke(): Response
    {
        return new Response('Hello World!');
    }
}
```

But this controller is always rendered, regardless of whether you have a valid back end login or not (as it should, I think?).

2024-04-16 13:40 UTC, aschempp commented
This is not about the back end. I have a custom controller on a custom route, that has `scope = frontend`. The controller checks permissions using Symfony, which works fine because the front end firewall is active. But because it does not have a `pageModel` in the request attributes, the Contao 401 login page is not rendered if access is denied.

2024-05-07 08:20 UTC, fritzmg commented
Ah, I see. I have the same issue within `fritzmg/contao-file-access` - I hacked it in by [executing](https://github.com/fritzmg/contao-file-access/blob/67051626e057c2c00390dedc65769cea99456ca1/src/Controller/AbstractFilesController.php#L96-L105)

```php
$root = $this->findFirstPublishedRootByHostAndLanguage($request->getHost(), $request->getLocale());

if (null !== $root) {
    $root->loadDetails();
    $request->attributes->set('pageModel', $root);
    $GLOBALS['objPage'] = $root;
}
```

This means after this PR this should not be necessary anymore, correct?

2024-05-07 11:46 UTC, fritzmg requested changes
I tested it - but it does not work if you set `contao.legacy_routing: false`. When Legacy Routing is disabled, `Frontend::getRootPageFromUrl()` will simply check for the `pageModel` attribute in the current request, which is of course missing.

https://github.com/contao/contao/blob/d26e0cec7adaf99a6f10c55db5449078ead30552/core-bundle/src/Resources/contao/classes/Frontend.php#L302-L321

2024-05-07 12:32 UTC, aschempp commented
Thanks @fritzmg. I have updated the PR to use other means to find the root page. The used method is deprecated, but since this is not going to be merged upstream I think that should be fine.

2024-05-07 13:08 UTC, fritzmg commented on core-bundle/src/EventListener/PrettyErrorScreenListener.php
> +            $parameters = $this->requestMatcher->matchRequest($request);
Right now it works neither with nor without legacy routing. I think this needs to be changed?

```suggestion
            $parameters = $this->requestMatcher->matchRequest($rootRequest);
```

2024-05-07 13:12 UTC, fritzmg commented
> The used method is deprecated

Btw. which method do you mean? As far as I can see you did not use any deprecated methods 🤔

2024-05-07 13:26 UTC, fritzmg submitted a review, later dismissed

2024-05-08 09:47 UTC, leofeyer commented
Wouldn‘t it be easier to backport the `PageFinder` service? This would also prevent conflicts when merging upstream.

2024-05-15 15:51 UTC, aschempp commented
> Wouldn‘t it be easier to backport the `PageFinder` service? This would also prevent conflicts when merging upstream.

I don‘t think its a good idea to backport this so late in the patch process…

2024-05-17 12:18 UTC, leofeyer commented
Why not? It wouldn‘t break anything and it would ensure upstream mergeability, which is worth much more than following the "no new features in a bugfix release" rule. We could even make the service `@internal` in Contao 4.13, so that nobody uses it, if that is what you‘re worried about.

2024-05-17 12:20 UTC, fritzmg commented
It could also reduce duplicate code in Contao 4.13.

2024-05-21 08:42 UTC, aschempp commented
The `PageFinder` is a feature, it allows a lot more than this bug fix requires. Not sure how we could fix the upstream mergeability issue, but that's a one-time thing, right? I would
1. merge everything before this PR upstream
2. merge this PR
3. merge upstream again, and remove all changes

That should do it?

2024-05-23 11:39 UTC, leofeyer approved these changes

2024-05-23 11:54 UTC, merged

2024-05-23 11:54 UTC, leofeyer commented
Thank you @aschempp.