Correctly check if an error page can be duplicated
contao/contao pull request #7095
Opened 2024-04-05 16:23 UTC by aschempp

Currently, if you have an error_404 (or other error) page in a root page, you cannot duplicate it. That's because the voter checks if such a page already exists in the current root. We need to allow copying if any other root page does not have that type.

2024-04-09 09:47 UTC, leofeyer commented
Isn‘t the permission to copy a page independent of whether there is a root page to paste it?

2024-04-12 10:34 UTC, aschempp commented
we currently prevent to create multiple error_404 etc. pages inside the same root page, because only one should exist.

2024-04-12 13:20 UTC, leofeyer commented
I know. But I should still be able to **copy** it even if there is no option to **paste** it.

2024-04-12 13:30 UTC, aschempp commented
The paste action is already prevented. But why would I copy if I cannot paste it anywhere?

2024-04-12 13:31 UTC, leofeyer commented
> Currently, if you have an error_404 (or other error) page in a root page, you cannot duplicate it.

To prevent issues like this one. 😄

2024-04-12 13:51 UTC, aschempp commented
?? Thats what this PR fixes?

2024-04-12 14:51 UTC, leofeyer commented
You don‘t get the point. The copy operation should **always** be allowed, independent of `hasPageTypeInRoot()`.

2024-04-16 13:36 UTC, aschempp commented
> You don‘t get the point. The copy operation should **always** be allowed, independent of `hasPageTypeInRoot()`.

why? Why would I copy a page if I cannot paste it?

2024-04-16 13:56 UTC, leofeyer commented
Because these are two different operations that have nothing to do with each other.

1. Copy.
2. Paste.

Yes, that fails if a 404 page exists under every root page. But

1. Copy.
2. Delete an existing 404 page.
3. Paste the duplicated page.

would not fail. But your logic prevents the second workflow.

2024-05-02 14:16 UTC, leofeyer commented
As discussed in the Contao call, the copy action and the paste action should be independent from each other if "copy" means "put on clipboard". If the "copy" action duplicates the record directly (e.g. in the list view), copying and pasting should be seen as one operation.

2024-05-02 14:17 UTC, leofeyer requested changes
As discussed in the Contao call, the copy action and the paste action should be independent from each other if "copy" means "put on clipboard". If the "copy" action duplicates the record directly (e.g. in the list view), copying and pasting should be seen as one operation.

2026-03-09 11:00 UTC, closed without merging