Overwrite page metadata before parsing the news article content
contao/contao pull request #7228
Opened 2024-05-21 14:01 UTC by lukasbableck

This PR fixes the fact that the page metadata is overwritten after the content has been generated. The sequence is relevant, for example, if an insert tag is used in the content that outputs the page metadata, e.g. `{{page::pageTitle}}`.
If the page metadata is overwritten afterwards the insert tag will be replaced with page title set in tl_page, with this PR the insert tag is replaced title of the news, as it should be IMO.

2024-05-21 15:14 UTC, fritzmg commented
I am not sure this should be changed. `parseArticles` was always executed _before_ the page meta data was overwritten by the new reader module. The idea might be so that any insert tags within the new content get the _actual_ page title, not the overwritten one. Otherwise `{{page::pageTitle}}` will output the same as `{{news::headline}}` which might not be intentional - and thus this change would be a BC break.

Also, if this is a bug, this needs to be targeted against 4.13.

2024-05-21 15:14 UTC, fritzmg requested changes
I am not sure this should be changed. `parseArticles` was always executed _before_ the page meta data was overwritten by the new reader module. The idea might be so that any insert tags within the new content get the _actual_ page title, not the overwritten one. Otherwise `{{page::pageTitle}}` will output the same as `{{news::headline}}` which might not be intentional - and thus this change would be a BC break.

Also, if this is a bug, this needs to be targeted against 4.13.

2024-05-21 17:46 UTC, lukasbableck commented
Contao 4.13 did not behave the same way, even though the metadata was also overwritten after the content was generated.
That's why I didn't base the PR on 4.13, forgot to mention that, sorry.

For example have a look at those two sites: 
https://c4.web01.bableck.dev/news/test-article.html
https://c5.web01.bableck.dev/news/test-article
Both are exactly the same, the c5 one is just the c4 but updated to Contao 5.3.
IMO both should produce the same result but they don't.
I can provide access to those example sites if needed.

2024-05-22 08:33 UTC, fritzmg commented
That is true.

The difference between Contao 4 and 5 is when insert tags are replaced. In Contao 4 (for this particular case) the insert tags are only replaced when the `fe_page` template gets rendered, so very late in the pipeline. In Contao 5 however insert tags are replaced more granularly - there the are replaced basically everytime a legacy `FrontendTemplate` gets rendered (in Twig it is different - there you specifically have to tell within the template when/where to replace them).

I would however argue that Contao 5 behaves more correctly here.

2024-05-22 08:36 UTC, fritzmg approved these changes
On the other hand - if we ever do implement a `NewsReaderPageController` that actually sets the response context before hand (in order to also fix #6050) we might as well change the order of operations here already beforehand 👍 (the response context code would then be removed anyway).

2024-05-27 14:55 UTC, merged

2024-05-27 14:55 UTC, leofeyer commented
Thank you @lukasbableck.