Allow Symfony 7
contao/contao pull request #7279
Opened 2024-06-12 12:04 UTC by Toflar

5.3 LTS requires Symfony 6.4 LTS as per our roadmap.

This means, Contao 5.4 must allow Symfony 7 components.

Dependencies:

- [x] `contao/manager-plugin`: https://github.com/contao/manager-plugin/pull/56
- [x] `contao/image`: https://github.com/contao/image/pull/104
- [x] `terminal42/service-annotation-bundle`: https://github.com/terminal42/service-annotation-bundle/pull/9
- [x] `terminal42/escargot`: https://github.com/terminal42/escargot/pull/36
- [x] Merge https://github.com/contao/contao/pull/7285 in `5.3`and then uptream into `5.x`

2024-06-12 14:06 UTC, fritzmg commented on calendar-bundle/composer.json
> +        "symfony/phpunit-bridge": "^6.4 || ^7.0 || ^7.0"
```suggestion
        "symfony/http-client": "^6.4 || ^7.0",
        "symfony/phpunit-bridge": "^6.4 || ^7.0"
```

2024-06-13 07:14 UTC, aschempp requested changes

2024-06-13 07:14 UTC, aschempp commented on composer.json
> +        "scheb/2fa-trusted-device": "^7.0",
Version 7 only supports PHP 8.2, but we still support PHP 8.1. There is no other functional difference for us (see https://github.com/scheb/2fa/blob/7.x/UPGRADE.md#6x-to-7x)

```suggestion
        "scheb/2fa-backup-code": "^6.0 || ^7.0",
        "scheb/2fa-bundle": "^6.0 || ^7.0",
        "scheb/2fa-trusted-device": "^6.0 || ^7.0",
```

2024-06-13 07:14 UTC, aschempp commented on core-bundle/composer.json
> +        "scheb/2fa-trusted-device": "^7.0",
```suggestion
        "scheb/2fa-backup-code": "^6.0 || ^7.0",
        "scheb/2fa-bundle": "^6.0 || ^7.0",
        "scheb/2fa-trusted-device": "^6.0 || ^7.0",
```

2024-06-14 07:22 UTC, aschempp commented
see https://github.com/Toflar/contao/pull/16 for fixing the `LocaleSubscriberTest` correctly

2024-06-18 12:01 UTC, Toflar commented
This PR is done and ready for review. What's missing is an upstream merge of 5.3 to 5.x to fix the `LocaleSubscriber` test.
After that, all packages can be updated to Symfony 7 versions except for one:

```
% composer show | grep 6.4                   
symfony/monolog-bridge                             6.4.8                 Provides integration for Monolog with various Symfony components
```

And this, we currently cannot provide because:

```
% composer why-not symfony/monolog-bridge 7.0
symfony/monolog-bridge v7.0.0 requires         monolog/monolog (^3)                     
contao/managed-edition -      does not require monolog/monolog (but 2.9.3 is installed) 
```

So it comes down to https://github.com/contao/contao/pull/7142 to also allow this very last package to be used in v7 :)

2024-06-18 12:38 UTC, ausi submitted a review, later dismissed
❤️

2024-06-24 09:44 UTC, leofeyer commented
#7142 has just been merged 🎉

2024-06-25 08:08 UTC, leofeyer approved these changes

2024-06-25 09:22 UTC, merged

2024-06-25 09:22 UTC, leofeyer commented
Thank you @Toflar.