Fix visibility of .limit_toggler in the backend
contao/contao pull request #7367
Opened 2024-07-25 13:20 UTC by lukasbableck

In Contao 5 if there is enough content in an element for it to be limited the content overlaps the .limit_toggler. This makes the toggler very hard to see. Also the content is cut off right at the border.
With this PR it looks more like Contao 4.13 again, the elements have some padding at the bottom again and the toggler is never below the content.

C4.13
<img width="706" alt="image" src="https://github.com/user-attachments/assets/581a475c-ba75-4039-8bbd-94d693bd0db2">

C5.3 currently
<img width="897" alt="image" src="https://github.com/user-attachments/assets/419115bc-0c4e-4035-b5fb-5b58ec755769">

C5.3 with this change
<img width="976" alt="image" src="https://github.com/user-attachments/assets/5de1266d-b099-4996-bf99-367c198ef272">

2024-07-25 13:24 UTC, bytehead commented
Nice one, I've noticed this myself but didn't investigate 🙃

2024-07-25 13:45 UTC, zoglo commented
I thought I fixed it in #6661

2024-07-25 13:56 UTC, lukasbableck commented
No, https://github.com/contao/contao/pull/6661 only fixed that the toggler was not clickable

2024-07-25 14:19 UTC, asaage commented
I still think it's pretty unnoticable https://github.com/contao/core-bundle/issues/1198

2024-07-25 22:49 UTC, zoglo commented
How about adding this as well:

```diff
.limit_toggler {
	width: 100%;
	position: absolute;
	bottom: 0;
	left: 0;
-	background: var(--content-bg);
+	background: linear-gradient(transparent, var(--content-bg));
	line-height: 11px;
	text-align: center;
	z-index: 1;
}

.limit_toggler button {
	margin: 0;
	padding: 0;
-	border: 0;
+       border: 1px solid var(--border);
	background: var(--content-bg);
	width: 24px;
	line-height: 8px;
	color: var(--gray);
	border-top-left-radius: 2px;
	border-top-right-radius: 2px;
}
```

That one would make it more visible and make sure that peopel see there is more content as well <3

![image](https://github.com/user-attachments/assets/10c952fc-6ddd-4951-a04c-7e9a4fe0e494)
![image](https://github.com/user-attachments/assets/6fadd2a6-e8a0-46f2-a2f6-7085b1405880)

2024-07-29 11:14 UTC, leofeyer commented
I agree that the gradient is the better solution. However, I cannot reproduce the initial problem:

<img width="881" alt="" src="https://github.com/user-attachments/assets/bd991818-43a0-4a2e-8e51-ddc0007776ce">

2024-07-29 11:25 UTC, lukasbableck commented
Apparantly Safari doesn't have that problem, only in Chrome, Firefox and everything based on them it looks like in my screenshot. Didn't notice that until now.

2024-07-29 12:18 UTC, fritzmg commented
I can reproduce the issue in Firefox.

2024-07-29 14:33 UTC, leofeyer commented
Interesting. It seems that Firefox misses a `z-index: 1`.

2024-07-29 14:38 UTC, fritzmg commented
The `order: 3` from `.cte_preview` changes the rendering stack so that `.cte_preview` is rendered _after_ `.limit_toggler` - thus putting the content of `.cte_preview` on top of `.limit_toggler`, which is somewhat expected.

2024-07-29 14:51 UTC, leofeyer commented
I added a separate PR #7374 that just fixes the missing `z-index`. Then we can keep this PR to discuss about the gradient.

<img width="641" alt="" src="https://github.com/user-attachments/assets/e3a29f22-80f3-492c-9c50-42ada5587a47">

<img width="620" alt="" src="https://github.com/user-attachments/assets/7abe2772-a599-4716-8450-7392445d233c">

The problem with the second screenshot is that it still looks like it isn‘t fully expanded, although it is.

2024-07-29 16:08 UTC, lukasbableck commented
Hmm, I can not reproduce that. Tried it in Safari, Firefox and Chrome on Contao 5.3.11.

But I have noticed that a background-color was set for the toggler on hover which looked weird as it was not transparent anymore. This is fixed now.

2024-08-07 16:36 UTC, zoglo commented
@lukasbableck The gradient itself is always visible, however it may overlap and act weird in different browser engines.
We should definitely go with something very specific like this to fix it (feel free to add transitions):
```css
[data-contao--limit-height-target][style*="max-height"] .limit_toggler {
    background: linear-gradient(transparent, var(--content-bg));
}
```

2024-08-08 06:24 UTC, lukasbableck commented
Thanks @zoglo, I have changed that.
Not sure about transitions in this case, gradients can't be easily transitioned anyway AFAIK. IMO it's ok like that.

2024-08-08 13:13 UTC, zoglo commented
@lukasbableck there is one more issue that needs to be fixed

![image](https://github.com/user-attachments/assets/381b5142-e474-4d5f-9e21-6bdf8258fd0c)
The toggler itself needs to be relative to the parent, however you also want it to overlap with the line:

Something like this would be sufficient:
```diff
+[data-contao--limit-height-target] {
+	position: relative;
+}

[data-contao--limit-height-target][style*="max-height"] .limit_toggler {
	background: linear-gradient(transparent, var(--content-bg));
}

.limit_toggler {
	width: 100%;
	position: absolute;
-	bottom: 0;
+	bottom: -1px;
	left: 0;
	line-height: 11px;
	text-align: center;
	z-index: 1;
}

![image](https://github.com/user-attachments/assets/05f2e024-aade-4f17-9d03-51cdae04d2f4)
![image](https://github.com/user-attachments/assets/b379f487-755c-4439-9c4e-02565601359d)

2024-08-08 13:16 UTC, zoglo requested changes

2024-08-08 13:16 UTC, zoglo commented on core-bundle/contao/themes/flexible/styles/main.css
>  	bottom: 0;
@lukasbableck there is one more issue that needs to be fixed

![image](https://github.com/user-attachments/assets/381b5142-e474-4d5f-9e21-6bdf8258fd0c)
The toggler itself needs to be relative to the parent, however you also want it to overlap with the line:

```suggestion
[data-contao--limit-height-target] {
	position: relative;
}

[data-contao--limit-height-target][style*="max-height"] .limit_toggler {
	background: linear-gradient(transparent, var(--content-bg));
}

.limit_toggler {
	width: 100%;
	position: absolute;
	bottom: -1px;
```

Will look like that:

![image](https://github.com/user-attachments/assets/05f2e024-aade-4f17-9d03-51cdae04d2f4)
![image](https://github.com/user-attachments/assets/b379f487-755c-4439-9c4e-02565601359d)

2024-08-08 13:18 UTC, zoglo commented
Do you also want to resolve the conflict :)?

2024-08-08 14:13 UTC, lukasbableck commented
Done 🙂

2024-08-08 17:42 UTC, zoglo approved these changes, later dismissed

2024-08-09 13:22 UTC, leofeyer reviewed
Almost perfect, but I would prefer not to add a border around the toggle. It puts too much emphasize on the element IMHO.

2024-08-09 13:22 UTC, leofeyer commented on core-bundle/contao/themes/flexible/styles/main.css
> +	bottom: -1px;
```suggestion
	bottom: 0;
```

2024-08-09 13:22 UTC, leofeyer commented on core-bundle/contao/themes/flexible/styles/main.css
> +	border: 1px solid var(--border);
```suggestion
	border: 0;
```

2024-08-09 13:35 UTC, zoglo approved these changes, later dismissed

2024-08-09 13:39 UTC, leofeyer approved these changes

2024-08-09 13:40 UTC, leofeyer commented
Thank you @lukasbableck.

2024-08-09 13:42 UTC, merged