Skip database backups if the remaining migrations will not be executed
contao/contao pull request #7376
Opened 2024-07-29 16:35 UTC by fritzmg

Same as https://github.com/contao/contao/pull/7357 for Contao 5.3.

2024-07-29 17:16 UTC, Toflar approved these changes, later dismissed

2024-07-30 09:21 UTC, leofeyer requested changes

2024-07-30 09:21 UTC, leofeyer commented on core-bundle/tests/Command/MigrateCommandTest.php
> +    public function testAbortsEarlyIfNonInteractiveAndThereAreOnlyDropMigrations(): void
This test is wrong. It duplicates the `testAbortsEarlyIfThereAreNoMigrations()` method and only adds `['interactive' => false]` in line 79, but it should add some `DROP` migrations, too. Right now it only works because there are no migrations at all.

2024-07-30 10:08 UTC, leofeyer submitted a review, later dismissed

2024-07-30 10:10 UTC, leofeyer commented on core-bundle/tests/Command/MigrateCommandTest.php
> +                static fn (bool $doNotDropColumns = false): array => $doNotDropColumns ? [] : ['DROP QUERY'],
```suggestion
                static fn (bool $skipDropStatements = false): array => $skipDropStatements ? [] : ['DROP QUERY'],
```

Just a nitpick :)

2024-07-30 10:15 UTC, leofeyer approved these changes

2024-07-30 10:16 UTC, leofeyer commented
Thank you @fritzmg.

2024-07-30 10:16 UTC, merged