Use the correct path prefix in the images loader
contao/contao pull request #7400
Opened 2024-08-01 14:18 UTC by leofeyer

To reproduce, add a preview image to a theme in the back end.

2024-08-01 14:21 UTC, zoglo commented
@leofeyer just tested it - This breaks all other preview images 🙈

2024-08-01 14:40 UTC, zoglo commented
Works after the latest commit.

2024-08-01 15:35 UTC, zoglo requested changes

2024-08-01 15:35 UTC, zoglo commented on core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php
> +                            'sources' => $picture->getSources($this->container->getParameter('contao.web_dir'), $staticUrl),
```suggestion
                            'img' => $picture->getImg($this->container->getParameter('kernel.project_dir'), $staticUrl),
                            'sources' => $picture->getSources($this->container->getParameter('kernel.project_dir'), 
```
This breaks the picture insert tag.
Reverting this change makes the `{{picture::*}}` render correctly in front-end

2024-08-01 16:00 UTC, zoglo commented
The latest change also breaks every image in the frontend.

The previous URLs that was output:
`localhost/assets/images/a/your-image.jpg`

The new one:
`localhost/public/assets/images/a/your-image.jpg` -> 404

2024-08-02 07:52 UTC, leofeyer commented
We have to remove the feature again, I‘m afraid: #7406

2024-08-02 09:58 UTC, closed without merging