Encode mailto addresses in the markdown element
contao/contao pull request #7416
Opened 2024-08-06 09:31 UTC by Toflar

Fixes https://github.com/contao/contao/issues/7414

In markdown, you can have `mailto` adresses with subject etc. and we should also encode those:

```
Hello [foo\@bar.com](mailto:foo@bar.com?subject=Test) whatever.
```

2024-08-06 11:41 UTC, aschempp approved these changes

2024-08-08 10:11 UTC, leofeyer requested changes
E-mail addresses in markdown documents are not encoded in Contao 4.13, either, so this PR should be targeted against the `4.13` branch.

2024-08-08 10:14 UTC, Toflar commented
We don't have Twig in 4.13 nor do we have any such filter there.

2024-08-08 13:21 UTC, leofeyer commented
But we do have two markdown elements (a [new one](https://github.com/contao/contao/blob/4.13/core-bundle/src/Controller/ContentElement/MarkdownController.php) and a [deprecated one](https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/elements/ContentMarkdown.php)) which both do not encode email addresses, either. If that is a bug, it should be fixed in all active versions.

2024-08-08 13:25 UTC, Toflar commented
Sure, but still this requires and extra PR because it's different from this one. So I don't see how this PR requires changes? 🤷‍♂️

2024-08-08 13:46 UTC, leofeyer approved these changes
I guess you‘re right about that 👍

2024-08-08 13:46 UTC, merged

2024-08-08 13:46 UTC, leofeyer commented
Thank you @Toflar.