Show a warning if a personal data module allows to change the password
contao/contao pull request #7443
Opened 2024-08-14 14:49 UTC by leofeyer

<img width="830" alt="" src="https://github.com/user-attachments/assets/55defc83-3406-474e-9b7e-baa3af2f8b69">

In contrast to the personal data module, the change password module requires to enter the old password when setting a new password.

Of course, we could adjust the personal data module accordingly (see #7442 for a proof of concept), but changing your password and editing your personal information in the same form seems like an anti-pattern and is not possible on any of the major websites I use. I am therefore against merging #7442.

2024-08-14 16:38 UTC, ausi approved these changes, later dismissed

2024-08-16 07:12 UTC, aschempp requested changes
I think this message should be displayed globally on the home screen and in the notification bell popup in the back end, not on the module configuration screen. Also, it should only be for admins (or maybe users with acess to the module configuration (including the respective theme))

2024-08-16 10:14 UTC, leofeyer commented
Changed in 9b3a96e1e49ea08cda8ae9371ab8432d87a333b8.

2024-08-16 10:23 UTC, leofeyer commented
> Also, it should only be for admins (or maybe users with acess to the module configuration (including the respective theme))

Changed in 7c0bbbd7f202cdf79bb4013e5af7f7a37266414e.

2024-08-20 09:05 UTC, fritzmg commented
Actually we have an open feature request about this: https://github.com/contao/contao/issues/5196
Parts of it would be implemented by https://github.com/contao/contao/pull/7442
However, even if we remove the ability to change the password - we still have the username left. And the username can currently _only_ be changed in the personal data module.

2024-08-20 09:10 UTC, leofeyer commented
Yes, but there is no additional requirement such as entering the old password before changing the username, so this should be fine.

2024-08-20 09:17 UTC, fritzmg commented
See https://github.com/contao/contao/issues/5196 - we discussed that the password needs to be re-entered when changing the username.

2024-08-20 09:35 UTC, leofeyer commented
The linked issue is old. We meanwhile agreed that users have to be fully authenticated to change their username or 2FA settings. Additionally requiring the password is not a standard practice (at least none of the major website I use does it).

2024-08-22 13:18 UTC, fritzmg approved these changes

2024-08-22 13:19 UTC, ausi approved these changes

2024-08-23 07:10 UTC, merged