Fix undefined CURRENT_ID in news permission check
contao/contao pull request #7460
Opened 2024-08-19 12:06 UTC by aschempp

Fixes an issue reported by Sentry (see stack trace image). Apprently, our help dialog creates a new `DC_Table` object, which runs the `onload_callback` with permission checks.

<img width="1317" alt="Bildschirmfoto 2024-08-19 um 14 04 49" src="https://github.com/user-attachments/assets/81e648b9-4bf5-447b-a791-068b08bf1476">

2024-09-20 09:09 UTC, Toflar approved these changes, later dismissed

2024-11-07 08:07 UTC, leofeyer requested changes
The same issue occurs in `tl_calendar_events.php`, `tl_form_field.php`, `tl_faq.php`, `tl_newsletter.php` and `tl_newsletter_recipients.php`. We should fix them all, shouldn‘t we?

2024-11-26 16:16 UTC, aschempp commented
Fixed in 9a15a5a42cc8a73b9468fd93c71d832e6b0e932a

2024-11-26 16:19 UTC, aschempp commented
Failing tests are not related.

2025-01-17 10:39 UTC, leofeyer approved these changes

2025-01-17 10:39 UTC, merged

2025-01-17 10:39 UTC, leofeyer commented
Thank you @aschempp.