Introduce the Twig variable "headline_attributes"
contao/contao pull request #7520
Opened 2024-09-06 22:45 UTC by richardhj

Fixes #7518

This PR fixes that the headline attributes can be overriden within the inhertence chain (similiar to existing variables like "text_atributes", "image_attributes, ...).

This is a bugfix, because the template did not work as intended 🤔 

Might be a low to no impact change, because, as stated in https://github.com/contao/contao/issues/7518#issuecomment-2333819257, people were overriding the entire block already.

2024-09-09 14:43 UTC, fritzmg commented
> This is a bugfix, because the template did not work as intended 🤔

How do you mean? This PR would break previously adjusted templates, wouldn't it?

2024-09-09 15:12 UTC, richardhj commented
> 
> How do you mean? This PR would break previously adjusted templates, wouldn't it?

Overriding headline attributes was (de facto) not possible before.

The only ways to override the headlines attributes as of now are 
1) to override the entire block:
```twig
{% block headline_attributes %}
    {{ attrs(headline.attributes|default).addClass('text-center text-3xl font-bold') }}
{% endblock %} 
```

2) or from inside the headline content element template (set and merge `attributes` there):
https://github.com/contao/contao/blob/6f8832ffea3c8454c90d0b09429c5654232afe39/core-bundle/contao/templates/twig/content_element/headline.html.twig#L7-L9

Regardless of whether people used 1) or 2) before, their templates won't break.

2024-09-12 10:42 UTC, leofeyer approved these changes
The changes make sense to me, but let‘s wait and see what @m-vo says.

2024-09-13 10:11 UTC, m-vo requested changes
IMHO these changes are wrong. Grouping everything under a single object is an intentional design decision in every component. See the explanation in https://github.com/contao/contao/issues/7518#issuecomment-2348570039.

2024-09-15 11:57 UTC, richardhj commented
#7518

2024-09-15 11:57 UTC, closed without merging