Specify dev tools howto
contao/contao pull request #7557
Opened 2024-09-27 07:43 UTC by de-es

Die Anleitung war nicht ganz eindeutig, daher eine Konkretisierung.

`composer bin all install` ist - zumindest mit einer aktuellen Composer-Version - auch obsolet, da das `composer update` schon die Dependencies für alle Tools in `vendor-bin` zieht. Aber es schadet ja auch nicht.

2024-09-27 08:25 UTC, fritzmg requested changes
The wording isn't quite correct. `composer update` installs the dependencies of `contao/contao` itself, not the code quality tools.

> `composer bin all install` ist - zumindest mit einer aktuellen Composer-Version - auch obsolet, da das composer update schon die Dependencies für alle Tools in vendor-bin zieht.

I cannot confirm that. `composer update` does not install `vendor-bin` for me as well.

2024-09-27 09:27 UTC, de-es commented
Also bei mir ist es definitiv auf dem System (Arch) so und ich habe es auch auf einem Debian 12 mit Composer 2.7.9 from scratch zusätzlich verifiziert. Die Dependencies werden installiert und die Tools laufen, ohne dass ich einmal `composer bin all install` ausgeführt habe. Mag vielleicht ein Feature sein, dass nicht in allen Konstellationen funktioniert. Daher habe ich es auch im PR nicht entfernt.

2024-09-29 15:46 UTC, aschempp commented
The behavior depends on the version of `bamarni/composer-bin-plugin` and your local configuration. In version 2 (the current one) the default was changed to forward the command: https://github.com/bamarni/composer-bin-plugin?tab=readme-ov-file#forward-command-forward-command

2024-09-29 16:00 UTC, fritzmg commented
I see, I only tested in `4.13` where we still use `1.x`.

2024-09-30 19:01 UTC, leofeyer approved these changes

2024-09-30 19:02 UTC, merged