Add CUD permissions for DCAs
contao/contao pull request #7591
Opened 2024-10-01 19:17 UTC by leofeyer

As discussed in the call, 

1. The `TableAccessVoter` should only deny a POST request if it tries to write to a field that is excluded and not allowed. Otherwise it should abstain.
2. The button should not be greyed out if the user is allowed to edit but there are no fields. If a user stumbles across an empty form, we want to display a hint why the field is empty and what they need to do to solve the problem.
3. We generally want to add `CUD` (without `R`) permissions to all tables.

This is a simplified mockup of how no. 3 could look like:

![](https://github.com/contao/contao/assets/1192057/2fe91da3-d500-423b-8d0d-c04cce62e416)

Note: We want to implement all three things at once.

_Originally posted by @leofeyer in https://github.com/contao/contao/issues/6451#issuecomment-1814703730_

2024-10-02 17:48 UTC, aschempp requested changes
Maybe that review is too early, then just ignore it 😅

The view should respect `closed`, `notCreatable`, `notEditable` etc in my opinion.

2024-10-02 17:48 UTC, aschempp commented on core-bundle/contao/dca/tl_user_group.php
> +			'options_callback'        => array('tl_user_group', 'getEditableDcas'),
This must be a listener and not a legacy class method!

2024-10-02 17:48 UTC, aschempp commented on core-bundle/contao/dca/tl_user_group.php
> +			if (!is_a($v['config']['dataContainer'] ?? null, DC_Table::class, true))
This should handle all tables imho, same as alexf. I also want my Isotope stuff with custom DC in there. Also for tl_files.

2025-01-23 00:07 UTC, zoglo commented
Just adding up for discussion since it's still 5.5 milestone and kinda ready? 👀

2025-01-23 08:27 UTC, leofeyer commented
It is not ready 😄

2025-11-18 09:50 UTC, aschempp commented
Superseeded by https://github.com/contao/contao/pull/9012

2025-11-18 09:50 UTC, closed without merging