Correctly set the ACE editor height
contao/contao pull request #7663
Opened 2024-10-22 14:47 UTC by leofeyer

Fixes #7602

Instead of setting `editor.container.maxHeight`, the script now sets `maxLines` dynamically.

2024-10-22 14:49 UTC, Toflar commented on core-bundle/contao/templates/backend/be_ace.html5
> +        if ('tl_files' === editor.container.closest('form').id) {
Looks like this should be an `eval` setting and not something hardcoded which other people cannot use?

2024-10-23 07:48 UTC, leofeyer commented on core-bundle/contao/templates/backend/be_ace.html5
> +        if ('tl_files' === editor.container.closest('form').id) {
The feature is now triggered by adding a `data-autosize` attribute: c78dcd50df5be3ca1785c43e6f18c1fa9114ffff

2024-10-23 08:15 UTC, fritzmg requested changes
In my test this PR causes to always only display 14 lines (at least in Firefox 131).

2024-10-23 08:33 UTC, bytehead commented
Seems to work for me (Firefox 131): 

![Bildschirmfoto 2024-10-23 um 10 32 41](https://github.com/user-attachments/assets/a61b3c98-5995-4cae-aefe-c359d21f5966)

2024-10-23 08:33 UTC, bytehead submitted a review, later dismissed

2024-10-23 08:37 UTC, fritzmg commented
@bytehead it works for me in the template editor as well - but not in the `code` content element for example.

2024-10-23 08:39 UTC, bytehead commented
Ah, I've missed that. Correct - in the `code` element it only shows 14 lines.

2024-10-23 09:00 UTC, leofeyer commented
That is the intended behavior. The editor only autosizes if the `data-autosize` attribute is set and that is only the case in the file manager.

2024-10-23 09:02 UTC, bytehead submitted a review, later dismissed

2024-10-23 09:52 UTC, bytehead approved these changes

2024-10-23 09:55 UTC, merged