Reduce redundant disallow rules in robots.txt
contao/contao pull request #7743
Opened 2024-11-25 02:24 UTC by CMSworker

Do not add contao disallow rules to a directive when the directive contains only one line with disallow:/

Fixes #7742 

Explained:

The contao disallow rules are not added, when
- there is only one directive within the record (= one line)
`1 === $directiveList->getLength()`
- AND the field name of the record is 'disallow'
`$directiveList->first()->getField() == 'disallow'`
- AND the value is '/'
`(string)$directiveList->first()->getValue() == '/'`

getLenght(), first(), getField() etc. are used according to [webignition/robots-txt-file/[...]DirectiveList.php](https://github.com/webignition/robots-txt-file/blob/master/src/DirectiveList/DirectiveList.php)

The contao disallow rules are still added when there are multiple rules within the directive or the directive is not disallow:/

2024-11-25 11:39 UTC, fritzmg requested changes
This will not work if another event listener adds such a directive _after_ the `RobotsTxtListener`. So this is the wrong approach and imho this does not need to be optimized in the first place.

If anything you would need to give the listener at least a very low priority.

2024-12-09 21:20 UTC, CMSworker commented
> This will not work if another event listener adds such a directive _after_ the `RobotsTxtListener`. If anything you would need to give the listener at least a very low priority.

This also applies to the previous (original, unchanged) Contao directive.

Why exactly do you think that it could be problematic if another listener adds the same directive? This would't change the result, if I got it right what you mean.

> I am not sure this needs to be optimized in the first place though.

Yeah, it is not "wrong" when Contao's additional disallow directives are set to each and every entry, even if there is already a general disallow rule present (and only such a single disallow rule)... You can also use `<p><span><span><span>Text</span></span></span></p>`, but it would be better to avoid adding unnecessary span tags...

I also know that you can combine all disallow rules in one block, that would result in a robots.txt link this:

```
User-agent: CCBot
User-agent: GPTBot
User-agent: Google-Extended
User-agent: Applebot-Extended
User-agent: GenAI
disallow:/
disallow:/contao/
disallow:/_contao/
```
Not wrong, but also... why adding these unnecessary disallow rules, when it can be fixed?

I assume that regular users (non-admin / experts) are not aware of that option and just copy the multi-line disallow examples from some random articles they find online (and end up with a extra long robots.txt as shown in the issue).

2024-12-10 10:21 UTC, fritzmg commented
> This also applies to the previous (original, unchanged) Contao directive.
> 
> Why exactly do you think that it could be problematic if another listener adds the same directive? This would't change the result, if I got it right what you mean.

What I meant is - if you have a `RobotsTxtEvent` listener like this:

```php
// src/EventListenerRobotsTxtListener.php
namespace App\EventListener;

use Contao\CoreBundle\Event\RobotsTxtEvent;;
use Symfony\Component\EventDispatcher\Attribute\AsEventListener;
use webignition\RobotsTxt\Directive\Directive;
use webignition\RobotsTxt\Directive\UserAgentDirective;
use webignition\RobotsTxt\Inspector\Inspector;
use webignition\RobotsTxt\Record\Record;

#[AsEventListener(priority: -1)]
class RobotsTxtListener
{
    public function __invoke(RobotsTxtEvent $event): void
    {
        $file = $event->getFile();
        $inspector = new Inspector($file);

        if (0 === $inspector->getDirectives()->getLength()) {
            $record = new Record();

            $userAgentDirectiveList = $record->getUserAgentDirectiveList();
            $userAgentDirectiveList->add(new UserAgentDirective('*'));

            $file->addRecord($record);
        }

        foreach ($file->getRecords() as $record) {
            $directiveList = $record->getDirectiveList();
            $directiveList->add(new Directive('Disallow', '/'));
        }
    }
}
```

you will again end up with.

```
user-agent:*
disallow:/contao/
disallow:/_contao/
disallow:/

sitemap:https://example.com/sitemap.xml
```

2024-12-12 14:52 UTC, leofeyer commented
As discussed in the call, this kind of optimization is best done in the library itself. Then it would work for everybody and not just for us.

@CMSworker Could you create a pull request here? https://github.com/webignition/robots-txt-file

2025-01-03 11:00 UTC, closed without merging