Fix base path for canonical URLs
contao/contao pull request #7768
Opened 2024-11-30 12:14 UTC by fritzmg

Same as #7767 for Contao 4.13.

2024-11-30 12:40 UTC, ausi requested changes

2024-11-30 12:40 UTC, ausi commented on core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
> +                $url = UrlUtil::makeAbsolute($url, $request->getSchemeAndHttpHost().'/'.$request->getBasePath());
```suggestion
                $url = UrlUtil::makeAbsolute($url, $request->getSchemeAndHttpHost().$request->getBasePath().'/');
```

2024-11-30 13:45 UTC, ausi approved these changes

2025-01-16 14:52 UTC, merged

2025-01-16 14:53 UTC, leofeyer commented
Thank you @fritzmg.