Consider the `addImage` checkbox when collecting RSS enclosures
contao/contao pull request #7789
Opened 2024-12-10 11:13 UTC by CMSworker

Fixes #7787

2024-12-10 11:34 UTC, fritzmg requested changes

2024-12-10 11:34 UTC, fritzmg commented on news-bundle/src/EventListener/NewsFeedListener.php
> +        if ($article->addImage == true && $article->singleSRC) {
```suggestion
        if ($article->addImage && $article->singleSRC) {
```

2024-12-10 15:17 UTC, fritzmg approved these changes

2025-01-03 10:59 UTC, leofeyer approved these changes

2025-01-03 10:59 UTC, merged

2025-01-03 10:59 UTC, leofeyer commented
Thank you @CMSworker.