Render nested fragments with allowedTypes option correctly
contao/contao pull request #7801
Opened 2024-12-16 14:29 UTC by bytehead

If you have fragments with `allowedTypes` configuration in the nested_fragments option, the debug command will fail:

```bash
php bin/console debug:fragments

In DebugFragmentsCommand.php line 93:
                                       
  Warning: Array to string conversion  
                                       
debug:fragments
```

Used config for the content element:

```php
#[AsContentElement(category: 'miscellaneous', nestedFragments: ['allowedTypes' => ['link', 'alias']])]
```

2024-12-19 11:28 UTC, aschempp commented on core-bundle/src/Command/DebugFragmentsCommand.php
> +                $v = 'true (allowed types: '.implode(', ', $v['allowedTypes']).')';
Maybe we could just implode if the value is an array? A debug output of `allowedFragments: alias, list` would work the same for me (and need less room)

2025-01-16 09:20 UTC, aschempp requested changes

2025-01-16 09:20 UTC, aschempp commented on core-bundle/src/Command/DebugFragmentsCommand.php
> +                $v = 'true (allowed types: '.implode(', ', $v['allowedTypes']).')';
```suggestion
            } elseif (\is_array($v) && array_is_list($v)) {
                $v = implode(', ', $v);
            } elseif (!is_scalar($v)) {
                // For non-list arrays, use YAML notation and fix indentation on multiline strings
                $v = Yaml::dump($v, indent: 2);
                $v = explode("\n", $v);
                array_walk($v, static fn (&$vv, $i) => $vv = $i > 0 ? str_repeat(' ', $length+3).$vv : $vv);
                $v = implode("\n", $v);
```

will render all array values nicely:

<img width="367" alt="Bildschirmfoto 2025-01-16 um 10 21 25" src="https://github.com/user-attachments/assets/c2acec50-1b7e-46c1-8b42-7ae5a5a6b1d2" />

2025-01-16 10:40 UTC, aschempp approved these changes

2025-01-16 11:02 UTC, leofeyer approved these changes

2025-01-16 11:03 UTC, leofeyer commented
Thank you @bytehead.

2025-01-16 11:03 UTC, merged