Support predefined image sizes in {{picture::}} tag #777
contao/contao pull request #781
Opened 2019-09-20 19:36 UTC by simonreitinger

Example: 

### Template
```
{{picture::files/foo.jpg?config=_foobar}}
```

### config.yml
```yml
contao:
    image:
        sizes:
            foobar:
                width: 100
                height: 200
                resizeMode: 'box'
                zoom: 100
                cssClass: 'foobar-image'
                densities: '1x, 2x'
                sizes: '100vw'
                items:
                    -
                        width: 50
                        height: 50
                        resizeMode: 'box'
                        zoom: 100
                        cssClass: 'foobar-image'
                        densities: '0.5x, 2x'
                        sizes: '50vw'
                        media: '(max-width: 900px)'
```

2019-09-22 11:40 UTC, ausi requested changes
I think we should reuse the `size` parameter here.

And IMO this is a bug fix for 4.8.

2019-09-22 11:40 UTC, ausi commented on core-bundle/src/Resources/contao/library/Contao/InsertTags.php
>  									$size = (int) $value;
```suggestion
									$size = is_numeric($value) ? (int) $value : $value;
```

2019-09-23 07:29 UTC, ausi approved these changes

2019-09-25 20:06 UTC, merged

2019-09-25 20:06 UTC, leofeyer commented
Thank you @simonreitinger.