Allow adding additional login providers to the back end login screen
contao/contao pull request #7817
Opened 2024-12-20 14:11 UTC by leofeyer

By using the Knp menu builder for the additional login providers, third-party extensions such as **contao.id** can easily add their own button.

<img width="1080" alt="" src="https://github.com/user-attachments/assets/ec8cc6ef-277f-44fb-bf9e-a37a8e7980f5" />

@sheeep @bytehead /cc

2024-12-20 14:45 UTC, Toflar commented
LGTM but I guess better to be approved by @bytehead

2024-12-20 15:03 UTC, fritzmg approved these changes, later dismissed
LGTM, but haven't tested.

2024-12-20 23:38 UTC, zoglo submitted a review, later dismissed

2025-01-06 15:07 UTC, bytehead commented
To simplify and unify the look of custom providers it would be useful to have properties which can be used for `icon` and `icon-dark`. Otherwise every third party provider has to provide some sort of CSS. What do you think?

2025-01-07 08:39 UTC, bytehead submitted a review, later dismissed
❤️

2025-01-07 08:57 UTC, bytehead requested changes

2025-01-07 08:57 UTC, bytehead commented on core-bundle/templates/Menu/backend_login.html.twig
> +            .login-providers .{{ item.name}} .tl_submit {
```suggestion
            .login-providers .{{ item.name}} .has-icon {
```

Nitpick 🙃

2025-01-07 09:13 UTC, bytehead approved these changes

2025-01-07 10:34 UTC, merged