Add WebP image format
contao/contao pull request #824
Opened 2019-10-06 14:27 UTC by xchs

Add WebP image format to the list of allowed upload and download file types.

2019-10-06 19:40 UTC, leofeyer commented
If @ausi confirms this change, the PR needs to be rebased onto the `4.8` branch.

2019-10-06 19:43 UTC, xchs commented
> the PR needs to be rebased onto the `4.8` branch

So do you consider this a bugfix, right?

2019-10-06 19:50 UTC, leofeyer commented
If @ausi has not deliberately left out `webp` at this place, then yes.

2019-10-07 07:04 UTC, ausi requested changes
Aside from the missing commas this looks good to me 👍

2019-10-07 07:04 UTC, ausi commented on core-bundle/src/Resources/contao/config/default.php
> +	= 'jpg,jpeg,gif,png,ico,svg,svgz,webp'
Missing comma

```suggestion
	= 'jpg,jpeg,gif,png,ico,svg,svgz,webp,'
```

2019-10-07 07:04 UTC, ausi commented on core-bundle/src/Resources/contao/config/default.php
> +	= 'jpg,jpeg,gif,png,svg,svgz,webp'
```suggestion
	= 'jpg,jpeg,gif,png,svg,svgz,webp,'
```

2019-10-07 15:11 UTC, closed without merging

2019-10-07 19:23 UTC, ausi commented
Followup pull request: #829