ContaoFramework::setConstants()
contao/contao pull request #868
Opened 2019-10-25 13:20 UTC by leofeyer

This PR is work in progress, but I want to discuss the concept with you before I continue working on it.

As you know, we have a really handy `ContaoFramework::getAdapter()` method, which allows us to mock methods of the Contao 3 framework in unit tests. It always bothered me that we do not have the same for constants and thus have to use `@runInSeparateProcess` extensively.

This PR adds two methods to the `contao.framework` service, which allow us to set and get constants in a backwards compatible way. The advantage should be obvious: We can now mock the `getConstant()` method in our unit tests and remove most of the `@runInSeparateProcess` annotations.

@contao/developers WDYT?

2019-10-25 14:03 UTC, Toflar commented
Interesting concept 👍 

> We can now mock the `getConstant()` method in our unit tests and remove most of the `@runInSeparateProcess` annotations.

Can you add just one example to this PR so we can actually see if that would work 😄

2019-10-25 14:36 UTC, leofeyer commented
I have removed the annotation in the `FrontendControllerTest` class in 26ed7cbacffa9f791e641f40f1c7126882091c0a. The bigger advantage – namely being able to use `$this->framework->getConstant('CURRENT_ID')` in the new code – would come in handy here:

https://github.com/contao/contao/blob/7af5e8f1c8a787070e9f9a7d51ff29b99a3634a7/core-bundle/src/Routing/PreviewUrlGenerator.php#L61-L63

2019-10-25 14:38 UTC, Toflar commented
I see. Yeah, looks good to me 👍

2019-10-28 09:17 UTC, aschempp requested changes
Very nice idea indeed! This would also allow some kind of forward-compatibility when changing constants in the future.

However, I don't think we should store any of the constants internally. The default framework behavior should be to set and get constants from the PHP runtime. Only unit tests should be able to mock the methods to manipulate the environment accordingly.

2019-10-28 10:14 UTC, leofeyer commented
You mean this?

```php
public function setConstant($name, $value): void
{
    if (\defined($name)) {
        throw new \InvalidArgumentException('…');
    }

    \define($name, $value);
}

public function getConstant($name)
{
    return \defined($name) ? $name : null;
}
```

2019-10-28 22:04 UTC, ausi commented
> You mean this?

Or only the `getConstant()` method without the `setConstant()`? 
Or do we also run code in tests that try to set constants?

2019-10-29 07:21 UTC, leofeyer commented
Nope, we are not. We could omit the `setConstant()` method entirely.

2019-10-29 13:00 UTC, aschempp commented
I think like this. And we absolutely do want a `setConstant()`, because we can (later) use it to rewrite constants, trigger deprecations errors etc.

```php
public function setConstant($name, $value): void
{
    \define($name, $value);
}

public function getConstant($name)
{
    return \constant($name);
}
```

2019-10-29 14:19 UTC, leofeyer commented
Agreed. Except we need the `if (\defined())` check in the `setConstant()` method.

2019-10-29 14:41 UTC, aschempp commented
> Agreed. Except we need the `if (!\defined())` check in the `setConstant()` method.

Why? There's not check in the current code, and PHP will throw it's warning/error/whatever as it currently does…

2019-10-29 14:41 UTC, aschempp commented
> > Agreed. Except we need the `if (!\defined())` check in the `setConstant()` method.
> 
> Why? There's not check in the current code, and PHP will throw it's warning/error/whatever as it currently does…

Or mabye we do so I can handle the `isset()` case?

2019-10-29 14:47 UTC, leofeyer commented
> Why? There's not check in the current code

Yes, there is: 

https://github.com/contao/contao/blob/3a48a3dd0a441342121a388f014dce66ea8c4cc0/core-bundle/src/Framework/ContaoFramework.php#L166-L176

2019-10-30 07:34 UTC, aschempp commented
Yes, but that's only our framework constants. There are plenty more constants (like `CURRENT_ID` in `DataContainer`). Thats why I mean we might also have a `hasConstant()` method which we should use wherever we currently use `\defined()`.

2019-10-30 12:42 UTC, leofeyer commented
Since we are using the `constant()` function, we could also use the method like this:

```php
if (null !== ($id = $this->framework->getConstant('CURRENT_ID'))) {
}
```

Which is even shorter than:

```php
$id = null;

if ($this->framework->hasConstant('CURRENT_ID'))) {
    $id = $this->framework->getConstant('CURRENT_ID');
}
```

2019-10-31 08:41 UTC, aschempp commented
True, but then we need a `\defined()` check, otherwise PHP will raise a warning.

2019-10-31 09:04 UTC, leofeyer commented
So this?

```php
public function getConstant($name)
{
    return \defined($name) ? \constant($name) : null;
}
```

2019-11-11 11:44 UTC, leofeyer commented
@contao/developers I have adjusted the code according to what we have discussed. Can you please recheck before I continue working on this one?

2019-11-11 11:46 UTC, Toflar commented
LGTM

2019-11-18 20:13 UTC, aschempp commented
Looks good. Some constants previously were set without checking if they are defined. Are we fine with now ignoring that case?

2019-11-18 21:13 UTC, leofeyer commented
Not sure. Ignoring it does allow us to remove some more `@runInSeparateProcess` annotations. I cannot think of any disadvantages right now, but that does not mean that there are none. 😄

2019-12-03 12:53 UTC, aschempp commented
I have updated the PR. Constants are now stored per framework instance. This means `Kernel::shutdown()` or creating a new kernel (and therefore a new container) can override constants.

I have also added deprecation warnings about constants. They are mostly meant to rewrite constants in the future, so developers can already switch to `ContaoFramework::getConstant()` and will be notified how to rewrite their code in the future.

2019-12-03 12:55 UTC, aschempp commented
Also, what about all the existing uses of the constants? Should we rewrite ever use of `TL_MODE` to the method (which will trigger a deprecation) or the new service?

2019-12-03 13:14 UTC, Toflar approved these changes
I'm not sure deprecations make sense for those that already have a replacement because you should use the replacement instead of the framework in that case :) It's helpful as documentation though which makes me think about maybe putting those into the UPGRADE.md or so.

2019-12-03 13:21 UTC, ausi requested changes
> Constants are now stored per framework instance.

I don’t like this, in https://github.com/contao/contao/pull/868#pullrequestreview-307716349 you said yourself *“I don't think we should store any of the constants internally”*.
For unit tests we can always mock the `getConstant()` method to return what we want. For other use cases it should not be possible to get a different value from `getConstant()` than from the constant itself.

> I have also added deprecation warnings about constants.

👍

> should we rewrite ever use of `TL_MODE` to the method

I don’t think we should change the legacy code. But we should use `getConstant()` in all the new code where we have access to the framework.

2019-12-03 14:18 UTC, aschempp commented
> > Constants are now stored per framework instance.
> 
> I don’t like this, in [#868 (review)](https://github.com/contao/contao/pull/868#pullrequestreview-307716349) you said yourself _“I don't think we should store any of the constants internally”_.
> For unit tests we can always mock the `getConstant()` method to return what we want. For other use cases it should not be possible to get a different value from `getConstant()` than from the constant itself.

The background for this change request is here: https://github.com/symfony/symfony/pull/34688

2019-12-03 14:46 UTC, leofeyer reviewed
I really do not like the deprecation stuff, especially not the static method to add custom constants. It adds functionality that we do not necessarily need to a class that already has too much functionality in it.

The initial point of the PR was to provide a mockable way to get the value of a constant. Can we focus on that again please?

2019-12-12 11:01 UTC, leofeyer commented
As discussed with @aschempp, we should close this PR and add a private `getCurrentId()` method to the preview URL generator, which rebuilds the CURRENT_ID logic. Later, if we know that the `getCurrentId()` logic works, we might use it to replace the CURRENT_ID constant altogether.

2019-12-12 11:01 UTC, closed without merging