Validate the start and stop date of a page
contao/contao pull request #896
Opened 2019-10-29 11:55 UTC by leofeyer

Fixes #812 

If we agree that the changes are correct, we have to apply them to articles, news, events etc. as well.

2019-10-29 12:22 UTC, aschempp commented
Can we make this a generic callback listener that can be registered on any DCA field. Every DCA will otherwise have to copy the whole code.

2019-10-29 14:08 UTC, leofeyer commented
IDK. Where would you put that generic listener? And how would you configure it (e.g. field names)?

2019-10-29 14:33 UTC, aschempp requested changes
I have added an actual event listener to implement the same code as yours does. The event listener can handle any table, and there can be additional instances if the fields are not called `start` and `stop`.

When merging this into Contao 4.8, we can also use the translator instead of globals and use services tags instead of adjusting the DCA to register the callbacks.

Your code is still there, one should be cleaned up before merging 😉

2019-10-29 14:42 UTC, leofeyer commented
I see and I agree. However, I would prefer to add this as a new feature in Contao 4.9 then so we do not have to do the work twice (the listener also needs a unit test).

2019-10-29 14:43 UTC, aschempp commented
You mean no validation in Contao 4.4? I would be fine with that.

2019-10-29 17:06 UTC, Mynyx commented
The title of the ticket #812 is "Validate stop date > start date", but the implementation is stop date >= start date.

2019-10-29 17:08 UTC, fritzmg commented
@Mynyx what's your point? ;) Why should start == stop be valid?

2019-10-29 19:41 UTC, Mynyx commented
> @Mynyx what's your point? ;) Why should start == stop be valid?

It should not be valid, but the implementations in this pull request would accept it as valid.

2019-11-11 11:34 UTC, leofeyer commented
@aschempp I have adjusted the PR according to your suggestions. Can you please check again before I continue working on it?

2019-11-18 20:11 UTC, aschempp commented
Why did you not use the service tags/annotations to register the callbacks?

2019-11-18 21:10 UTC, leofeyer commented
Do you mean the `@Callback` annotation?

2019-11-18 21:13 UTC, m-vo commented
... or the service tagged with `name: 'contao.callback', callback: '...'`

2019-11-19 15:57 UTC, aschempp commented
Yes, either of these would be better to lead as an example 😊

2019-12-04 15:43 UTC, leofeyer commented
Changed in a55254d5e8c407abf74eda628cb99aed6d60a623. Any other remarks?

2019-12-04 17:57 UTC, Mynyx requested changes
start == stop should not be valid.

2019-12-04 17:57 UTC, Mynyx commented on core-bundle/src/DataContainer/StartStopValidator.php
> +        if ($stop && $value > $stop) {
```suggestion
        if ($stop && $value >= $stop) {
```

2019-12-04 17:57 UTC, Mynyx commented on core-bundle/src/Resources/contao/languages/en/default.xlf
> +        <source>The start time cannot be after the end time!</source>
```suggestion
        <source>The start time must be before the end time!</source>
```

2019-12-04 17:57 UTC, Mynyx commented on core-bundle/src/Resources/contao/languages/en/default.xlf
> +        <source>The end time cannot be before the start time!</source>
```suggestion
        <source>The end time must be after the start time!</source>
```

2019-12-04 17:57 UTC, Mynyx commented on core-bundle/src/DataContainer/StartStopValidator.php
> +        if ($start && $start > $value) {
```suggestion
        if ($start && $start >= $value) {
```

2019-12-05 17:14 UTC, leofeyer commented
> start == stop should not be valid.

Changed in 51dc5db4c9df62bb965b854ff71d5917f4cc9962.

2019-12-05 18:57 UTC, hhogrebe commented
Maybe the translation ids should also be amended.

2019-12-05 18:58 UTC, Mynyx commented
Maybe the translation IDs should also be amended.

2019-12-06 11:35 UTC, leofeyer commented
@contao/developers This PR is RTM now.

2019-12-06 11:50 UTC, aschempp reviewed
Can you explain what the `StartStopValidatorPass` is for?

2019-12-06 11:56 UTC, leofeyer commented
It adds the calendar and news bundle fields so they can use the callback, too?

2019-12-06 11:58 UTC, aschempp commented
So the core bundle is adding listeners for the news and calendar bundle??

2019-12-06 11:59 UTC, leofeyer commented
No? Can you please review carefully? There is one `StartStopValidatorPass` in the calendar bundle and one in the news bundle. Zero in the core bundle.

2019-12-09 15:17 UTC, aschempp commented
As discussed, we should try to optimize this, by having a DCA flag instead of a compiler pass per bundle. Something like `start => eval => lowerThan => 'stop'`. Or maybe there should be multiple validators?

```
'fields' => [
    'start' => [
        'eval' => ['validate' => 'lt:stop AND gte:foobar']
    ]
```

2019-12-10 15:33 UTC, aschempp reviewed
As discussed, we should try to optimize this, by having a DCA flag instead of a compiler pass per bundle. Something like `start => eval => lowerThan => 'stop'`. Or maybe there should be multiple validators?

```
'fields' => [
    'start' => [
        'eval' => ['validate' => 'lt:stop AND gte:foobar']
    ]
```

2019-12-18 16:38 UTC, Toflar commented
The Symfony Validator solves this by using the Expression Language ;)

2019-12-27 13:07 UTC, Toflar commented
Draft PR for an alternative approach: https://github.com/contao/contao/pull/1134

2020-08-10 06:59 UTC, closed without merging